### ISSUE TITLE
With tcpdump, how to filter real trafic in a vxlan environnement 

### ISSUE THREAD

**Issue by nabsdcnm** [the-tcpdump-group/tcpdump#1004]
Hi everdybody,

Can you please help me.
I have done a tcpdump on a vxlan environement and i don't find how to filter trafic inside vxlan packet.
So my question is: With tcpdump, how to filter real trafic in a vxlan environnement ?

Thanks a lot for your lights.

Regards
N.

**Comment by infrastation** [comment]
tcpdump supports decoding of VXLAN packets. Packet filtering is done in libpcap, and libpcap filtering currently does not have support for VXLAN directly. The only way you could test the contents of a VXLAN packet now is through the `link[x:y]` expressions as explained in **[pcap-filter](https://www.tcpdump.org/manpages/pcap-filter.7.html)**(7), in other words, you would need to know which protocol field is at which packet offset. For this to improve, someone would need to implement VXLAN support in libpcap.

**Comment by infrastation** [comment]
As far as a support request goes, this has been addressed. If anybody is willing to add VXLAN support to libpcap, they would need to prepare source code changes for libpcap as a separate matter.
