### ISSUE TITLE
Run TCPDump in local machine

### ISSUE THREAD

**Issue by faysalhossain2007** [the-tcpdump-group/tcpdump#1013]
Hi,

I want to run TCPDump in my local desktop. To be specific, I want to install the latest version on my local desktop and then want to run some testing scripts to test different functions. How can I do that?

I appreciate your help!

**Comment by guyharris** [comment]
> To be specific, I want to install the latest version on my local desktop

At lest some operating systems provide tcpdump as part of the operating system, either installing it by default or allowing it to be installed as an option.

Most Linux distributions, macOS, and the \*BSDs all do, as do, I think, Solaris (which can run on a PC, but it's probably not your desktop OS) and AIX (which is almost certainly not your desktop OS).

However, the version that they provide isn't necessarily the latest released version, which is 4.99.1.

So, if you're running on one of those OSes, do you need to run 4.99.1, or would whatever version the OS provides be good enough?  Or do you want to run the tip of the 4.99 branch of the GIt repository, or the tip of the main branch of the Git repository?  If so, then you'll need to build it from source.

If your desktop is running Windows, it does *not* come with tcpdump and doesn't have it as an option, and nobody is currently providing binary versions of it for Windows, so you'd have to build it from source.

**Comment by faysalhossain2007** [comment]
Thanks a lot for the comments. I want to run it on my Linux machine. Latest or one version older sounds fine to me. Does Linux provider auto installation of tcpdump?

Can you give me also a pointer to how can I run some test scripts?

**Comment by infrastation** [comment]
Please use a search engine and search for the phrase "how to install tcpdump on Linux". And/or please refer to the user guide, administrator guide or any other documentation that comes with your Linux system. As to "some test scripts", is this true that it is a part of your university assignment?

**Comment by faysalhossain2007** [comment]
Thanks for your suggestion. Yes, I already followed existing tutorials and was able to run tcpdump on my local machine. But I am not able to figure out how I can write a custom script to test a specific function or module. That's why I am a bit concerned that if I want to do that, does it need to be built from the source or not?
And it is not a part of my university assignment, I am trying to understand some specific packet traversal and operations from tcpdump. As it is one well-documented and maintained open-source software, that's why I thought to ask for others' help which may give me a jump start.

**Comment by guyharris** [comment]
> But I am not able to figure out how I can write a custom script to test a specific function or module.

Are you talking about white-box or black-box testing here?

**Comment by faysalhossain2007** [comment]
white-box testing.

**Comment by guyharris** [comment]
> white-box testing.

Then the best thing to do is probably to download the source and start reading.  Unfortunately, we don't have anything like, to use the IBM term, a "program logic manual" for tcpdump giving a detailed description of how it works.

**Comment by infrastation** [comment]
Perhaps `make check` is the closest thing to what you are looking for.

**Comment by fxlb** [comment]
On 16/10/2022 20:56, faysalhossain2007 wrote:
> white-box testing.

You can configure and build tcpdump with:
$ ./configure --enable-instrument-functions
$ make -s

(more information in the message of the commit 65f4c88d27fa3a333b7f5303c34d8d10999e1d4d.)

After if you e.g. read a pcap file, you will have:
$ ./tcpdump -#nv -r tests/tcp-handshake-nano.pcap

[>> main (0)
 [>> nd_init (1) from main tcpdump.c:1497]
  [>> strlcpy (2) from nd_init netdissect.c:80]
  [<< strlcpy (2)
 [<< nd_init (1)
[...]
 [>> get_if_printer (1) from main tcpdump.c:2519]
  [>> lookup_printer (2) from get_if_printer print.c:305]
  [<< lookup_printer (2)
 [<< get_if_printer (1)
[...]
 [>> print_packet (1) from pcap_offline_read savefile.c:682]
[...]
  [>> pretty_print_packet (2) from print_packet tcpdump.c:3170]
[...]
   [>> sll_if_print (3) from pretty_print_packet print.c:413]
[...]
    [>> ethertype_print (4) from sll_if_print print-sll.c:329]
     [>> ip_print (5) from ethertype_print print-ether.c:537]
[...]
      [>> ip_demux_print (6) from ip_print print-ip.c:487]
       [>> tcp_print (7) from ip_demux_print print-ip-demux.c:99]
[...]

**Comment by faysalhossain2007** [comment]
Thanks a lot for all those pointers! I appreciate all of your help. I will try out these approaches and will keep you posted.

**Comment by infrastation** [comment]
Alright, this is resolved, if you run into a different problem, please open a separate issue as and if required.
