### ISSUE TITLE
PGM: Unknown option needs different opt_len

### ISSUE THREAD

**Issue by mruprich** [the-tcpdump-group/tcpdump#1024]
Hi,
when PGM packet is being parsed, the default value for an unknown option needs a bit different handling. The code is as follows:
```
default:
                    ND_PRINT(" OPT_%02X [%u] ", opt_type, opt_len);
                    bp += opt_len;
                    opts_len -= opt_len;
                    break;
                }
```

The problem here is that this only works for the first option, if there are more than one, it will not read the values properly. Looking at the RFC for PGM, the opt_len is "The Length field is the total length of the option in bytes" and from the examples, it should be the total length INCLUDING the option header. In the while loop, the opt_type and opt_len are extracted and the bp pointer is moved one byte each time:
```

while (opts_len) {
                if (opts_len < PGM_MIN_OPT_LEN) {
                    ND_PRINT("[Total option length leaves no room for final option]");
                    return;
                }
                opt_type = GET_U_1(bp);
                bp++;
                opt_len = GET_U_1(bp);
                bp++;
```
But at the end, the whole opt_len is added to the bp pointer. This should be "bp += opt_len - 2" since tcpdump already extracted these two bytes from the packet. I have a sample SPM packet capture that looks like this when parsed with tcpdump:
```
tcpdump -c 1 -r xx.pcap -v -T pgm
reading from file xx.pcap, link-type EN10MB (Ethernet), snapshot length 262144
dropped privs to tcpdump
18:02:55.992148 IP (tos 0x0, ttl 16, id 58109, offset 0, flags [DF], proto UDP (17), length 122)
    192.168.193.237.63846 > 239.90.0.26.19026: 26198 > 19026: PGM, length 0 0xc0a85322cff9 SPM seq 3835 trail 1 lead 545 nla 192.168.193.237 OPTS LEN 58 OPT_21 [30] [Bad option, length 0 < 4] [94]
```
This is the output with "bp += opt_len - 2" in the default part of the switch posted above:
```
tcpdump -c 1 -r xx.pcap -v -T pgm
reading from file xx.pcap, link-type EN10MB (Ethernet), snapshot length 262144
dropped privs to tcpdump
18:02:55.992148 IP (tos 0x0, ttl 16, id 58109, offset 0, flags [DF], proto UDP (17), length 122)
    192.168.193.237.63846 > 239.90.0.26.19026: 26198 > 19026: PGM, length 0 0xc0a85322cff9 SPM seq 3835 trail 1 lead 545 nla 192.168.193.237 OPTS LEN 58 OPT_21 [30]  OPT_29 [8]  OPT_A2 [16]  [94]
```
Looking at the raw dump of the packet:
```
tcpdump -x -c 1 -r xx.pcap -v -T pgm
reading from file xx.pcap, link-type EN10MB (Ethernet), snapshot length 262144
dropped privs to tcpdump
18:02:55.992148 IP (tos 0x0, ttl 16, id 58109, offset 0, flags [DF], proto UDP (17), length 122)
    192.168.193.237.63846 > 239.90.0.26.19026: 26198 > 19026: PGM, length 0 0xc0a85322cff9 SPM seq 3835 trail 1 lead 545 nla 192.168.193.237 OPTS LEN 58 OPT_21 [30]  OPT_29 [8]  OPT_A2 [16]  [94]
	0x0000:  4500 007a e2fd 4000 1011 156b c0a8 c1ed
	0x0010:  ef5a 001a f966 4a52 0066 b491 6656 4a52
	0x0020:  0001 005e c0a8 5322 cff9 0000 0000 0efb
	0x0030:  0000 0001 0000 0221 0001 0000 c0a8 c1ed
	0x0040:  0004 003a 211e 0000 04ef 5a00 1a01 0000
	0x0050:  3a98 004a 524a 5200 0000 0007 7c00 0001
	0x0060:  f402 2908 0000 786d 616e a210 0000 4c52
	0x0070:  4856 4945 5f43 4e54 524c
```
Last four lines are the options:
```
        0x0040:  0004 003a 211e 0000 04ef 5a00 1a01 0000
	0x0050:  3a98 004a 524a 5200 0000 0007 7c00 0001
	0x0060:  f402 2908 0000 786d 616e a210 0000 4c52
	0x0070:  4856 4945 5f43 4e54 524c
```
0004 003a are the 4 octets corresponding to the overall option length (opts_len) which is 3a (58 = 4 + 30 + 8 + 16). When parsing the first option 211e ... 21 is the option type and 1e is option length, which is 30. But if you move bp pointer two bytes ahead after reading opt_type and opt_len and then add 30, you end up with this in the bp pointer:
```
                           0000 786d 616e a210 0000 4c52
	0x0070:  4856 4945 5f43 4e54 524c
```
So the next option in line reads as opt_len = 00 and thus it fails with [Bad option, length 0 < 4] when in fact, the bp should move just 28 bytes and end up with this:
```
                      2908 0000 786d 616e a210 0000 4c52
	0x0070:  4856 4945 5f43 4e54 524c
```
Resulting in opt_len = 8 for the next one and finally this for the last option, after moving bp 8 bytes ahead:
```
                                          a210 0000 4c52
	0x0070:  4856 4945 5f43 4e54 524c
```
Which is the last option with the length of 16.

Note:
I am posting this as an issue and not as a PR since there is one problem with the current PGM captures. The files pgm_opts_asan.pcap, pgm_opts_asan_2.pcap and pgm_opts_asan_3.pcap do not look valid to me. Even the IP part looks weird when parsed:
```
tcpdump -c 1 -v -r pgm_opts_asan_2.pcap 
reading from file pgm_opts_asan_2.pcap, link-type EN10MB (Ethernet), snapshot length 95
dropped privs to tcpdump
20:04:16.587271427 IP (tos 0x41,ECT(1), id 0, offset 0, flags [none], proto PGM (113), length 32639, options (unknown 89 [bad length 232]), bad cksum 5959 (->96b9)!)
```
I think I saw some fix in git for a CVE a while ago that said that these packet captures were actually marked as invalid before some bounds check was added. Anyway the problem with PGM is that with this change, all of these end up with this:
```
128.121.89.107 > 89-89-16-63.abo.bbox.fr: 128.121.89.107.4 > 89-89-16-63.abo.bbox.fr.225: PGM, length 0 0x3414eb1f0022 UNKNOWN type 0x1f OPTS LEN 225 OPT_1F [13] [Bad OPT_LENGTH option, length 12 != 4]
```
I am not convinced that these three packet captures are OK. So the thing is that these will definitely fail with a PR if you run a scratch build and run the tests.

Looking forward to any feedback.
Thanks and regards,
Michal Ruprich

**Comment by mruprich** [comment]
Hi, did anyone have time to look at this? Thanks.

**Comment by mruprich** [comment]
Hi, just asking again if anyone had time to go over this?

**Comment by mruprich** [comment]
Hello again, is there anything I can do to get someone to take a look at this? Is some info missing here? Anything I can provide from my side? Thanks.

**Comment by fxlb** [comment]
FYI, there is an update to PGM printer with 9a3eebde95cf1032ac68ae4312e2db14bb1fe58d.

**Comment by mruprich** [comment]
Thanks, https://github.com/the-tcpdump-group/tcpdump/commit/09b0447fad52298440e05e7368f9d24492d0b0fe did it.
