### ISSUE TITLE
Default link type LINUX_SLL2 is not supported on Solaris

### ISSUE THREAD

**Issue by l1gi** [the-tcpdump-group/tcpdump#1057]
Hello,

this is a regression to #850. Though having default link type LINUX_SLL2 on Linux is a good idea, on Solaris and other non Linux platforms it is not.

The fix is to either:

- select appropriate default link type for known platforms
- set the default just for Linux
- not set default at all

What fix type do you prefer and why, please?

On Solaris a quick fix could look like this, but I don't like it:
> -#if defined(DLT_LINUX_SLL2) && defined(HAVE_PCAP_SET_DATALINK)
> +#if defined(__linux__) && defined(DLT_LINUX_SLL2) && defined(HAVE_PCAP_SET_DATALINK)

Thank you,
Martin

**Comment by l1gi** [comment]
Actually this is happening on Solaris:
> # tcpdump -i any
> tcpdump: LINUX_SLL2 is not one of the DLTs supported by this device
> # uname -a
> SunOS ST146 5.11 11.4.60.146.0 i86pc i386 i86pc virtualbox

**Comment by guyharris** [comment]
Probably the best way to fix this would be "select appropriate default link type for known platforms".

This means defaulting to `DLT_LINUX_SLL2` on the "any" device *only* if the "any" device defaults to `DLT_LINUX_SLL` *and* supports `DLT_LINUX_SLL2` in addition to `DLT_LINUX_SLL`.

**Comment by guyharris** [comment]
(The same problem happens on macOS if you build with the macOS libpcap.

Yes, macOS's libpcap supports an "any" device; supporting it in tcpdump.org's libpcap would involve supporting macOS's PKTAP mechanism, preferably *not* by picking up Apple's code, which is covered the the APSL, a license with patent clauses, which I'd prefer to avoid if at all possible so as not to add extra licensing complications to libpcap.)

**Comment by fxlb** [comment]
> On Solaris a quick fix could look like this, but I don't like it:

Why?

**Comment by l1gi** [comment]
> > On Solaris a quick fix could look like this, but I don't like it:
> 
> Why?

Because it 'fixes' just Solaris. There are a lot of other platforms.

**Comment by fxlb** [comment]
> There are a lot of other platforms.

With a "any" interface, outside Solaris and macOS?

**Comment by l1gi** [comment]
> > There are a lot of other platforms.
> 
> With a "any" interface, except Solaris and macOS?

Okay, I don't know. Could you elaborate, please?

**Comment by infrastation** [comment]
Francois-Xavier likely means that whilst the `any` pseudo-interface still remains to be documented properly (see the-tcpdump-group/libpcap#1055), so far it has been seen on Linux, macOS and Solaris only.

For reference, my Solaris 11.4.42.111.0 does not have `any`, as far as the current master branch of tcpdump and libpcap see. Which specific Solaris do you use and what is the output of `tcpdump -D` and `tcpdump -i any -L`?

**Comment by guyharris** [comment]
On my 11.4.42.111.0 Solaris VM, `tcpdump -D`, which runs the tcpdump that comes with the OS using the libpcap that comes with the OS, prints

```
1.net0 [Up, Running]
2.lo0 [Up, Running, Loopback]
3.any (Pseudo-device that captures on all interfaces) [Loopback]
```

and `tcpdump -i any -L` prints

```
Data link types for any (use option -y to set):
  IPNET (Solaris ipnet)
```

If I build tcpdump from the tip of the main branch, but do *not* build libpcap, so that tcpdump is built with the libpcap that comes with the OS, I get the same behavior as I get from the tcpdump that comes with the OS.

Unfortunately, Solaris isn't open-source any more, so, unless support for the "any" device was in OpenSolaris or was independently added in Illumos, it'll take some looking at Oracle documentation or, if the mechanism used for the "any" device isn't documented, reverse-engineering to implement it in tcpdump.org libpcap.  (And if the changes are under the CDDL, that has a patent clause, so I'd be loath to pick up that code.)

**Comment by guyharris** [comment]
> so far it has been seen on Linux, macOS and Solaris only.

Emphasis on the "so far"; I'd prefer not to embed an assumption that no \*BSD, for example, would implement it and that Npcap won't ever implement it, or that any future implementation in any OS would necessarily use `DLT_LINUX_SLL` or `DLT_LINUX_SLL2`.

**Comment by infrastation** [comment]
illumos (as available in OmniOS r151046) does not implement `any`, at least not out of the box.

**Comment by guyharris** [comment]
And rpcap throws an extra twist into the mix - you might be capturing on a Linux box from a non-Linux box, or on a non-Linux box from a Linux box - so that's another reason to have code in tcpdump that doesn't make "any"-device assumptions based on the platform for which tcpdump is compiled.

**Comment by guyharris** [comment]
It turns out that the Solaris "any" device is just another device to which you can bind a BPF device, so the only Special Magic needed is to provide it, if available, in `pcap_findalldevs()`.

**Comment by fxlb** [comment]
> any (Pseudo-device that captures on all interfaces)

FYI: https://github.com/oracle/solaris-userland/blob/master/components/libpcap/patches/pcap-bpf.c.patch

**Comment by fxlb** [comment]
In the above patch: "This is an in-house patch and will eventually be sent upstream."

**Comment by fxlb** [comment]
Applying  this patch, updating `add_dev` to `pcap_add_dev` on "SunOS unstable11x 5.11 11.3 i386" or "Oracle Corporation SunOS 5.11 11.3 June 2018" (sparc) allows `tcpdump -D` to show the `any` interface.

**Comment by l1gi** [comment]
> Unfortunately, Solaris isn't open-source any more, so, unless support for the "any" device was in OpenSolaris or was independently added in Illumos, it'll take some looking at Oracle documentation or, if the mechanism used for the "any" device isn't documented, reverse-engineering to implement it in tcpdump.org libpcap. (And if the changes are under the CDDL, that has a patent clause, so I'd be loath to pick up that code.)

Sorry, I am using a civil nick l1gi, but my name is Martin Rehak and I am part of the team who maintains tcpdump and libpcap packages in Solaris in Oracle.

Recent Solaris delivers libpcap and tcpdump is linked against it. libpcap includes the patch mentioned above which I have applied on libpcap in Solaris.
```
root@ST146:~# uname -a
SunOS ST146 5.11 11.4.60.146.0 i86pc i386 i86pc virtualbox
root@ST146:~# ldd /usr/bin/tcpdump
        libpcap.so.1 =>  /usr/lib/64/libpcap.so.1
        libc.so.1 =>     /lib/64/libc.so.1
        libibverbs.so.1 =>       /usr/lib/64/libibverbs.so.1
        libkstat.so.1 =>         /lib/64/libkstat.so.1
root@ST146:~# tcpdump -D
1.net0 [Up, Running, Connection status unknown]
2.lo0 [Up, Running, Loopback]
3.any (Pseudo-device that captures on all interfaces) [Loopback, Connection status unknown]
root@ST146:~# tcpdump -i any -L
Data link types for any (use option -y to set):
  IPNET (Solaris ipnet)
```
Could you guide me, what could be the fix in this situation, please?

Thank you,
Martin Rehak aka l1gi

**Comment by guyharris** [comment]
> what could be the fix in this situation, please?

c6b4ee68786c76d47327944e9f3be779bcfe4c6e is the fix.

**Comment by guyharris** [comment]
>  libpcap includes the patch mentioned above which I have applied on libpcap in Solaris.

So which Solaris version added the "any" device?

**Comment by guyharris** [comment]
> Applying this patch, updating add_dev to pcap_add_dev on "SunOS unstable11x 5.11 11.3 i386" or "Oracle Corporation SunOS 5.11 11.3 June 2018" (sparc) allows tcpdump -D to show the any interface.

So that 11.3 version has the "any" device?  Note that the patch will show the "any" device on, for example, "Oracle Corporation SunOS 5.11 11.3 September 2015", but if you try to *capture* on it, you get a "No such process" error (because BPF apparently returns `ESRCH` rather than `ENXIO` if you try to bind to an interface that doesn't exist).

Can you capture on the "any" device on that version of 11.3?

**Comment by fxlb** [comment]
> Can you capture on the "any" device on that version of 11.3?

I don't have root access on OpenCSW Buildfarm machines, so I can't test.

**Comment by l1gi** [comment]
> So which Solaris version added the "any" device?

One of our customers asked for this functionality to help them investigate traffic on systems with multiple network devices. They referred to Linux where _any_ already existed. It was implemented in 2016 and appear firstly in Solaris 11.3.11.6.0.
```
root@S11-3-SRU:~# tcpdump -i any
dropped privs to nobody                                                                               
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode                            
listening on any, link-type IPNET (Solaris ipnet), capture size 262144 bytes
```

**Comment by l1gi** [comment]
> > what could be the fix in this situation, please?
> 
> [c6b4ee6](https://github.com/the-tcpdump-group/tcpdump/commit/c6b4ee68786c76d47327944e9f3be779bcfe4c6e) is the fix.

I will test this and let you know if that worked.

Thank you very much for your time,
m.

**Comment by guyharris** [comment]
> t was implemented in 2016 and appeared firstly in Solaris 11.3.11.6.0.

Is there a mechanism that does *not* require root privileges to determine whether the OS on which you're running supports the "any" device?

**Comment by l1gi** [comment]
The fix works fine, thanks again.

> Is there a mechanism that does _not_ require root privileges to determine whether the OS on which you're running supports the "any" device?

Why are you asking? Isn't the mechanism you have come with good enough? All versions which does not support that are already EOLed so you can expect it will work.

Does that make sense to ask you to integrate even this?
https://github.com/oracle/solaris-userland/blob/master/components/libpcap/patches/pcap-bpf.c.patch

**Comment by guyharris** [comment]
> Why are you asking?

Because I want libpcap to list the "any" device only when running on a version of Solaris that supports it, regardless of whether the program using libpcap is run as root or not.

> Isn't the mechanism you have come with good enough?

No, because it tests the OS version with uname and looks for 11.4 or later, but some 11.3 releases support it as well.

> All versions which does not support that are already EOLed so you can expect it will work.

So "EOLed" means either "nobody out there is running it" or "nobody out there who happens to be running it will want to build a newer version of libpcap and link programs with it"?

**Comment by infrastation** [comment]
`uname -v` prints the 5-number version in Oracle Solaris, which is supposedly the contents of `utsname.version`, maybe that could be used as a portable run-time check.

**Comment by l1gi** [comment]
Hi,

It is not necessary to do a runtime check, buildtime is enough as far as I understand. I would like to dissuade you from using Solaris version scheme. It always been a mess. I was trying for a while to create a test program, but as ipnet.h is a kernel buildtime header it is not easy to fulfill its dependencies. A very trivial and reliable test to find out whether _any_ is supported is just a

`grep IPNET_ANY_LINK /usr/include/inet/ipnet.h`

Is it acceptable?

Thanks,
m.

**Comment by l1gi** [comment]
Any news on this, please?

Thank you,
m.

**Comment by guyharris** [comment]
> Is it acceptable?

Yes.  See the-tcpdump-group/libpcap@841507c824c1e3adffca4ec8b3d986fbc1244ba1.

**Comment by l1gi** [comment]
Guy, thank you again for your time. Works perfectly.

Regards,
m.
