### ISSUE TITLE
tcpdump flat doesn't work in user namespace + network namespace context

### ISSUE THREAD

**Issue by majek** [the-tcpdump-group/tcpdump#1062]
It's great that tcpdump tries to drop root priviledges by default nowadays, but this means it doesn't work in user namespace + net namespace context:

```
$ unshare -rn bash -c "ip l set lo up; tcpdump -ni lo -Zroot"
tcpdump: Couldn't change to 'root' uid=0 gid=0: Operation not permitted

$ unshare -rn bash -c "ip l set lo up; tcpdump -ni lo"
tcpdump: Couldn't change to 'tcpdump' uid=108 gid=115: Operation not permitted
```

An insane solution is to run it under strace fault injection to mask the setgroups syscall error
```
strace -e trace=setgroups -o /dev/null -e inject=setgroups:retval=0 tcpdump -ln -i lo -Zroot
```

But this is just grotesque.

----

Explanation: in linux you can spoof userid with a featuer called user namespace. Under user namespace process can see that uid==0. While it looks like root, it's not root. It's root within the context of user namespace. If net namespace is added at the same time user looks like root and has full permissions to network. However it can't arbitrarly setgroup/setuid. So tcpdump, while has sufficient permissions for net, doesn't have a permission to change uid. 

---
tcpdump version 4.99.1
libpcap version 1.10.1 (with TPACKET_V3)
OpenSSL 3.0.2 15 Mar 2022

**Comment by fenner** [comment]
Does https://github.com/the-tcpdump-group/tcpdump/pull/812 fix this problem for you?
