### ISSUE TITLE
The tcpdump man page appears not to document one of the TCP flags

### ISSUE THREAD

**Issue by YangQing1989** [the-tcpdump-group/tcpdump#1069]
https://www.tcpdump.org/manpages/tcpdump.1.html

```
|  HL   | rsvd  |C|E|U|A|P|R|S|F|        window size            |
```
I think there is a missing TCP flag：**Accurate ECN**

**Comment by infrastation** [comment]
Thank you for bringing this up, let's treat this as a duplicate of #999.

**Comment by guyharris** [comment]
Duplicate of #999
