### ISSUE TITLE
How can grep the result in tcpdump with --version or -L(data-link-types)

### ISSUE THREAD

**Issue by MinpuKang** [the-tcpdump-group/tcpdump#1095]
Hello Expert

With a script for tcpdump and need to check the libpcap version or list data-link-types like "tcpdump --version | grep -i libpcap", but it cannot printout the correct grep result and always printout all result for --version.

May I know how can use grep to get the match result?

Thank you
BRs/Minpu

**Comment by guyharris** [comment]
`tcpdump --version 2>&1 | grep -i libpcap`

Some older versions of tcpdump may have printed the version information or the `-L` information to the standard error, so just force the standard error of the process to go to the standard output before piping the standard output to grep.

(The tcpdump that comes with macOS Ventura, and the version from the main branch, send version information to the standard output.  However, the macOS Ventura tcpdump sends `-L` information to the standard error, although the main branch version sends it to the standard output.)
