### ISSUE TITLE
Missing support for L2TPv3

### ISSUE THREAD

**Issue by Zstorm999** [the-tcpdump-group/tcpdump#1120]
**tcpdump version:** 4.99.4
**libpcap version:** 1.10.4

There is currently no support for the L2TPv3 protocol in tcpdump. Attempts to capture packets result in the following error:
`Unknown Version, neither L2F(1) nor L2TP(2)`.

This seems to be mostly a display issue: packets are correctly captured (and identified as an unknown l2tp version), and when storing the capture as pcap it is identified correctly by other software such as wireshark.

Reference for the protocol: https://www.rfc-editor.org/rfc/rfc3931

**Comment by infrastation** [comment]
Adding such support would need some good example packet captures and a volunteer to add the missing code and to turn the packet captures into additional tests.

**Comment by Zstorm999** [comment]
I have an example packet capture here : 
[l2tpv3.zip](https://github.com/the-tcpdump-group/tcpdump/files/13977862/l2tpv3.zip)

I will try to make a pull request with an implementation in the next week.

**Comment by infrastation** [comment]
Thank you. Please see the `CONTRIBUTING.md` file for a multitude of starting points.

**Comment by infrastation** [comment]
Did not happen, closing.
