### ISSUE TITLE
MPLS over 802.1Q Ethernet parsing

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/tcpdump#115]
Converted from [SourceForge issue 2796822](http://sourceforge.net/support/tracker.php?aid=2796822), submitted by ericaustin

We run MPLS over an 802.1q tagged Ethernet link (2 labels deep on the MPLS).  It looks like tcpdump fails to parse the packets properly in this scenario.  Just MPLS seems to work and just 802.1q tagged seems to work but the combination of the two kills it.  Coincidentally, Snort seems to have the same issue but Wireshark parses it fine.

**Comment by infrastation** [comment]
For posterity, there is now a [FAQ entry](https://www.tcpdump.org/faq.html#q13) about this.
