### ISSUE TITLE
Please help me: On Linux, whether tcpdump can continue work 7*24。

### ISSUE THREAD

**Issue by Gi20095044** [the-tcpdump-group/tcpdump#1191]
I am using tcpdump on Linux version openEuler 22.03(lts-sp3),
tcpdump version 4.99.3
libpcap version 1.10.3

When i try to run this command:
nohup tcpdump -i enp4s0 tcp  -C 100 -w /capture/file.pcap &

Wether tcpdump can keep working for one week(7*24).
Wether the command may causes the system to crash .

Please help me.

**Comment by guyharris** [comment]
> Wether tcpdump can keep working for one week(7*24).

It should be able to, as you're just writing to capture files, so it won't build up any internal state, and thus shouldn't run out of address space.

> Wether the command may causes the system to crash .

Unless there's a kernel bug, it shouldn't cause the system to crash.

**Comment by Gi20095044** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Gi20095044** [comment]
Thank you very much. I will try.



---Original---
From: "Guy ***@***.***&gt;
Date: Tue, Jun 25, 2024 10:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [the-tcpdump-group/tcpdump] Please help me: On Linux, whether tcpdump can continue work 7*24。 (Issue #1191)




  
Wether tcpdump can keep working for one week(7*24).
  
It should be able to, as you're just writing to capture files, so it won't build up any internal state, and thus shouldn't run out of address space.
  
Wether the command may causes the system to crash .
  
Unless there's a kernel bug, it shouldn't cause the system to crash.
