### ISSUE TITLE
Potential memory leak in tcpdump.c

### ISSUE THREAD

**Issue by icy17** [the-tcpdump-group/tcpdump#1208]
Calling [pcap_findalldevs](https://github.com/the-tcpdump-group/tcpdump/blob/master/tcpdump.c#L1165C11-L1165C27) in tcpdump.c line: 1165 without releasing the devlist cause memleak (in 1175).

Although the program will exit, I think it is better to add a free here.

![image](https://github.com/user-attachments/assets/e895946d-d6c9-4e4d-bd57-e62aa211a94c)

**Comment by RoseSecurity** [comment]
Just opened [this PR](https://github.com/the-tcpdump-group/tcpdump/pull/1211) to address this!

**Comment by guyharris** [comment]
Fixed in the main branch in 11e8f0a2ecaf6e391ab412b1b23ece0ddac2dd0c and in the 4.99 branch 830c52e09f41ac82a25a201bf1fd042395f6c8b4.  I also improved the error message while I was at it.
