### ISSUE TITLE
OLSR and Nameservice Plugin

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/tcpdump#134]
Converted from [SourceForge issue 3287379](http://sourceforge.net/support/tracker.php?aid=3287379), submitted by benbe

When parsing OLSR Trafic (IPv4) which contains messages from the Nameservice plugin the dissector seems to assume IPv4 adresses, although the plugin itself writes IPv6-length addresses. Cf. the headers at 
http://hg.ninux.org/olsrd-ninux-messy/browser/lib/nameservice/src/nameservice_msg.h?rev=1965%3Ab2a7a33ffa5e3044eccdbd370bc4a3c668d76b09

Due to this bug the parsing is off and reports wrong results:

19:08:10.907461 IP (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 244)
    10.11.10.15.698 > 255.255.255.255.698: [udp sum ok] OLSRv4, seq 0xe9b4, length 216
        MID Message (0x03), originator 10.11.0.14, ttl 254, hop 1
          vtime 288.000s, msg-seq 0x392c, length 16
          interface address 10.11.4.33
        TC-LQ Message (0xca), originator 10.11.0.8, ttl 1, hop 1
          vtime 496.000s, msg-seq 0xaa2e, length 64
            advertised neighbor seq 0x0032
              neighbor 10.11.10.10, link-quality 100.00%, neighbor-link-quality 100.00%
              neighbor 10.11.0.12, link-quality 78.82%, neighbor-link-quality 84.31%
              neighbor 10.11.0.13, link-quality 92.55%, neighbor-link-quality 100.00%
              neighbor 10.11.10.14, link-quality 100.00%, neighbor-link-quality 49.80%
              neighbor 10.11.0.15, link-quality 100.00%, neighbor-link-quality 100.00%
              neighbor 10.11.63.26, link-quality 100.00%, neighbor-link-quality 100.00%
        TC-LQ Message (0xca), originator 10.11.0.10, ttl 6, hop 2
          vtime 200.000s, msg-seq 0x01dd, length 32
            advertised neighbor seq 0x146a
              neighbor 10.11.0.14, link-quality 55.69%, neighbor-link-quality 45.88%
              neighbor 10.11.0.9, link-quality 98.82%, neighbor-link-quality 71.37%
        Nameservice Message (0x82), originator 10.11.0.10, ttl 253, hop 2
          vtime 1792.000s, msg-seq 0x01df, length 100
          Version 1, Entries 2
            #0: type 000000, length 7, address 10.11.0.10, name "^@^@^@^@^@^@^@"
            #1: type 000000, length 0 (invalid)
        0x0000:  ffff ffff ffff 129c e121 c98e 0800 4510  .........!....E.
        0x0010:  00f4 0000 4000 4011 25d0 0a0b 0a0f ffff  ....@.@.%.......
        0x0020:  ffff 02ba 02ba 00e0 d0a2 00d8 e9b4 032c  ...............,
        0x0030:  0010 0a0b 000e fe01 392c 0a0b 0421 cafc  ........9,...!..
        0x0040:  0040 0a0b 0008 0101 aa2e 0032 ffff 0a0b  .@.........2....
        0x0050:  0a0a ffff 0000 0a0b 000c c9d7 0000 0a0b  ................
        0x0060:  000d ecff 0000 0a0b 0a0e ff7f 0000 0a0b  ................
        0x0070:  000f ffff 0000 0a0b 3f1a ffff 0000 ca9b  ........?.......
        0x0080:  0020 0a0b 000a 0602 01dd 146a 0000 0a0b  ...........j....
        0x0090:  000e 8e75 0000 0a0b 0009 fcb6 0000 82ce  ...u............
        0x00a0:  0064 0a0b 000a fd02 01df 0001 0002 0000  .d..............
        0x00b0:  0007 0a0b 000a 0000 0000 0000 0000 0000  ................
        0x00c0:  0000 7468 656f 2d61 7000 0003 0015 0a0b  ..theo-ap.......
        0x00d0:  0009 0100 4100 0101 0000 0001 0000 3438  ....A.........48
        0x00e0:  2e33 3230 3039 392c 3130 2e39 3031 3730  .320099,10.90170
        0x00f0:  302c 3000 0000 0000 0000 0000 0000 0000  0,0.............
        0x0100:  0000                                     ..

Where the correct Nameservice entries would be:
        Nameservice Message (0x82), originator 10.11.0.10, ttl 253, hop 2
          vtime 1792.000s, msg-seq 0x01df, length 100
          Version 1, Entries 2
            #0: type 0000, length 0007, address 10.11.0.10, name "theo-ap"
            #1: type 0003, length 0015, address 10.11.0.9, name "48.320099,10.901700,0"

If necessary I can extract some of the packets from the dump for you to reproduce.

**Comment by infrastation** [comment]
The original SF bug was opened on 2011-04-15. Commit 289e0ae on 2009-05-17 added some IPv6 support to the OLSR decoder, including the `OLSR_NAMESERVICE_MSG` case. Supposedly, that didn't work entirely well. However, the only samples of OLSR nameservice plugin packets exist in an OOBR test, so cannot be taken as reference. Given the amount of available input, without a subject matter expert it is impracticable to state the problem (if any) exactly, so I am closing this request after 10 years.
