### ISSUE TITLE
[Patch] Makes tcpdump flush its dump on SIGUSR1

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/tcpdump#181]
Converted from [SourceForge issue 740372](http://sourceforge.net/support/tracker.php?aid=740372), submitted by nobody

Sometimes you want to peak at a dump in progress, while
it is written to disk. tcpdump/libpcap uses stdio to
write to the dump file, which may mean that it can take
a while for a packet to hit the disk.

Attached patch makes tcpdump flush the output file on
reception of SIGUSR1. No changes to libpcap are needed
to make this happen.

Submitted by bert hubert ahu@ds9a.nl

**Comment by tomato42** [comment]
Note that lack of this functionality may be possible to workaround using the `-U` option

**Comment by infrastation** [comment]
This behaviour had been implemented in 2018 in a slightly different way: see pull request #670, commits 0e79762 and ee29ee4. Closing.
