### ISSUE TITLE
[Feature] Add capability to print interface name

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/tcpdump#296]
Converted from [SourceForge issue 2223028](http://sourceforge.net/support/tracker.php?aid=2223028), submitted by inigo78

Just a switch to print the interface name with each packet.

When using "-i any" it could be very useful.

See at r1.22 in:

 http://www.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/tcpdump/util.c

Ther is just two lines of code.

A lot of tanks.

**Comment by amosshapira** [comment]
+1 for this feature. I see that last change was over 18 months ago. Is there any ETA? Thanks.

**Comment by mcr** [comment]
Amos Shapira <notifications@github.com> wrote:
    > +1 for this feature. I see that last change was over 18 months ago. Is there
    > any ETA? Thanks.

Send patch...

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by leonerd** [comment]
The `LINUX_SLL2` header format includes the interface index; that can be used to provide this feature

http://comments.gmane.org/gmane.network.tcpdump.devel/6991

**Comment by guyharris** [comment]
> The LINUX_SLL2 header format includes the interface index; that can be used to provide this feature

...but only if you are printing the interface name while doing a live capture, or are running tcpdump on a saved capture taken on the machine on which you're running tcpdump at a time when it has the same network configuration as it did when the capture was done, or running it on a machine with the same network configuration and interface names.

pcapng fixes this problem by providing Interface Description Blocks that include the interface name.

**Comment by leonerd** [comment]
Sure - both features work well together. The SLL2 header per packet tells you which interface it came in on, and every time you mention a new interface index, provide an IDB to map that index onto its name.

**Comment by guyharris** [comment]
> Sure - both features work well together. The SLL2 header per packet tells you which interface it came in on, and every time you mention a new interface index, provide an IDB to map that index onto its name.

All pcapng packet blocks either 1) *already have an interface ID field that refers to an IDB* or 2) is a Simple Packet Block that implicitly has an interface ID of 0; the extra interface ID field in the SLL2 header wouldn't be used to look up IDBs.

**Comment by zyf0330** [comment]
Hello, I want to know when v4.10.0 releases?
