### ISSUE TITLE
build problem when building to non /usr/local locations

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/tcpdump#30]
Converted from [SourceForge issue 752276](http://sourceforge.net/support/tracker.php?aid=752276), submitted by nobody

Howdy,

I had to manually edit your Makefile when I tried to
build tcpdump-3.7.2 because the prefix value is not
used to search for libraries or include files by adding
-I and -L values. The build succeeded after my change.

Regards,

George...

**Comment by fxlb** [comment]
Should we close this issue ?
Version 3.7.2 is rather old (2003).

**Comment by guyharris** [comment]
It still seems to work that way - I built with `--prefix=/tmp/install` and it neither used `-I /tmp/install/include` nor `-L /tmp/install/lib`.

**Comment by guyharris** [comment]
For what it's worth, the [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html) say, in the [Variables for Installation Directories](https://www.gnu.org/prep/standards/standards.html#Directory-Variables) section:

> Running ‘`make install`’ with a different value of `prefix` from the one used to build the program should *not* recompile the program.

If the intent is that `prefix` controls the location in which to search for header files and libraries, that seems to me to be inconsistent with "changing `prefix` shouldn't cause the program to be recompiled".

In addition, in [the "Optional Features" section of the autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf.html#Optional-Features), it says

> For packages that use the X Window System, configure can usually find the X include and library files automatically, but if it doesn't, you can use the `configure` options `--x-includes=`*dir* and `--x-libraries=`*dir* to specify their locations.

which also suggests that --prefix= may not be the way to say where to search for headers and libraries.

And if a particular package required by a program is installed in an unusual place - a place *other* than where the program *itself* should be installed - having `--prefix` affect where the script and the build process search for header files and libraries won't help.

So I'm not sure that changing the script so that `--prefix` affects where to search for libraries and headers is the right thing to do.  Setting `CFLAGS` and `LDFLAGS` environment variables, with `CFLAGS` having a `-I` flag and `LDFLAGS` having a `-L` flag, when running the configure script will cause header files and libraries to be searched for in the specified directories.

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > So I'm not sure that changing the script so that --prefix affects where
    > to search for libraries and headers is the right thing to do. Setting
    > CFLAGS and LDFLAGS environment variables, with CFLAGS having a -I flag
    > and LDFLAGS having a -L flag, when running the configure script will
    > cause header files and libraries to be searched for in the specified
    > directories.

I concur.

It's very annoying if "sudo make install" causes a recompile.  I rather think
it should just fail.  So I don't want any recompiles there.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by fxlb** [comment]
> So I'm not sure that changing the script so that --prefix affects where to search for libraries and headers is the right thing to do. Setting CFLAGS and LDFLAGS environment variables, with CFLAGS having a -I flag and LDFLAGS having a -L flag, when running the configure script will cause header files and libraries to be searched for in the specified directories.

Totally agree.

**Comment by guyharris** [comment]
Close it, then?

**Comment by fxlb** [comment]
Yes, done.
