### ISSUE TITLE
tcpdump displays a dot('.') for an Ack flag.

### ISSUE THREAD

**Issue by pjps** [the-tcpdump-group/tcpdump#319]
Hi,

Yesterday while looking through a packet dump, we realised that while showing TCP hand shake, tcpdump(8) displays a dot('.') for an Acknowledgement flag. The tcpdump(8) manual explains this under the - TCP Packet - section as

...
&nbsp;The general format of a tcp protocol line is:
&nbsp;&nbsp;&nbsp;&nbsp;              src > dst: flags data-seqno ack window urgent options
&nbsp;&nbsp;&nbsp;&nbsp;       Src and dst are the source and  destination  IP  addresses  and  ports.
&nbsp;&nbsp;&nbsp;&nbsp;       Flags  are  some  combination of S (SYN), F (FIN), P (PUSH), R (RST), U
&nbsp;&nbsp;&nbsp;&nbsp;       (URG), W (ECN CWR), E (ECN-Echo) or '.' (ACK), or `none'  if  no  flags
&nbsp;&nbsp;&nbsp;&nbsp;       are set. 

Why not display letter 'A' for acknowledgement flag? How does this dot('.') help??
Please consider the letter 'A' in place of a dot('.') for acknowledgement flag, it will be much more intuitive and helpful.

Thank you.

**Comment by jeffrey-e** [comment]
> The reason for not doing this is explained in http://article.gmane.org/gmane.network.tcpdump.devel/6383
> This tracker is purposed for bugs, please consider using the tcpdump-workers mailing list for future discussions. Closing.

This link is broken

**Comment by fxlb** [comment]
You can find a copy here:
https://seclists.org/tcpdump/2013/q2/127
(or on archive.org)
