### ISSUE TITLE
Problem using many IP's in not host clause

### ISSUE THREAD

**Issue by docsnoop** [the-tcpdump-group/tcpdump#357]
Hi There,

I have currently a big problem. I have defined a huge rule like the following "and not (host 1.1.1.1 or host 2.2.2.2 or host 3.3.3.3,...). In total I have a list of ~ 300 hosts for which I will not protocol any data.
So far the command is parsed correctly and tcpdump is running. but even if I connect from e.g. 1.1.1.1 a packet is snipped.
Are there any maximums for number of named hosts?
Any ideas / proposals?

Thanks.
Regards,
Andy

**Comment by mcr** [comment]
Please re-open with details.
