### ISSUE TITLE
 print names: spaces problem, normalization ?

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#410]
Hi,

1) Some printers prints spaces in names (field/option/attribute) : It makes difficult to parse the output.

2) Some printers don't use the name defined in the corresponding RFC : It makes difficult to "git grep" the code to search if an option/attribute is supported or not.

The solution to these two problems goes in the same direction because a RFC name (if available) is defined with hyphens and not spaces. (Ok, there are maybe exceptions and some protocols are not defined by a RFC).

Example with Radius protocol:

in tests/radius-rfc5176-v.out, we see:
```
IP (tos 0x0, ttl 64, id 21127, offset 0, flags [none], proto UDP (17), length 110)
127.0.0.1.46281 > 127.0.0.1.1812: RADIUS, length: 82
  Access Request (1), id: 0xb5, Authenticator: 11851d8b1b48  <- Access Request: 2 words
  Username Attribute (1), length: 14, Value: bob-untagged    <- Username: 1 word
  Password Attribute (2), length: 18, Value:                <- Password: 1 word
  NAS IP Address Attribute (4), length: 6, Value: 127.0.0.1 <- NAS IP Address: 3 words
  NAS Port Attribute (5), length: 6, Value: 1              <- NAS Port: 2 words
  Message Authentication Attribute (80), length: 18, Value: <- Message Authentication: 2 wds
```
For a better parsing of the output and greping of the code, I propose to use only RFC/standard names (if availables). Otherwise I propose to just replace spaces by hyphens.

for example:
"Username" would be "User-Name"
"Password" would be "User-Password"
"NAS IP Address" would be "NAS-IP-Address"
"NAS Port" would be "NAS-Port"
"Message Authentication" would be "Message-Authenticator"
(RFC2865, RFC2869)
Etc.

After "normalization":
```
IP (tos 0x0, ttl 64, id 21127, offset 0, flags [none], proto UDP (17), length 110)
127.0.0.1.46281 > 127.0.0.1.1812: RADIUS, length: 82
  Access-Request (1), id: 0xb5, Authenticator: 11851d8b1b48  <- Access-Request: 1 word
  User-Name Attribute (1), length: 14, Value: bob-untagged  <- User-Name: 1 word
  User-Password Attribute (2), length: 18, Value:          <- User-Password: 1 word
  NAS-IP-Address Attribute (4), length: 6, Value: 127.0.0.1 <- NAS-IP-Address: 1 word
  NAS-Port Attribute (5), length: 6, Value: 1              <- NAS-Port: 1 word
  Message-Authenticator Attribute (80), length: 18, Value:  <- Message-Authenticator: 1 word
```

Thought?

**Comment by infrastation** [comment]
Does this issue still need to remain open?

**Comment by fxlb** [comment]
I have no time now for more normalizations. Closing.
