### ISSUE TITLE
rpl_format_dagid() problem

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/tcpdump#418]
I've sort of managed to run the tests (using StrawBerry Perl and a MSVC built Windump). But I see a problem with `sh TESTonce dio02/dio03` and `rpl_format_dagid()`:

```	
static void
rpl_format_dagid(char dagid_str[65], const u_char *dagid)
{
        char *d = dagid_str;
        int  i;

        for(i=0;i<16;i++) {
                if(isprint(dagid[i])) {
                        *d++ = dagid[i];
                } else {
                        snprintf(d,4,"0x%02x", dagid[i]);
                        d += 4;
                }
        }
        *d++ = '\0';
}
```

In `tests\rpl-19-pickdag.out`, the expected 'dagid' should be:
```
... [dagid:T10x0,seq:10 ....
```
How can `dagid` become `T10x0` when told to loop over 16 characters?

My MSVC compiled Windump IMHO correctly spits out:
```
IP6 (hlim 64, next-header ICMPv6 (58) payload length: 56) fe80::216:3eff:fe11:3424 > fe80::216:3eff:fe11:3424: [icmp6 sum ok] ICMP6, RPL, (CLR)Destination Advertisement Object [dagid:T10x000x000x000x000x000x000x000x000x000x000x000x000x000x00,seq:10,instance:42,Dagid,40] opt:rpltarget len:25  opt:pad0 opt:pad0 opt:pad0 opt:pad0 opt:pad0 opt:pad0 opt:pad0
```

**Comment by gvanem** [comment]
The `dao01` test is affected too (since print-icmp6.c) is involved.

**Comment by infrastation** [comment]
It happens because `rpl_format_dagid()` does not account for the null char in the `snprintf()` call. May be on Windows `snprintf()` does not account for the null char and it works as is. The following change makes it work on Linux as originally intended:
```patch
--- a/print-icmp6.c
+++ b/print-icmp6.c
@@ -660,7 +660,7 @@ rpl_format_dagid(char dagid_str[65], const u_char *dagid)
                 if(isprint(dagid[i])) {
                         *d++ = dagid[i];
                 } else {
-                        snprintf(d,4,"0x%02x", dagid[i]);
+                        snprintf(d,5,"0x%02x", dagid[i]); /* 4 + null char */
                         d += 4;
                 }
         }
```
I can fix it this way but perhaps it would be better to reuse the existing `fn_printzp()` function for this purpose.

**Comment by infrastation** [comment]
Could you check it is OK now?

**Comment by gvanem** [comment]
Works fine now. Except for lmp-v:
```
Failed test: lmp-v

96c96
<             Min Reservable Bandwidth: 9877.895 Mbps
---
>             Min Reservable Bandwidth: 9877.894 Mbps
```

which is a bit silly IMHO.

**Comment by infrastation** [comment]
This is a case of of bug #333, which should not occur any more but... Could you check why `tests/lmp-v.sh` is not skipping the test as it should for a non-GCC build?

**Comment by gvanem** [comment]
I have no idea really; maybe since I don't have a Makefile, the `grep ` is probably causing this.
(I use a home-brew GNU makefile called Makefile.Windows targeting MSVC and MingW). So maybe it should test for `../Makefile` first?

**Comment by infrastation** [comment]
Does it work now?

**Comment by gvanem** [comment]
Yes. Fine:
```
lmp-v                         : TEST SKIPPED (no Makefile)
...
```

But there is 1 more problem with my MSys `diff` and space-diffs (i.e. line-endings). So adding the `-b` option, all other tests now report `passed`. I know space-diffs are important in `./tests`. But AFAICS, `diff` has no `--ignore-line-ending` option. An alternative would be to run `unix2dos --keepdate *.out` first. But I've patched `TESTonce` like so:
```
--- Git-Latest/tests/TESTonce 2014-11-25 13:36:58 +0000
+++ tests/TESTonce	2015-01-02 21:14:18 +0000
@@ -13,8 +13,8 @@
 $options=$ARGV[3];

 if ($^O eq 'MSWin32') {
-  $r = system "..\\windump -n -r $input $options 2>NUL | tee NEW/$output | diff $output - >DIFF/$output.diff";
- }
+  $r = system "..\\windump -n -r $input $options 2>NUL | tee NEW/$output | diff -b $output - >DIFF/$output.diff";
+}
 else {
   $r = system "../tcpdump 2>/dev/null -n -r $input $options | tee NEW/$output | diff $output - >DIFF/$output.diff";
 }
```

**Comment by infrastation** [comment]
Do I get it right that tcpdump output has DOS newlines on Windows and the `.out` files remain with UNIX newlines?

**Comment by fxlb** [comment]
Perhaps something like `..\\windump [...] | dos2unix | tee [...]` will work ?

**Comment by fxlb** [comment]
I think that if `core.autocrlf=false` is set in git config, the tests/*.out files keep their Unix newlines when pulled in Windows.

**Comment by gvanem** [comment]
@infrastation 

Seem so yes.

**Comment by infrastation** [comment]
I was going to suggest the same as @fxlb just did.

**Comment by mcr** [comment]
The snprintf(..4) my fault. Sorry. Omitting trailing \0 *looked* more correct to my eyes.
I'll probably want to fix it to do that explicitely.

**Comment by infrastation** [comment]
The original bug has already been fixed. As for the newlines issue, it would be wrong to ignore all changes in whitespace amount in all builds through `diff -b` as it makes in the way of seeing other bugs as they appear. The newline style conversion/preservation should be a Windows-specific part of the test. @gvanem, would you like to provide a patch for this?

**Comment by gvanem** [comment]
Okay, here is something that works here:
```
diff --git a/tests/TESTonce b/tests/TESTonce
index 7e55d24..540f792 100755
--- a/tests/TESTonce
+++ b/tests/TESTonce
@@ -13,8 +13,14 @@ $output=$ARGV[2];
 $options=$ARGV[3];

 if ($^O eq 'MSWin32') {
+  #
+  # Windump always have DOS line-endings. The *.out files may not have.
+  # And since diff have no option to ignore changes in line-endings,
+  # convert the *.out file to Unix style first.
+  #
+  system "unix2dos --keepdate --quiet $output";
   $r = system "..\\windump -n -r $input $options 2>NUL | tee NEW/$output | diff $output - >DIFF/$output.diff";
- }
+}
 else {
   $r = system "../tcpdump 2>/dev/null -n -r $input $options | tee NEW/$output | diff $output - >DIFF/$output.diff";
 }
```

This just *ass-u-me*s user has the `unix2dos` program. It could probably been done in Perl.

**Comment by infrastation** [comment]
On Internet it is suggested that `s/\012/\015\012/g` should do the conversion.

**Comment by infrastation** [comment]
`unix2dos` should be fine too, let me know what you prefer.

**Comment by gvanem** [comment]
Denis Ovsienko wrote:
> |unix2dos| should be fine too, let me know what you prefer.

unix2dos (until someone objects).

-- 
--gv

**Comment by fxlb** [comment]
I do not like very much the idea of changing files under git control.
It's why I expected that `..\\windump [...] | dos2unix | tee [...]` will work.
or perhaps `..\\windump [...] | sed 's/\r//' | tee [...]`
sed is already needed (for configure, etc.).
(sorry, I don't have a Windows setup to test ...)

**Comment by infrastation** [comment]
This also makes sense. @gvanem, could you tell if sed is available?

**Comment by gvanem** [comment]
@infrastation `sed 's/\r//'`

It must be `sed 's/\\r//'`. F*ck this shell-issues. I wish this was done in Python. Okay, this works:

```
--- Git-latest/tests/TESTonce   2015-01-06 14:42:25 +0000
+++ TESTonce    2015-01-08 23:19:18 +0000
@@ -13,8 +13,8 @@
 $options=$ARGV[3];

 if ($^O eq 'MSWin32') {
-  $r = system "..\\windump -n -r $input $options 2>NUL | tee NEW/$output | diff $output - >DIFF/$output.diff";
- }
+  $r = system "..\\windump -n -r $input $options 2>NUL | sed 's/\\r//' | tee NEW/$output | diff $output >DIFF/$output.diff";
+}
 else {
   $r = system "../tcpdump 2>/dev/null -n -r $input $options | tee NEW/$output | diff $output >DIFF/$output.diff";
 }
```

**Comment by infrastation** [comment]
Should the new call to diff be `diff $output -` too? It is missing the dash.

**Comment by infrastation** [comment]
Also the last (unchanged) call to diff is missing the dash on the diff above. Something must be wrong with copying the text around, I am committing this change with the dash.

**Comment by infrastation** [comment]
It was commit 6802dd6. Is this issue fully resolved?

**Comment by gvanem** [comment]
Yes.

**Comment by infrastation** [comment]
Thank you for the feedback.
