### ISSUE TITLE
ieee801.4.15 print crash

### ISSUE THREAD

**Issue by andrewreiter** [the-tcpdump-group/tcpdump#428]
Found a scenario that results in a crash that is unlikely to be reached in normal circumstances , but might as well share. I found it via fuzzing the pcap file read option. The packet being processed reaches the following display function (snipped):

```
u_int
ieee802_15_4_if_print(netdissect_options *ndo,
                      const struct pcap_pkthdr *h, const u_char *p)
{
        u_int caplen = h->caplen;
        int hdrlen;
        uint16_t fc;
 ...snip...
        fc = EXTRACT_LE_16BITS(p);
        hdrlen = extract_header_length(fc);
 ...snip...
        p += 3;
        caplen -= 3;
        if (!ndo->ndo_vflag) {
                p+= hdrlen;
                caplen -= hdrlen;
        } else {
  ... snip...
                caplen -= hdrlen;
        }
        if (!ndo->ndo_suppress_default_print)
                ND_DEFAULTPRINT(p, caplen);
```

In the case that I encounter, I have
u_int caplen = h->caplen = 4.
caplen -= 3;  (=> caplen = 1)

fc = EXTRACT_LE_16BITS(p);
int hdrlen = extract_header_length(fc)

121     p+= hdrlen;
(gdb) n
122     caplen -= hdrlen;
(gdb) p hdrlen
$34 = 20
(gdb) p caplen
$35 = 1
(gdb) p caplen
$36 = 4294967277

so, hdrlen vs caplen is the issue here. This is then passed to the ND_DEFAULTPRINT() macro which calls down to hex_and_ascii_print().. trusting the length (caplen) and just reading from memory ...

```
	0x43fb0:  0000 0000 0000 0000 0000 0000 0000 0000  ................

Program received signal SIGSEGV, Segmentation fault.
0x0000000000415262 in hex_and_ascii_print_with_offset (ndo=0x871d20 <Gndo>, ident=0x7ffffffa <error: Cannot access memory at address 0x7ffffffa>, 
    cp=0x7ffff7fd8001 <error: Cannot access memory at address 0x7ffff7fd8001>, length=5, oset=278480) at ./print-ascii.c:103
103			s2 = *cp++;
(gdb) 
```

Again, this is sort of a baked scenario because the pcap file is the source of the issue versus packet coming off the wire. But, I figured I would share anyway. 

The 11th packet in the trace  http://www.watson.org/~arr/ieee801415printcrash.pcap is the one of interest.

**Comment by fxlb** [comment]
Thanks, what is the output of `tcpdump --version`?
Do you get this crash with last code in master branches of libpcap/tcpdump?

**Comment by andrewreiter** [comment]
Indeed this is fixed with master. My apologies. I had thought I had the latest, but I was 2 minor revs off.
