### ISSUE TITLE
missing fragmented UDP packets

### ISSUE THREAD

**Issue by ayguen** [the-tcpdump-group/tcpdump#434]
"tcpdump -nn -i eth1 udp and port 40000 -w rec.pcap" misses fragmented packets shown with non-zero 'Fragment offset' in wireshark.

"tcpdump -nn -i eth1 udp -w rec.pcap" does catch all packets .. but of course, additional ones for other ports.

**Comment by guyharris** [comment]
The BPF filtering engine is stateless, so it cannot filter packets based on the contents of other packets.

A fragmented UDP packet will have the UDP header only in the first fragment, so only the first fragment could possibly match the filter "port 40000"; therefore, other packets will not match that filter, and:

1. as indicated above, if the first fragment matches, there's no way to get a BPF filter to match subsequent fragments based on that;

2. there isn't even a guarantee that the fragments will be transmitted in order - I think at least some versions of Linux transmit fragments in *reverse* order - so there might be fragments seen by the filter *before* the first fragment is seen, and to allow *those* packets to pass the filter would require either the ability to predict the future :-), or require that the filter mechanism do its own fragmentation and defer the delivery of non-first fragments.  The latter would be *quite* complicated, and would either cause packets to be delivered out of order to programs such as tcpdump or require that *other* packets being delayed.
