### ISSUE TITLE
pkg-config support

### ISSUE THREAD

**Issue by joeythesaint** [the-tcpdump-group/tcpdump#439]
pcap-config often returns host values when cross-compiling.  Rather than modify pcap-config with workarounds, it would be useful to provide pkg-config support in libpcap that can be used inside a sysroot.

**Comment by infrastation** [comment]
As far as I understand, pkg-config is not available in all platforms that support libpcap, hence pkg-config would not be able to completely replace pcap-config. What is the problem you are looking to solve in the first place?

**Comment by infrastation** [comment]
Closing due to lack of feedback.
