### ISSUE TITLE
Many warnings with ND_TTEST2 macro last update

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#443]
With the last change, we have more than 100 warnings on Travis.
See: https://travis-ci.org/the-tcpdump-group/tcpdump/builds/53903144
```patch
 #define ND_TTEST2(var, l) \
+  ((l) >= 0 && \
 	((uintptr_t)ndo->ndo_snapend - (l) <= (uintptr_t)ndo->ndo_snapend && \
-	    (uintptr_t)&(var) <= (uintptr_t)ndo->ndo_snapend - (l))
+         (uintptr_t)&(var) <= (uintptr_t)ndo->ndo_snapend - (l)))
```
I don't see now a straightforward fix.

**Comment by guyharris** [comment]
If we were to remove the "(l) >= 0" test *and* audit the code to make sure all length values are unsigned - which they probably should be anyway, as a negative length would be either a code error or, if the length is calculated from data in the packet, a packet error for which the printer should be checking before even checking the length - that should fix the warnings without restoring any vulnerabilities.

Unfortunately, we don't have any way to ensure that new signed lengths don't creep back in, however.

**Comment by mcr** [comment]
The (l)>=0 issue seemed to work for me... I'll need to read more about is
this a compile warning, or a test case warning. I can see that if l is
unsigned, that it can never be negative.

**Comment by guyharris** [comment]
It's a compile warning - the compiler warns about "if ({unsigned variable} >= 0" that "comparison of unsigned expression >= 0 is always true".

It Would Be Nice if there were either a way to tell the compiler "yes, I know, in *this particular case* I want you to silently optimize the test away" or "if somebody really is passing a signed value here I want you to fail", but I don't know of a way to do that, offhand.

**Comment by fxlb** [comment]
For the record the two (repeated) warnings are: `comparison of unsigned expression >= 0 is always true [-Wtype-limits]` and `comparison is always true due to limited range of data type [-Wtype-limits]`.

**Comment by guyharris** [comment]
With GCC 4.4 and later:

    https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Function-Specific-Option-Pragmas.html#Function-Specific-Option-Pragmas

and, I think, with all versions of clang, pragmas can be used to temporarily suppress some warnings (prior to that, there's no push/pop support), and with any compiler supporting those pragmas and C99's `_Pragma()`, there might be a way " to tell the compiler "yes, I know, in *this particular case* I want you to silently optimize the test away"", by incorporating into `_ND_TTEST2()` the appropriate _Pragma() calls to turn off those two warnings and to do pushes and pops of the warning state.

**Comment by infrastation** [comment]
Perhaps a straightforward way to tell the compiler that the test involves an unsigned length argument would be to use different macro, which doesn't test it for negative value? There could be two test: `ND_TTEST2U(...)` for unsigned and `ND_TTEST2S(...)` for signed. Or the most common case (unsigned in network protocols) could use the original name and the other case could use a new name.

**Comment by fxlb** [comment]
@guyharris I had a look at your idea, but because the `ND_TTEST2` is indirectly used in if(...), while(...), I don't see now how to do this.
@infrastation Thus, if `ND_TTEST2S`is used with an unsigned, we got a warning: good. If `ND_TTEST2U` is used with a signed, no warning and no test >= 0: less good.

Perhaps, we could,as Guy said, just remove the `>=0` test, make sure than, now, all the the codes use unsigned values, doing eventual updates, and put on our review list for new patches and printers:
1) Verify that arg to ND_CHECK*, ND_TTEST* are unsigned.

**Comment by mcr** [comment]
Denis Ovsienko <notifications@github.com> wrote:
    > Perhaps a straightforward way to tell the compiler that the test
    > involves an unsigned length argument would be to use different macro,
    > which doesn't test it for negative value? There could be two test:
    > ND_TTEST2U(...) for unsigned and ND_TTEST2S(...) for signed. Or the
    > most common case (unsigned in network protocols) could use the original
    > name and the other case could use a new name.

so when one writes, in C:

unsigned int foo = 8;   /* but usually it's ~100 */

ND_TEST2(thing, foo-9);

we get -1, even when both inputs are unsigned.
It's precisely these situations that we want to check, and we can not guess
ahead of time.  I guess we get the unsigned complaint whenever we pass
something that is constant and is known to be unsigned by the compiler,
I guess when we say "sizeof(foostruct)"

I'd rather throw a compiler directive at this if we can.

**Comment by guyharris** [comment]
In the example you give, foo is unsigned - and 9 is signed, as per "Semantics" in section 6.1.3.2 "Integer constants" in C90:

> The type of an integer constant is the first of the corresponding list in which its value can be represented. Unsuffixed decimal: ***`int`***, ***`long int`***, ***`unsigned long int`***; ...

So the "Usual arithmetic conversions", section 6.2.1.5 of C90, apply:

> Otherwise, the integral promotions are performed on both operands. Then the following rules are applied:

> If either operand has type ***`unsigned long int`***, the other operand is converted to ***`unsigned long int`***.
> Otherwise, if one operand has type ***`long int`*** and the other has type ***`unsigned int`***, if a ***`long int`*** can represent all values of an ***`unsigned int`***, the operand of type ***`unsigned int`*** is converted to ***`long int`***; if a ***`long int`*** cannot represent all the values of an ***`unsigned int`***, both operands are converted to ***`unsigned long int`***.
> Otherwise, if either operand has type ***`long int`***, the other operand is converted to ***`long int`***.
> Otherwise, if either operand has type ***`unsigned int`***, the other operand is converted to ***`unsigned int`***.
> Otherwise, both operands have type ***`int`***.

where the "integral promotions", from section 6.2.1.1 "Characters and integers" of C90, are:

> A ***`char`***, a ***`short int`***, or an ***`int`*** bit-field, or their signed or unsigned varieties, or an
enumeration type, may be used in an expression wherever an ***`int`*** or ***`unsigned int`*** may be
used. If an ***`int`*** can represent all values of the original type, the value is converted to an ***`int`***;
otherwise, it is converted to an ***`unsigned int`***. These are called the *integral promotions*. other arithmetic types are unchanged by the integral promotions.

The "integral promotions" don't apply, as we're not dealing with shorter-than-`int` values.  What *does* apply is "Otherwise, if either operand has type ***`unsigned int`***, the other operand is converted to ***`unsigned int`***, so 9 gets converted from `int` to `unsigned int`.

Section 6.1.2.5 "Types" of C90 says:

> A computation involving unsigned operands can never overflow, because a result that cannot be represented by the resulting unsigned integer type is reduced modulo the number that is one greater than the largest value that can be represented by the resulting unsigned integer type.

Presumably by "overflow ... reduced" they mean both "overflow ... reduced" and "underflow ... increased", so that a subtraction cannot underflow, so `foo-9` evaluates as 2^32-1 on an ILP32, LP64, or ILP64 platform.

If `foo` were `int`, however, the subtraction really *would* result in -1, and `ND_TTEST2()` would succeed.

**Comment by guyharris** [comment]
Were we to cast `l` to `size_t`, then:

* nothing would be done to the results of a `sizeof`;
* a value of type `unsigned int` would be unchanged on an ILP32 platform, zero-extended to `unsigned long` on an LP64 platform, and zero-extended to `unsigned long long` on an LLP64 platform;
* a value of type `int` would be converted to `unsigned int` on an ILP32 platform, `unsigned long` on an LP64 platform, and to `unsigned long long` on an LLP64 platform.

Section 6.2.1.2 "Signed and unsigned integers" says:

> When a value with integral type is converted to another integral type, if the value can be represented by the new type, its value is unchanged.
> When a signed integer is converted to an unsigned integer with equal or greater size, if the value of the signed integer is nonnegative, its value is unchanged. Otherwise: if the unsigned integer has greater size, the signed integer is first promoted to the signed integer corresponding to the unsigned integer; the value is converted to unsigned by adding to it one greater than the largest number that can be represented in the unsigned integer type.

so a negative `int` value would get 2^32 added to it in on ILP32 platform and 2^64 added to it on an LP64 or LLP64 platform

So if we have `ND_TTEST2()` cast `l` to `size_t` everywhere and check whether '(size_t)(l) <= 2147483647`, that should ensure that no negative values sneak through *and* not cause warnings.

**Comment by guyharris** [comment]
Yeah, but it still doesn't suppress warnings - if, for example, `l` is of type `uint8_t`, then the compiler will warn that, when cast to `size_t`, `l` can never be >= 2147483647.

**Comment by fxlb** [comment]
To avoid  tautological messages, this should work:
```
#define ISPOS(x) (((x) > 0) || ((x) == 0))
#define ND_TTEST2(var, l) \
  (ISPOS(l) && \
   [...]
```

**Comment by fxlb** [comment]
Or perhaps call it 'NOT_NEGATIVE'

**Comment by mcr** [comment]
fxlb <notifications@github.com> wrote:
    > #define ISPOS(x) (((x) > 0) || ((x) == 0))
    > #define ND_TTEST2(var, l) \
    > (ISPOS(l) && \

okay... sounds good. I think NOT_NEGATIVE is too wordy, but I don't care.

**Comment by guyharris** [comment]
Some quick tests on with llvm-gcc and clang on my x86-64 Mac show that "x > 0 || x == 0" compiles into a single test, so the compiler will probably generate good code for it.

As long as the compiler doesn't say "hey, you're trying to trick me, but x is unsigned so that test will always be true", and issue a warning anyway, I'd say go for it.

I'm OK either with ISPOS or NOT_NEGATIVE.

I'd put in a comment to indicate *why* we're doing that, so people don't ask us about it or "helpfully" submit patches to do it more simply.

**Comment by guyharris** [comment]
It seems to suppress the warnings with llvm-gcc and clang on my Mac.

**Comment by guyharris** [comment]
Actually, now I think I'd go for IS_NOT_NEGATIVE, as that emphasizes what it is we're trying to avoid.

**Comment by fxlb** [comment]
This confirms my tests with gcc on Debian and gcc/clang on Travis.
Comment added.

**Comment by fxlb** [comment]
No more warning. Closing.
