### ISSUE TITLE
Print files should be in their own directory. 

### ISSUE THREAD

**Issue by r0nk** [the-tcpdump-group/tcpdump#447]
There are a ton of "print-" files in the sources root directory. It seems clear to me that they should be placed into their own printers/ directory. Is there some reason they aren't?

**Comment by gvanem** [comment]
Why? Having all .c-files in same directory makes life easier for GNU-make.

**Comment by infrastation** [comment]
I suggest to close this with the resolution that this change won't happen in the next year, at least.

**Comment by fxlb** [comment]
OK to close.
