### ISSUE TITLE
mistagged release

### ISSUE THREAD

**Issue by mcginty** [the-tcpdump-group/tcpdump#461]
https://github.com/the-tcpdump-group/tcpdump/releases

It looks like there was a typo, and the 4.7.4 release's tag is `tcpdump-1.7.4` instead!

**Comment by afett** [comment]
I'd like to see this fixed, too  as my build scripts checkout the sources by release tag.

**Comment by infrastation** [comment]
The commit that was previously tagged 1.7.4 is now tagged 4.7.4, thank you for pointing the typo out.

**Comment by mcr** [comment]
I pushed this again with a pgp signed tag.

**Comment by infrastation** [comment]
Thank you.
