### ISSUE TITLE
Unsatisfied code symbol 'pcap_set_tstamp_precision' in load module '/usr/local/sbin/tcpdump'

### ISSUE THREAD

**Issue by victor-ivas** [the-tcpdump-group/tcpdump#462]
environment: uname -a
HP-UX octans B.11.31 U ia64 1514058526 unlimited-user license

tcpdump version:
/usr/local/sbin/tcpdump --version
tcpdump version 4.7.3
libpcap version 1.1.1
OpenSSL 1.0.0 29 Mar 2010

Error:
/usr/local/sbin/tcpdump -w /tmp/captura.pcap src <IP> and dst <IP> and dst port <port>
/usr/lib/hpux32/dld.so: Unsatisfied code symbol 'pcap_set_tstamp_precision' in load module '/usr/local/sbin/tcpdump'.
Killed

**Comment by guyharris** [comment]
If you got tcpdump from the HP-UX Porting and Archive Centre, or some other site that distributes binaries, get the latest libpcap from the same site and install it.

If you built tcpdump from source code, please run the command `ldd tcpdump` and report what it prints.

**Comment by victor-ivas** [comment]
Hello,

Thank you!
Yes, that was the solution. I've installed latest tcpdump & latest libpcap from the HP-UX Porting and Archive Centre and everything was ok afterwards.
