### ISSUE TITLE
[Solaris] Terminating tcpdump with ^C leaves interface in promiscuous mode

### ISSUE THREAD

**Issue by riingo** [the-tcpdump-group/tcpdump#475]
I was able to recreate this in tcpdump version 4.5.1 and 4.7.4 in a Solaris environment that constructs IPMP. The script chk_capture.sh used is as follows. 

chk_capture.sh:

```
#!/bin/sh

echo "check mac:"
for arg in `echo "::mac_client"|mdb -k|egrep 'net|vlan'|awk '{print $1}'`
do
        echo "$arg::print -t mac_client_impl_t mci_name mci_promisc_list"|mdb -k
done
```

```
root@S12-79:~# dladm show-phys
LINK              MEDIA                STATE      SPEED  DUPLEX    DEVICE
net0              Ethernet             up         0      unknown   vnet0
net3              Ethernet             unknown    0      unknown   vnet3
net2              Ethernet             unknown    0      unknown   vnet2
net1              Ethernet             unknown    0      unknown   vnet1
root@S12-79:~# ipadm create-ipmp ipmp0
root@S12-79:~# ipadm create-ip net1
root@S12-79:~# ipadm create-ip net2
root@S12-79:~# ipadm add-ipmp -i net1 -i net2 ipmp0
root@S12-79:~# ipadm set-ifprop -p standby=on -m ip net2
root@S12-79:~# ipadm create-addr -a local=192.168.0.1/24 ipmp0/v4
root@S12-79:~# ipadm show-addr
ADDROBJ           TYPE     STATE        ADDR
lo0/v4            static   ok           127.0.0.1/8
net0/v4           dhcp     ok           172.16.14.20/20
ipmp0/v4          static   ok           192.168.0.1/24
lo0/v6            static   ok           ::1/128
net0/v6           addrconf ok           fe80::211:22ff:fe48:da7/10
root@S12-79:~# ./chk_capture.sh 
check mac:
char [256] mci_name = [ "net3" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net2" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net1" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net0" ]
mac_cb_t *mci_promisc_list = 0
```

While running `tcpdump`, interfaces will go into promiscuous mode as expected:

```
root@S12-79:~# ./chk_capture.sh 
check mac:
char [256] mci_name = [ "net0" ]
mac_cb_t *mci_promisc_list = 0x4001710ff00
char [256] mci_name = [ "net3" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net2" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net1" ]
mac_cb_t *mci_promisc_list = 0x4001710fe80
char [256] mci_name = [ "net0" ]
mac_cb_t *mci_promisc_list = 0
```

After terminating with ^C, they will remain in promiscuous mode:

```
root@S12-79:~# ./chk_capture.sh 
char [256] mci_name = [ "net3" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net2" ]
mac_cb_t *mci_promisc_list = 0
char [256] mci_name = [ "net1" ]
mac_cb_t *mci_promisc_list = 0x4001710fe80
char [256] mci_name = [ "net0" ]
mac_cb_t *mci_promisc_list = 0
```

Running variations such as `tcpdump -i net1` or `tcpdump -i ipmp0`, etc., will have similar results where interfaces will remain in promiscuous mode after ^C termination. Is this intended?

**Comment by mcr** [comment]
riingo <notifications@github.com> wrote:
    > While running tcpdump, interfaces will go into promiscuous mode as
    > expected:

...
    > Running variations such as tcpdump -i net1 or tcpdump -i ipmp0, etc.,
    > will have similar results where interfaces will remain in promiscuous
    > mode after ^C termination. Is this intended?

No, but since tcpdump could be kill-9'ed, I think it's really a kernel bug if
the interfaces don't return to non-promisc on Solaris.

**Comment by guyharris** [comment]
With the latest versions of libpcap and tcpdump, this shouldn't happen for ^C; tcpdump should catch SIGINT and call `pcap_breakloop()`, so the capture loop should exit and tcpdump should close the capture device - and that should cause promiscuous mode to be turned off.

With Solaris 11, BPF is used, and closing the last BPF device that had put an interface into promiscuous mode *should* turn promiscuous mode off; if not, that is, indeed, a kernel bug, as that's what's supposed to happen with BPF - to quote [the Solaris 11.4 BPF(4D) man page](https://docs.oracle.com/cd/E88353_01/html/E37851/bpf-4d.html):

> `BIOCPROMISC`
>     Forces the interface into promiscuous mode. All packets, not just those destined for the local host, are processed. Since more than one file can be listening on a given interface, a listener that opened its interface non-promiscuously can receive packets promiscuously. This problem can be remedied with an appropriate filter.
> 
> *The interface remains in promiscuous mode until all files listening promiscuously are closed*.

(emphasis mine).

With Solaris 10, BPF isn't available and the DLPI interface is used; the [Solaris 10 DLPI(4P) man page](https://docs.oracle.com/cd/E26505_01/html/816-5177/dlpi-7p.html) doesn't explicitly say anything about promiscuous mode being turned off if the last descriptor on which promiscuous mode was turned on is closed, so that may be just a kernel deficiency, not a "bug" in the sense of "it's not doing what it's advertised to do".

**Comment by guyharris** [comment]
> With Solaris 10, BPF isn't available and the DLPI interface is used; the [Solaris 10 DLPI(4P) man page](https://docs.oracle.com/cd/E26505_01/html/816-5177/dlpi-7p.html) doesn't explicitly say anything about promiscuous mode being turned off if the last descriptor on which promiscuous mode was turned on is closed, so that may be just a kernel deficiency, not a "bug" in the sense of "it's not doing what it's advertised to do".

However:

- [the Open Group documentation for DLPI](https://pubs.opengroup.org/onlinepubs/009618899/DL_PROMISCON_REQ.htm) says:

> DL_PROMISCON_REQ (*dl_promiscon_req_t*) - this primitive requests the DLS Provider to enable promiscuous mode on a per Stream basis, either at the physical level or at the SAP level.
> 
> The DL Provider will route all received messages on the media to the DLS User until either a DL_DETACH_REQ or a DL_PROMISCOFF_REQ is received or the Stream is closed.

- [the Solaris GLDv2 DLPI Primitives documentation](https://docs.oracle.com/cd/E26505_01/html/E27000/gld2.html#gld2-dlpi) says something similar:

> The `DL_PROMISCON_REQ` and `DL_PROMISCOFF_REQ` primitives turn promiscuous mode on or off on a per-stream basis. These controls operate at either at a physical level or at the SAP level. The DL Provider routes all received messages on the media to the DLS user. Routing continues until a `DL_DETACH_REQ` is received, a `DL_PROMISCOFF_REQ` is received, or the stream is closed. You can specify physical level promiscuous reception of all packets on the medium or of multicast packets only.

- [`dlprims.c` in the snoop source code, at least from the "OpenSolaris Launch" commit](https://github.com/illumos/illumos-gate/blob/7c478bd95313f5f23a4c958a745db2134aa03244/usr/src/cmd/cmd-inet/usr.sbin/snoop/dlprims.c), shows code to turn promiscuous mode *on* but not *off*;

so I suspect that even with DLPI the kernel *should* turn promiscuous mode off when there are no streams open on which it's been requested.  If not, *that's* a kernel bug.
