### ISSUE TITLE
Feature request: decode (decompress) `Content-Encoding: gzip`

### ISSUE THREAD

**Issue by arjamizo** [the-tcpdump-group/tcpdump#501]
```
tcpdump -i eth0 -s 1500 port not 22 and port not 53 -vv -X
```

shows

```
0x01b0:  742d 456e 636f 6469 6e67 0d0a 436f 6e74  t-Encoding..Cont
0x01c0:  656e 742d 456e 636f 6469 6e67 3a20 677a  ent-Encoding:.gz
0x01d0:  6970 0d0a 436f 6e74 656e 742d 4c65 6e67  ip..Content-Leng
0x01e0:  7468 3a20 3732 310d 0a43 6f6e 6e65 6374  th:.721..Connect
```

but the content is encrypted - of course. 
Is there any way of unzipping (ungzipping)? 
so I could immediately see decoded content? 

For example `tcpdump -i eth0 -u` where -u stands for --unzip or --ungzip

**Comment by infrastation** [comment]
tcpdump can save the TCP session (or as much of it as possible) contents into an output file and you can split it into HTTP headers and the response itself and then try to do further processing/decoding given you have all the segments and they are properly odered. But that is not guaranteed to work, whether with or without an internal gzip decoder, which to me seems to be out of the expected scope of tcpdump. You may want to look at an HTTP proxy instead.

**Comment by guyharris** [comment]
Wireshark can do it.

But Wireshark does detailed parsing of the HTTP headers, so it knows 1) where the content begins and 2) whether it's compressed.  We could add that to tcpdump as well; at minimum, we'd have to add parsing to know where the compressed content begins, and, at that point, you might as well try to auto-detect compressed content.

However, that also means detecting when the compressed content *ends*, which means parsing the Content-Length header.

So this isn't a quick enhancement.

**Comment by infrastation** [comment]
Excuse me, but the amount of work required to support features of this level is not feasible. Closing.
