### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by mizhdi** [the-tcpdump-group/tcpdump#502]
[ -d /usr/local/sbin ] || \
	    (mkdir -p /usr/local/sbin; chmod 755 /usr/local/sbin)
/usr/bin/install -c tcpdump /usr/local/sbin/tcpdump
/usr/bin/install -c tcpdump /usr/local/sbin/tcpdump.`cat ./VERSION`
[ -d /usr/local/share/man/man1 ] || \
	    (mkdir -p /usr/local/share/man/man1; chmod 755 /usr/local/share/man/man1)
/usr/bin/install -c -m 644 tcpdump.1 /usr/local/share/man/man1/tcpdump.1

**Comment by guyharris** [comment]
So what's the error?

**Comment by mizhdi** [comment]
![image](https://cloud.githubusercontent.com/assets/3582887/13098720/15b20ec0-d566-11e5-854a-36b291fd55a7.png)
what can I do?

**Comment by guyharris** [comment]
Show the *entire* output of the `sudo make install` command, including whatever error there was.  (Hint: next time, do `sudo make install 2>&1 | tee install.log`, and then copy and paste the contents of the `install.log` file into this report.)

**Comment by samxliu1** [comment]
why do you have this (Line 408 in makefile.in) 
	$(INSTALL_PROGRAM) $(PROG) $(DESTDIR)$(sbindir)/$(PROG).`cat ${srcdir}/VERSION`
which leaves an unused image in sbin?

**Comment by infrastation** [comment]
To @samxliu1: developers sometimes need multiple versions of tcpdump installed to make tests.
To @mizhdi: closing due to lack of feedback.
