### ISSUE TITLE
Exiting after file limit reached doesn't print statistics

### ISSUE THREAD

**Issue by mpitt** [the-tcpdump-group/tcpdump#503]
I'm using the combination of `-G <sec> -W 1` to terminate the capture after some time. When the capture terminates this way, tcpdump doesn't print the statistics on packets (captured, received by filter, dropped by kernel) as usual.

Found in version `4.5.1`, confirmed in version `4.7.4`.

**Comment by stevekay** [comment]
Pull request submitted.
https://github.com/the-tcpdump-group/tcpdump/pull/506

**Comment by guyharris** [comment]
Fixed in bb6a08174a1cb1e6281f6bcf7126a7a94e211a47.
