### ISSUE TITLE
Can't build on mac os x

### ISSUE THREAD

**Issue by sokie** [the-tcpdump-group/tcpdump#504]
After downloading the source from github, I build libpcap.
Then I build tcpdump:
./configure
make
The build process completes successfully, but I can't see any changes I do. For example, changing line 1750 to 
`(void)fprintf(stderr, "capturing on %s, link-type %s (%s), capture size %u bytes\n",
			    device, dlt_name,
			    pcap_datalink_val_to_description(dlt), ndo->ndo_snaplen);`

executing the command 
`sudo tcpdump -i any -w file.pcap`

I still get:
`tcpdump: data link type PKTAP
tcpdump: listening on any, link-type PKTAP (Packet Tap), capture size 262144 bytes
`
how come?

**Comment by gvanem** [comment]
`make clean` first?

**Comment by sokie** [comment]
I both did a make clean, as well as start from clean folder and doing a git clone. 
That's why it's odd..

**Comment by fxlb** [comment]
`sudo ./tcpdump -i any -w file.pcap` ?

**Comment by gvanem** [comment]
Well, do the same change to line 1747 too then. Not sure which of then gets triggered; I'm on Win-10...

**Comment by sokie** [comment]
@gvanem It's the correct line...
@fxlb was right tough, I've just made a fool of myself.
Had a different version of tcpdump installed on path.
This can be closed, thanks again folks..

**Comment by mcr** [comment]
sudo ./tcpdump

might help.  . should not be in your path, and certainly not in root's path.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
