### ISSUE TITLE
Not working on android 6.0.1

### ISSUE THREAD

**Issue by fmorenopino** [the-tcpdump-group/tcpdump#507]
Hi!,

I have tried to run the latest release (4.7.4/1.7.4) on Android 6.0.1, but it doesn´t capture any traffic or give an error message (not even the message that you can read if you run the file in another version of Android with information like the number of bytes captured).

There is some known problem about this?

Thanks.

**Comment by xyoung1314** [comment]
I hava the same problem, my device is Samsung A9000, Android version is 6.0.1.

**Comment by guyharris** [comment]
A smartphone usually has at least two devices that act as regular network interfaces - a Wi-Fi interface and a mobile phone interface.

Does this happen on the Wi-Fi interface, the mobile phone interface, or both?

**Comment by fmpino** [comment]
Hi, I solved it compiling myself tcpdump and libpcap using this instructions: http://www.androidtcpdump.com/android-tcpdump/compile.

I used for it an old versions from here: http://www.tcpdump.org/
(the newest ones didn´t work).

I hope it helps you xyoung!

PD: guyharris, it didn´t work with any network interfaces, I suposse that there´s any problem with the newest version.

**Comment by guyharris** [comment]
> I suposse that there´s any problem with the newest version

Or perhaps there's a problem with the Android version of the Linux kernel or its drivers.  It worked on the Linux systems on which I used it.

**Comment by fmpino** [comment]
I haven´t tested it on Linux, so I can´t say anything about it. I just hope it helps someone.

**Comment by infrastation** [comment]
If anybody still can reproduce this issue using the latest versions of tcpdump and libpcap, please provide exact steps to reproduce the problem, otherwise it will be closed soon.
