### ISSUE TITLE
possible race condition in tcpdump 4.7.4 ?

### ISSUE THREAD

**Issue by tereshonkov-roman** [the-tcpdump-group/tcpdump#513]
Running command
tcpdump -vvv -i eth0 -s0 -c3 udp port 1234 -w /tmp/capture.pcap
from time to time I get "Segmentation fault (core dumped)".
To analyse I modified libpcap and tcpdump code to get more output as:

TCPDUMP: tcpdump.c

    static void verbose_stats_dump(int sig _U_)
    {
            struct pcap_stat stat;
            printf("tcpdump: verbose_stats_dump function entered %d\n", infodelay); //<---------
            if (infodelay == 0 && pcap_stats(pd, &stat) >= 0)
                    fprintf(stderr, "Got %u\r", packets_captured);
            alarm(1);
            printf("tcpdump: verbose_stats_dump function exit\n"); //<---------
    }

....

            printf("tcpdump: do loop before calling pcap_close function\n"); //<---------
            pcap_close(pd);
            printf("tcpdump: do loop after calling pcap_close function\n"); //<---------
            if (VFileName != NULL) {
                ret = get_next_file(VFile, VFileLine);

LIBPCAP: pcap.c

    void
    pcap_close(pcap_t *p)
    {
        printf("libpcap: pcap.c: pcap_close\n"); //<---------
            if (p->opt.source != NULL)
                    free(p->opt.source);
            p->cleanup_op(p);
            free(p);
    }

After running the mentioned command I can see the segmentation fault run path:

tcpdump: verbose_stats_dump function entered 0
tcpdump: verbose_stats_dump function exit
tcpdump: verbose_stats_dump function entered 0
tcpdump: verbose_stats_dump function exit
status 0
3 packets captured
234 packets received by filter
121 packets dropped by kernel
tcpdump: do loop before calling pcap_close function
libpcap: pcap.c: pcap_close
tcpdump: verbose_stats_dump function entered 0
Segmentation fault (core dumped)

The origin or the fault is that libpcap function linux_if_drops(const char \* if_name)
gets if_name as NULL and tries to run strlen(if_name).
This caused by accessing to the structure fields which have been already freed.

**Comment by guyharris** [comment]
Fixed in 2a85a1bba4c2e63094a259c5d0ed397f234ba5f3.
