### ISSUE TITLE
When given a filter string, capture ignores -G and -W until a packet is received

### ISSUE THREAD

**Issue by UnitedMarsupials** [the-tcpdump-group/tcpdump#514]
When run without a filter string, the following capture exits after 10 seconds as expected:

```
# date; tcpdump -G 10 -W 1 -w /tmp/%A.pcap ; date
Fri Apr 15 18:38:04 EDT 2016
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
Maximum file limit reached: 1
Fri Apr 15 18:38:14 EDT 2016
```

But, if add a filter-expression, the process would not quit until a packet matching the filter arrives after the specified timeout:

```
# date; tcpdump -G 10 -W 1 -w /tmp/%A.pcap port 65534 ; date
Fri Apr 15 21:23:27 EDT 2016
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
.... hang ....
```

Seems like the timer and other conditions are not verified until a packet is captured. If none satisfies the filter, tcpdump keeps running. It should not... Seeing the problem on both FreeBSD and Linux.

**Comment by mcr** [comment]
Not every capture mechanism will timeout when no packets arrive.
There are changes in recent kernels.  Can you retest and re-open? Thank you.

**Comment by UnitedMarsupials** [comment]
Why not implement the timeout the old-fashioned way -- as a `SIGALRM`-handler?
