### ISSUE TITLE
Incorrect format string %u

### ISSUE THREAD

**Issue by davidsilveiro** [the-tcpdump-group/tcpdump#521]
Within print-802_11.c:1850

```
static void
print_chaninfo(int freq, int flags)
{
        printf("%u MHz", freq); <------- The Culprit!
        if (IS_CHAN_FHSS(flags))
                printf(" FHSS");
        if (IS_CHAN_A(flags)) {
                if (flags & IEEE80211_CHAN_HALF)
                        printf(" 11a/10Mhz");
                else if (flags & IEEE80211_CHAN_QUARTER)
                        printf(" 11a/5Mhz");
                else
                        printf(" 11a");

```

**Comment by gvanem** [comment]
With which compiler is this? I've checked with gcc 5.1 ([TDM-gcc](http://tdm-gcc.tdragon.net/)) and do have `__ATTRIBUTE___FORMAT_OK_FOR_FUNCTION_POINTERS` defined. It gives no warning there.

But you're correct. The function should probably take a `uint16_t`:
```
--- a/print-802_11.c 2016-02-26 20:56:09
+++ b/print-802_11.c 2016-05-31 10:02:06
@@ -2518,7 +2518,7 @@

 static void
 print_chaninfo(netdissect_options *ndo,
-               int freq, int flags, int presentflags)
+               uint16_t freq, int flags, int presentflags)
 {
        ND_PRINT((ndo, "%u MHz", freq));
        if (presentflags & (1 << IEEE80211_RADIOTAP_MCS)) {
```

**Comment by guyharris** [comment]
Or maybe a `uint32_t`, to be future-proof.  11ad uses 60 GHz, i.e. 60000 MHz, and, although I'm not a microwave engineer, I'm not sure 65.536 MHz is necessarily unusable, at least for short-range communication.  Radiotap doesn't yet have any fields with a 32-bit frequency subfield, but we might as well be ready, just in case....

**Comment by infrastation** [comment]
Some radio amateurs do voice communication around 100GHz and well above. IEEE WiFi may make it there too though not tomorrow maybe.

It needs to be noted that the original code snippet is at least two years old. It would be more practical to test the current version of code.

**Comment by infrastation** [comment]
Commit 6334c94 makes the proposed change.

**Comment by infrastation** [comment]
After the higher frequencies are available in the encoding let's see what changes are necessary to accommodate them. Also somebody might want to review the signedness of the `flags` argument of the same function (and probably many others). But this specific issue has been resolved and is now closed, thank you!

**Comment by fxlb** [comment]
> Also somebody might want to review the signedness of the flags argument of the same function

Done in 52ad9e15b42a87c7477cd305d9cfd3afb5128976.
