### ISSUE TITLE
Hardware Timestamping Problem

### ISSUE THREAD

**Issue by Saddun** [the-tcpdump-group/tcpdump#523]
Hello,
(Applogies for my bad english in advance. I'm not a native speaker)

I'm currently working on my Bachelors Thesis.
The aim of my project is to accuratly and precisely timestamp Packages(it has to be at least precise in the tenth of microsecond range).

I am trying to accomplish hardware timestamping with tcpdump, but there are some problems I have encountered.

My Setup:
2 directly connected identical Servers.
Linux: Debian 3.16.7
Network Interface: Intel i350-T4

Used tcpdump command:
sudo /usr/sbin/tcpdump -i eth4 -s 59 port 33333 -x -n -tt -v -j adapter_unsynced --time-stamp-precision=nano -w name.pcap

Now, my results in itself make sense and would give me the desired results, but they have a big offset to them. 36 seconds to be exact.

The jitter of my results with the -j adapter_unsynced option are about 10 µs,
If I use the -j adapter option I get a Jitter of ~100µs( too imprecise for my application),  but not the 36 second offset.

All clocks are syncronised as far as I can see.
The system clocks were both syncronised, and the PHC Clock of the NIC was too.

As a test run I changed the system clock of one of the servers and the change showed up on the results while using -j adapter_unsynced.

So my question is: What am I doing wrong, and is what I want to do even possible with tcpdump?

I'm thankfull for any advice.

Greetings,
Christian

P.S. : ethtool -T  
Time stamping parameters for eth4:
Capabilities:
        hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)
        software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
        hardware-receive      (SOF_TIMESTAMPING_RX_HARDWARE)
        software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
        software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
        hardware-raw-clock    (SOF_TIMESTAMPING_RAW_HARDWARE)
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
        off                   (HWTSTAMP_TX_OFF)
        on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
        none                  (HWTSTAMP_FILTER_NONE)
        all                   (HWTSTAMP_FILTER_ALL)

**Comment by apuls** [comment]
Hey, 

i just looked over the issue list while i cloned the repo and saw your "timestamping issue"

The 36 second offset are they fixed ?
Mabye the timespand are in TAI format

http://www.leapsecond.com/java/gpsclock.htm
https://en.wikipedia.org/wiki/Temps_atomique_international

**Comment by Saddun** [comment]
Hello

yes the Timescale was the problem. hardware clocks use the TAI time, and 
the software clock UTC.
Due to tcpdump not being able to capture hardware timestamps for 
outgoing packages apparently the software clock was used, this lead to 
both capture points using the different timescale, thusly creating a 36s 
offset.

So the problem is still standing.

I could fix that for my project by introducing a third capture point at 
the first Switch on the transmission path, connected via a mirror port 
mechanism, but that is of course not an option for everyone.



Am 26.10.2016 um 16:12 schrieb apuls:

**Comment by guyharris** [comment]
> Due to tcpdump not being able to capture hardware timestamps for
outgoing packages

Which really means "due to *Linux* not being able to capture hardware timestamps for outgoing packets" - it's not anything tcpdump can fix, and, from what I've seen in the kernel, it's not even something *libpcap* can fix.

**Comment by infrastation** [comment]
So the conclusion here is the problem stands but belongs elsewhere, its cause is known but it cannot be solved due to conceptual limitations. Nothing can be done so let's close this issue.
