### ISSUE TITLE
Test failure for tcpdump 4.7.4: pppoes_id

### ISSUE THREAD

**Issue by pwp333** [the-tcpdump-group/tcpdump#524]
Failed test: pppoes_id

1c1
< PPPoE  [ses 0x3b] LCP, Echo-Request (0x09), id 103, length 14
---
> EXIT CODE 00000100

Any idea what could be wrong?

**Comment by infrastation** [comment]
Does tcpdump pass the test if compiled with the latest master branch of libpcap in `../libpcap` ?

**Comment by guyharris** [comment]
On what version of what OS (for Linux, give the distribution name and version, not "Linux" and the kernel version) was this done?

What does `./tcpdump -h` print when run in the build directory?

What does `./tcpdump -t pppoes 0x3b -r tests/pppoes.pcap` print when run in the build directory?

**Comment by pwp333** [comment]
It passed with lasted lippcap. Thanks.
