### ISSUE TITLE
tcpdump with libressl?

### ISSUE THREAD

**Issue by jungle-boogie** [the-tcpdump-group/tcpdump#531]
Hi All,

How can tcpdump be build against libressl? I don't see a `./configure` option.

```
ldd /ldd /usr/local/sbin/tcpdump
/usr/local/sbin/tcpdump:
        libcrypto.so.7 => /lib/libcrypto.so.7 (0x28137000)
        libpcap.so.8 => /lib/libpcap.so.8 (0x282c8000)
        libsmi.so.2 => /usr/local/lib/libsmi.so.2 (0x28306000)
        libc.so.7 => /lib/libc.so.7 (0x28359000)
```

**Comment by guyharris** [comment]
> I don't see a `./configure` option.

There should only be an option if the configure script needs to do something different with libressl than with libssl.

> ldd /ldd /usr/local/sbin/tcpdump
> /usr/local/sbin/tcpdump:
>         libcrypto.so.7 => /lib/libcrypto.so.7 (0x28137000)

OK, that seems to be linked with the part of lib{re}ssl that we use, namely libcrypto.  What more needs to be done here?

**Comment by jungle-boogie** [comment]
`/lib/libcrypto.so.7` is not libressl.

```
% tcpdump -h
tcpdump version 4.8.0-PRE-GIT_2016_07_13
libpcap version 1.4.0
OpenSSL 1.0.1s-freebsd  1 Mar 2016
SMI-library: 0.4.8
```

**Comment by jungle-boogie** [comment]
something like fossil shows this for its ldd:

```
% ldd /usr/local/bin/fossil
/usr/local/bin/fossil:
        libssl.so.38 => /usr/local/lib/libssl.so.38 (0x28337000)
        libcrypto.so.37 => /usr/local/lib/libcrypto.so.37 (0x28387000)
        libz.so.6 => /lib/libz.so.6 (0x28516000)
        libtcl86.so.1 => /usr/local/lib/libtcl86.so.1 (0x2852a000)
        libthr.so.3 => /lib/libthr.so.3 (0x2869e000)
        libm.so.5 => /lib/libm.so.5 (0x286bf000)
        libc.so.7 => /lib/libc.so.7 (0x286e6000)
```
```
% fossil version -v
This is fossil version 1.36 [e1034c4c35] 2016-06-24 03:36:03 UTC
Compiled on Jun 24 2016 10:07:19 using clang-3.4.1 (tags/RELEASE_34/dot1-final 208032) (32-bit)
SQLite 3.13.0 2016-05-18 10:57:30 fc49f556e4
Schema version 2015-01-24
zlib 1.2.8, loaded 1.2.8
SSL (LibreSSL 2.3.6)

```

**Comment by guyharris** [comment]
> `/lib/libcrypto.so.7` is not libressl.

You did not indicate that.

            libcrypto.so.37 => /usr/local/lib/libcrypto.so.37 (0x28387000)

So libssl is installed in `/lib` and libressl is installed in `/usr/local/lib`.

libressl's libssl is compatible with OpenSSL's libssl; if its libcrypto is also compatible with OpenSSL's libcrypto, then all that needs to be done is to get the configure script to look in `/usr/local` for libcrypto.  Unfortunately, the `--with-crypto` configure script argument doesn't take an optional pathname argument, so it can't be used to force the version in /usr/local/lib to be used; I'll look at adding such an argument.

**Comment by jungle-boogie** [comment]
hi @guyharris, I apologize for omitting that.

Thanks for checking out the config script to support arguments for crypto.

**Comment by guyharris** [comment]
OK, try it with the current master version; 119ee4915344cedb05089680a84bca9ffaf3b0b9 adds support for `--with-crypto={directory}`, so try `--with-crypto=/usr/local` - it seemed to work on my Ubuntu VM, with the standard libssl and its -dev package installed under `/` and `/usr` and with libressl installed from source under `/usr/local`.

**Comment by jungle-boogie** [comment]
Hi @guyharris!

excellent work!

```
/usr/local/sbin/tcpdump:
        libcrypto.so.37 => /usr/local/lib/libcrypto.so.37 (0x28137000)
        libpcap.so.8 => /lib/libpcap.so.8 (0x282c6000)
        libsmi.so.2 => /usr/local/lib/libsmi.so.2 (0x28304000)
        libc.so.7 => /lib/libc.so.7 (0x28357000) 
```
