### ISSUE TITLE
Absolute TCP Sequence Number is off by 1

### ISSUE THREAD

**Issue by sorotp** [the-tcpdump-group/tcpdump#538]
Hi,

I was testing tcpdump 4.7.4, libpcap 1.7.4 on ubuntu 16.04 (64-bit) with a simple network communication (running nc listener on one machine and nc client on the other). I noticed that the absolute TCP sequence number is off by 1.

The following packets are the packets after the TCP 3-way handshake. A client (172.16.120.131) sends a text "Hello from client to server." to the server (172.16.120.132). The packets shown are the result of running tcpdump -Xnv -S -r sample.pcap. The seq in the first packet shows 3568581192:3568581221 (which is 3568581192 + 29 (the size of the payload)). But in fact it should be 3568581192:3568581220 because the following packet ACK the sequence number 3568581221  which suppose to be  the sequence number of the previous packet + 1.  

```
14:26:57.988108 IP (tos 0x0, ttl 64, id 2153, offset 0, flags [DF], proto TCP (6), length 81)
    172.16.120.131.34472 > 172.16.120.132.6666: Flags [P.], cksum 0x7634 (correct), seq 3568581192:3568581221, ack 311092815, win 229, options [nop,nop,TS val 2702156 ecr 361788], length 29
    0x0000:  4500 0051 0869 4000 4006 e915 ac10 7883  E..Q.i@.@.....x.
    0x0010:  ac10 7884 86a8 1a0a d4b4 3a48 128a e64f  ..x.......:H...O
    0x0020:  8018 00e5 7634 0000 0101 080a 0029 3b4c  ....v4.......);L
    0x0030:  0005 853c 4865 6c6c 6f20 6672 6f6d 2063  ...<Hello.from.c
    0x0040:  6c69 656e 7420 746f 2073 6572 7665 722e  lient.to.server.
    0x0050:  0a

14:26:57.988531 IP (tos 0x0, ttl 64, id 25459, offset 0, flags [DF], proto TCP (6), length 52)
    172.16.120.132.6666 > 172.16.120.131.34472: Flags [.], cksum 0xba27 (correct), ack 3568581221, win 227, options [nop,nop,TS val 364137 ecr 2702156], length 0
    0x0000:  4500 0034 6373 4000 4006 8e28 ac10 7884  E..4cs@.@..(..x.
    0x0010:  ac10 7883 1a0a 86a8 128a e64f d4b4 3a65  ..x........O..:e
    0x0020:  8010 00e3 ba27 0000 0101 080a 0005 8e69  .....'.........i
    0x0030:  0029 3b4c  
```

The code that affects the display of the sequence number is in the tcpdump-4.7.4 source code (print-tcp.c line 897).

ND_PRINT((ndo, ":%u", seq + length));

It should be
ND_PRINT((ndo, ":%u", seq + length - 1));

**Comment by stevekay** [comment]
Is that line number if 897 correct ?  Just that I see release 4.7.4 only having 897 lines in print-tcp.c.

    $ wc -l print-tcp.c
    897 print-tcp.c
    $ grep -n ND_PRINT.*seq.*len print-tcp.c
    414:                        ND_PRINT((ndo, ":%u", seq + length));
    $

**Comment by sorotp** [comment]
You are right. Sorry I meant line 414.

**Comment by infrastation** [comment]
This is the expected behaviour. With `-S` the seq and ack numbers are displayed as they are in the TCP header. The number after the semicolon is not from the header, tcpdump calculates and displays it for convenience, the [tcpdump man page](http://www.tcpdump.org/manpages/tcpdump.1.html) describes it as follows:
```
The notation is `first:last' which means `sequence numbers  first up to but not including last'.
```
