### ISSUE TITLE
tcpdump capturing less traffic when the month changes

### ISSUE THREAD

**Issue by nilpix** [the-tcpdump-group/tcpdump#540]
I'm using tcpdump to capture the traffic writing pcap files every couple of seconds for a longer period of time. I noticed that when the month changes TcpDump breaks but not completely. It still captures traffic but much less. It could happen because the name of the capture files. The command that i'm using is something like this:

> tcpdump -i eth0 -G 60 -w %d_%m-%H_%M_%S.pcap

It only fails when the month changes.

**Comment by mcr** [comment]
Can you explain "fails" better?  Does the same thing happen when the day changes?

**Comment by nilpix** [comment]
Sorry, yes. I would mean: It still captures traffic but much less than expected.

Maybe, this could be related to the environment used, I was using a disk mounted in ram (ramfs) and maybe is that what is affecting the right functioning.

**Comment by infrastation** [comment]
Without specific steps to reproduce there is nothing to do about this issue, hence closing.
