### ISSUE TITLE
print-syslog.c:96]: (style) Array index 'msg_off' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [the-tcpdump-group/tcpdump#568]
Source code is

        while ( *(pptr+msg_off) >= '0' &&
                *(pptr+msg_off) <= '9' &&
                msg_off <= SYSLOG_MAX_DIGITS) {

Suggest sanity check array index before use.

**Comment by infrastation** [comment]
`ND_TCHECK2(*(pptr + msg_off), 1);` does the check, or do you mean something else?

**Comment by dcb314** [comment]
Not sure about your macro, but I was thinking of something like

    while ( msg_off <= SYSLOG_MAX_DIGITS &&
            *(pptr+msg_off) >= '0' &&
            *(pptr+msg_off) <= '9'
            ) {

**Comment by guyharris** [comment]
As the bug title notes, it's a style issue, not an actual bounds check issue; the "array" is the array of packet data, and the `ND_TCHECK2(*(pptr + msg_off), 1);` calls in the code do the bounds checks in question.

**Comment by infrastation** [comment]
This issue is now resolved, thank you for the report.
