### ISSUE TITLE
Error in print-bootp.c: TAG_PRINTER_NAME and TAG_MDHCP_SERVER

### ISSUE THREAD

**Issue by elear** [the-tcpdump-group/tcpdump#572]
The values for these bootp options do not match the IANA assignments, which refer to the POSIX_TCODE and PCODE, respectively (see RFC 4833).  I've got a patch ready for this that I'll issue a pull request against shortly, along with other stuff (it contains a new option, which is how I noticed).

**Comment by guyharris** [comment]
Fixed by pull request #574, right?
