### ISSUE TITLE
tcpdump -G 15 -W 1 does not work if there is not continuous traffic. 

### ISSUE THREAD

**Issue by zhexuany** [the-tcpdump-group/tcpdump#577]
As a site reliability engineer, I sometime need `tcpdump` port to digest the traffic for a specific port. 
Recently, I just found `tcpdump -G 15 -W 1 ` will not work correctly if there is not continuous traffic. Should I consider this as a feature instead of bug?

**Comment by zhexuany** [comment]
It's a duplicated issue with https://github.com/the-tcpdump-group/tcpdump/issues/577. I am closing it.

**Comment by zhexuany** [comment]
#338

**Comment by guyharris** [comment]
Duplicate of #338
