### ISSUE TITLE
Heap out of bound read in cip_if_print() function in print_cip.c

### ISSUE THREAD

**Issue by deepsjal** [the-tcpdump-group/tcpdump#582]
**Tested on**: TcpDump: 4.8.1 and LibPcap: 1.9.0

**How to Reproduce**: Compile tcpdump in asan mode (-fsanitize=address) and tcpdump -r attachment

Sample attachment Pcap: 

[heapoverflowreadprint-cip66.tar.gz](https://github.com/the-tcpdump-group/tcpdump/files/698563/heapoverflowreadprint-cip66.tar.gz)

**Asan Output:**

=================================================================
==19898== ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb5c00735 at pc 0x807a342 bp 0xbfcc2c28 sp 0xbfcc2c1c
READ of size 1 at 0xb5c00735 thread T0
    #0 0x807a341 in cip_if_print    /tcpdump/4.8.1/gccasan/./print-cip.c:66
    #1 0x80582f2 in pretty_print_packet    /tcpdump/tcpdump-4.8.1/./print.c:339
    #2 0x8052036 in print_packet    /tcpdump/4.8.1/gccasan/./tcpdump.c:2262
    #3 0xb5f9efd5 in pcap_offline_read    /libpcap/gccbuild/./savefile.c:527
    #4 0xb5f8ce9e in pcap_loop    /libpcap/gccbuild/./pcap.c:890
    #5 0x804f349 in main    /tcpdump/4.8.1/gccasan/./tcpdump.c:1766
    #6 0xb5deaaf2 (/lib/i386-linux-gnu/libc.so.6+0x19af2)
    #7 0x80515b0 in _start (   /tcpdump/4.8.1/gccasan/tcpdump+0x80515b0)
0xb5c00735 is located 1 bytes to the right of 4-byte region [0xb5c00730,0xb5c00734)
allocated by thread T0 here:
    #0 0xb6186854 (/usr/lib/i386-linux-gnu/libasan.so.0+0x16854)
    #1 0xb5f9fb49 in pcap_check_header    /libpcap/gccbuild/./sf-pcap.c:401
SUMMARY: AddressSanitizer: heap-buffer-overflow    /tcpdump/4.8.1/gccasan/./print-cip.c:66 cip_if_print
Shadow bytes around the buggy address:
  0x36b80090: fa fa 05 fa fa fa 07 fa fa fa 00 fa fa fa 00 00
  0x36b800a0: fa fa 00 fa fa fa 00 00 fa fa 00 04 fa fa 00 fa
  0x36b800b0: fa fa 00 00 fa fa 00 04 fa fa 00 fa fa fa 00 00
  0x36b800c0: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa fd fd
  0x36b800d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x36b800e0: fa fa fd fa fa fa[04]fa fa fa 00 07 fa fa 00 04
  0x36b800f0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa fd fd
  0x36b80100: fa fa 04 fa fa fa 04 fa fa fa 00 01 fa fa 00 01
  0x36b80110: fa fa 04 fa fa fa 04 fa fa fa 00 01 fa fa 00 01
  0x36b80120: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x36b80130: fa fa 00 03 fa fa 00 03 fa fa 00 01 fa fa 00 01
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==19898== ABORTING

**Note**: Found using AFL

**Comment by infrastation** [comment]
This is a duplicate of #567.

**Comment by infrastation** [comment]
Please send any future security reports to security@tcpdump.org.
