### ISSUE TITLE
Announce and Release 4.9

### ISSUE THREAD

**Issue by nluedtke** [the-tcpdump-group/tcpdump#584]
Version 4.9 has been announced by several distro's and posted publicly, as such, an announcement and release should be made to address several CVEs that have made public.

**Comment by infrastation** [comment]
Yes, it should be made and it will be made.

**Comment by Barthalion** [comment]
Any estimates? Is the thing that Debian ships considered the official 4.9.0? Which commit is it derived from?

**Comment by gmacario** [comment]
@Barthalion 

> Which commit is it derived from?

Please see https://anonscm.debian.org/git/users/rfrancoise/tcpdump.git/log/

**Comment by Barthalion** [comment]
I have been there already. There is no information which commit has been "imported" as `upstream/4.9.0`, and files like `VERSION` or `CHANGES` from GitHub repository are completely out of sync with what Debian shipped. I just want to have clear indication what is the timeframe for official 4.9.0 release or what is the relationship between Debian sources and what I considered upstream so far.

**Comment by infrastation** [comment]
@Barthalion, Arch Linux now has the information you were looking for.

**Comment by Barthalion** [comment]
Sorry, but who has specifically? I didn't receive anything at bpiotrowski@archlinux.org.

**Comment by Barthalion** [comment]
Alright, I got it now at different address. Thanks.

**Comment by fpletz** [comment]
Why the secrecy? Not releasing a new version when distributions are already packaging that new version is absurd and harmful for all users of tcpdump not using the distributions you have informed.

Asking as security team member of [NixOS](https://nixos.org/).

**Comment by domenkozar** [comment]
It's hard to agree on best security practise with the timing. But openssl have finally learned that, announce the patch upfront for everyone, but make sure distros are included.

**Comment by rfrancoise** [comment]
The Debian package is not based on a Git commit but on the 4.9.0 upstream tarball, which is available here:

 http://www.tcpdump.org/4.9.0-u82xFZBjZxWv/

It is signed with the tcpdump.org release key, and was generated from a private Git repository that is managed by Michael and the rest of the tcpdump team.

(You can regenerate the upstream tarball from the Debian sources using pristine-tar, and check that the signature matches.)

**Comment by infrastation** [comment]
If anybody still needs any additional information, please contact security@tcpdump.org as advised on the web-site. Thank you.

**Comment by infrastation** [comment]
The 4.9.0 release has been published on www.tcpdump.org and GitHub, it is exactly the code that some vendors have already used to prepare their updated packages. Hopefully next time the publication will be organized better. Thank you for your patience!
