### ISSUE TITLE
Passing same buffer as in and out to EVP_Cipher() in print-esp.c

### ISSUE THREAD

**Issue by glebius** [the-tcpdump-group/tcpdump#586]
The prototype of EVP_Cipher() doesn't allow to pass const buffer as in. It seems that the feature of passing the same buffer as in and out is undocumented and may disappear. Better to allocate a temporary buffer for out.

At FreeBSD we currently fixed compilation with __DECONST() macro, but this isn't right solution.

**Comment by msehnout** [comment]
The buffer should also have size that is a multiple of a block size of given cipher. It works fine on most architectures, but fails on ppc64le. There is a RH bugzilla for this with more information: https://bugzilla.redhat.com/show_bug.cgi?id=1441963

**Comment by guyharris** [comment]
The master branch has both fixes.
