### ISSUE TITLE
Memory used

### ISSUE THREAD

**Issue by JMDelhGit** [the-tcpdump-group/tcpdump#593]
Hello,

Most likely not an issue but cannot find the way to handle the problem. Therefore I'm addressing it here.

On MacOS, using libpcap to check WiFi LAN activity, I have noticed that libpcap use **huge** memory when  a connection exists between the Mac using libpcap and another Mac on the LAN. 

It can use several GB or the whole memory available temporarily.

This happens in monitor mode with total bytes read of 20MB-50MB in 20 seconds
  or in non monitor mode were the total number of bytes read is less than a few thousands bytes for 20 seconds

I would like to stop the scan when the memory used is > 300MB for example. 

Unfortunately, the memory used by libpcap is not available using:
`
  int memoryUsed = 0;   
   struct mach_task_basic_info info;
    mach_msg_type_number_t size = MACH_TASK_BASIC_INFO_COUNT;
    kern_return_t kerr = task_info(mach_task_self(),
                                   MACH_TASK_BASIC_INFO,
                                   (task_info_t)&info,
                                   &size);
    if( kerr == KERN_SUCCESS ) {
        memoryUsed = info.resident_size;
    }
`
This provides only the memory used by the calling process not the memory used by libpcap.

Is there a libpcap variable or function that returns the memory used (or buffer size used) 
or a way to limit the buffer used ?

Thank you in advance,
Jean

**Comment by guyharris** [comment]
There is some calling program that's using libpcap.  How do you know that the memory is being used by libpcap, not by the program?

> Unfortunately, the memory used by libpcap is not available using:

Are you certain that's the case?  A quick look at the x86 pmap code in Sierra doesn't show any obvious sign that the resident_size for a pmap counts only some pages; note that, within a process, a library that uses `malloc()` allocates memory from the exact same heap as the one from which a similar allocation, using `malloc()`, in the main program would use, so a page could well contain *both* data allocated by a library and data allocated by the main program.  This applies even to shared libraries such as libpcap.

Libpcap doesn't allocate a lot of memory, so I *very strongly* believe that what's consuming the memory is the program, not libpcap.

**Comment by JMDelhGit** [comment]
You are right.
My calling program is in Objective-C. 
I was rebuilding the main container in the class delegate at each packet read callback.
I fixed the problem and everything is ok now.

Thank you,
Jean
