### ISSUE TITLE
Endless loop when reading input file

### ISSUE THREAD

**Issue by fgeek** [the-tcpdump-group/tcpdump#596]
When reading fuzzed input file tcpdump goes to endless loop:
```
wget http://bugs.fi/media/afl/tcpdump/endless-loop.pcap
tcpdump -ntr endless-loop.pcap
```
Fuzzed with [afl](http://lcamtuf.coredump.cx/afl/), instances controlled with [afl-utils](https://github.com/rc0r/afl-utils) and the minimized corpus (with [afl-kit](https://github.com/kcwu/afl-kit)) can be downloaded from [git](https://bitbucket.org/henrisalo/fuzzing-tcpdump).

**Comment by infrastation** [comment]
To report a security issue please send an e-mail to security@tcpdump.org.

**Comment by guyharris** [comment]
And both crashes, and infinite loops, due to a bad packet are security issues.

**Comment by fxlb** [comment]
Thanks for the report.
This issue, already reported by another contributor, is fixed in the security branch (Will be merged in a few weeks).

**Comment by fgeek** [comment]
Thank you.

**Comment by fgeek** [comment]
What is the status with the merge?

**Comment by infrastation** [comment]
Some works still remains to be done, please allow us the time required.

**Comment by fgeek** [comment]
70 days have passed. Status?

**Comment by gvanem** [comment]
I tried to verify this bug on Windows, but the `.pcap`-file is gone:
```
 ERROR 404: Not Found.
```

**Comment by fgeek** [comment]
I was asked to remove the file from public by security@tcpdump.org, but I'll email it to you privately. I don't know what is the exact security reporting guidelines for tcpdump, but I don't consider this case to be high severity so the sample can be shared. I was expecting the merge to happen already and I have no current information about the status. Not sure if the another researcher is receiving information. I'll reopen this issue report so that this case is not lost to the void.

**Comment by gvanem** [comment]
Confirmed on Windows too (off course). And just a FYI:
```
tshark: The file "endless-loop.pcap" appears to be damaged or corrupt.
(pcap: File has 218959117-byte packet, bigger than maximum of 262144)
```
But where `invalid` gets printed in tcpdump is unknown to me. Lots of sources.

**Comment by fgeek** [comment]
This is still issue in 4.9.1 release released today.

**Comment by infrastation** [comment]
Thank you for reminding.

**Comment by infrastation** [comment]
This was one of the problems resolved in tcpdump release 4.9.2. As a traditional reminder, please report any future security issues with tcpdump to security@tcpdump.org. Closing.

**Comment by fgeek** [comment]
@infrastation Which commit fixed this issue? Did you request CVE identifier for this case?

**Comment by infrastation** [comment]
I cannot tell without the file but if you have the .pcap file, `git bisect` will tell you the commit and the commit will tell you the CVE ID.
