### ISSUE TITLE
value of capture size when running tcpdump on linux

### ISSUE THREAD

**Issue by husheng5** [the-tcpdump-group/tcpdump#601]
When running `tcpdump -ni eth0 -w data.pcap -v` on different hosts, tcpdump firstly shows:
    

> tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size **65535** bytes

or 
    

> tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size **262144** bytes

Why is the capture size different:65535 and 262144? What does this value  mean? Thanks!

**Comment by infrastation** [comment]
If you search for "snapshot-length" at http://www.tcpdump.org/manpages/tcpdump.1.txt you will find the bit of documentation that explains it. The difference in value is because of different versions of libpcap having different default value.

**Comment by husheng5** [comment]
Thanks!
