### ISSUE TITLE
Missing 802.11 frame types on ARM

### ISSUE THREAD

**Issue by lennartkoopmann** [the-tcpdump-group/tcpdump#610]
When running on ARM architectures, I am only seeing recorded `beacon` and `probe-req` 802.11 frames but no other types like `probe-resp`, `deauth` or `assoc-*`.

Running `tcpdump` like this:

    ~# tcpdump -i wlan1 type mgt

Device `wlan1` is in monitor mode.

Running the exact same commands with the same WiFi adapter on the same Debian version works without issues on a `x86_64`.

Tried it with the standard Debian `tcpdump` and one compiled from source:

* tcpdump v4.9.0
* libpcap v1.8.1

Tried it with these devices, successfully on `x86_64`, failing on ARM (Raspberry Pi 3):

* ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
* ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

Why am I only seeing `beacon` and `probe-req` frames on ARM?

Any help is greatly appreciated!

**Comment by guyharris** [comment]
Are both devices listening on the same channel?

**Comment by lennartkoopmann** [comment]
Yes, I took care of setting the right channel.

**Comment by guyharris** [comment]
Then it's probably something at a layer below libpcap, even if *all* the software is the same.

**Comment by lennartkoopmann** [comment]
Thank you!
