### ISSUE TITLE
unresolved fall-through warnings from GCC 7

### ISSUE THREAD

**Issue by infrastation** [the-tcpdump-group/tcpdump#618]
A test build on Fedora 26 had produced a number of fall-through warnings, some of which I could resolve but the ones below still stand:
* One case in `print-isoclns.c` (not previously detected by Coverity). I could find a few CNLP packet diagrams but it was not enough to understand how to resolve.
```
./print-isoclns.c: In function ‘clnp_print’:
./print-isoclns.c:1041:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (*(pptr) == NLPID_CLNP) {
                ^
./print-isoclns.c:1048:9: note: here
         case  CLNP_PDU_DT:
         ^~~~
```
* Four cases in `print-rx.c` (existing Coverity defects 603361, 603362, 603363 and 976452). The only description of the Rx protocol used in AFS I could find was the OpenAFS git repository, in which I could not find anything to relate with the case blocks below. My best guess here is all four fall-through cases are not intentional.
```
./print-rx.c: In function ‘fs_print’:
./print-rx.c:1009:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
   {
   ^
./print-rx.c:1023:3: note: here
   case 65537: /* Fetch data 64 */
   ^~~~
./print-rx.c: In function ‘cb_print’:
./print-rx.c:1250:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
   {
   ^
./print-rx.c:1282:3: note: here
   case 214: {
   ^~~~
In file included from ./print-rx.c:47:0:
./print-rx.c: In function ‘vldb_reply_print’:
./netdissect.h:326:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define ND_PRINT(STUFF) (*ndo->ndo_printf)STUFF
./print-rx.c:777:4: note: in expansion of macro ‘ND_PRINT’
    ND_PRINT((ndo, " %d", _i)); \
    ^~~~~~~~
./print-rx.c:1741:4: note: in expansion of macro ‘INTOUT’
    INTOUT();
    ^~~~~~
./print-rx.c:1742:3: note: here
   case 503: /* Get entry by id */
   ^~~~
In file included from ./print-rx.c:47:0:
./netdissect.h:326:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define ND_PRINT(STUFF) (*ndo->ndo_printf)STUFF
./print-rx.c:777:4: note: in expansion of macro ‘ND_PRINT’
    ND_PRINT((ndo, " %d", _i)); \
    ^~~~~~~~
./print-rx.c:1790:4: note: in expansion of macro ‘INTOUT’
    INTOUT();
    ^~~~~~
./print-rx.c:1791:3: note: here
   case 518: /* Get entry by ID N */
   ^~~~
```

**Comment by kaduk** [comment]
Hopefully the help offered on the openafs-devel list will come through, but I note that in addition to the "spec" at http://git.openafs.org/?p=openafs.git;a=blob;f=doc/txt/rx-spec.txt;h=c1499132ebba3109231647bf4fbb3c5034a80c55;hb=HEAD and the OpenAFS implementation, the linux AF_RXRPC is the same Rx protocol.

**Comment by infrastation** [comment]
Thank you for the update. I think I had looked through `rx-spec.txt` before, but could not make it out if "inline bulk stat" (65536), "callback" (204), "list entry" (510) and "list entry U" (529) relate to the next case block(s) or not. Some of those words do not even appear in the file. I guess those encoding items could be described somewhere in the RPC/XDR-related files within the repository.

**Comment by kaduk** [comment]
I took a look.  The first two ("bulk stat" and "callback"; lines 1023 and 1282) should not fall through, but the other two ("list entry" in various forms, lines 1741 and 1790) *should* fall through.
The answer lies in the RPC-L files at http://git.openafs.org/?p=openafs.git;a=blob;f=src/fsint/afsint.xg;h=9fe4980c6cffcae457789e363393825e29dcb7b1;hb=HEAD#l594, http://git.openafs.org/?p=openafs.git;a=blob;f=src/fsint/afscbint.xg;h=19760bc512c647595662c30e190303b3a20be983;hb=HEAD#l22, and http://git.openafs.org/?p=openafs.git;a=blob;f=src/vlserver/vldbint.xg;h=ff34d12d45454de328439cab3ed896fd564f0c59;hb=HEAD#l341 (also line 396), looking at the appropriate IN or OUT arguments.

**Comment by infrastation** [comment]
I take your word for it. Now it only remains to add two instances of `ND_FALL_THROUGH` and two instances of `break`, possibly with comments, would you like to author this change yourself?

**Comment by infrastation** [comment]
The fix is in the master branch now, thank you very much!
