### ISSUE TITLE
'or' operation in pcap filter is buggy

### ISSUE THREAD

**Issue by pinggit** [the-tcpdump-group/tcpdump#623]
the 'or' operation is buggy:

root@comp82:~# tcpdump -nr  testbond2_tshark.pcap  udp[42:2]=0xac10 | grep 36.689703
reading from file testbond2_tshark.pcap, link-type EN10MB (Ethernet)
08:40:36.689703 IP 172.29.6.35.51638 > 172.29.8.26.51234: UDP, length 70

root@comp82:~# tcpdump -nr  testbond2_tshark.pcap udp[82:4]=0xac103fff or ip[98:4]=0xac103fff or udp[42:2]=0xac10 | grep 36.689703
reading from file testbond2_tshark.pcap, link-type EN10MB (Ethernet)
<nothing>

**Comment by guyharris** [comment]
What do

    tcpdump -dnr testbond2_tshark.pcap udp[42:2]=0xac10

and

    tcpdump -dnr testbond2_tshark.pcap udp[82:4]=0xac103fff or ip[98:4]=0xac103fff or udp[42:2]=0xac10

print?
