### ISSUE TITLE
tcpdump-4.9.2/print-isoclns.c:899: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [the-tcpdump-group/tcpdump#629]
tcpdump-4.9.2/print-isoclns.c:895] -> [tcpdump-4.9.2/print-isoclns.c:899]: (warning) Opposite inner 'if' condition leads to a dead code block.

Source code is

        while (li >= 2) {
            u_int op, opli;
            const uint8_t *tptr;

            if (li < 2) {
                ND_PRINT((ndo, ", bad opts/li"));
                return (0);
            }

Suggest remove pointless inner if test.

**Comment by infrastation** [comment]
That is a good point.

**Comment by infrastation** [comment]
Which tool did you use to get the warning?

**Comment by dcb314** [comment]
A static analyser for C & C++ called "cppcheck".

Downloadable from http://cppcheck.sourceforge.net/

**Comment by infrastation** [comment]
This issue has been fixed, thank you for reporting it.
