### ISSUE TITLE
please consider having -w with additional console output

### ISSUE THREAD

**Issue by Zugschlus** [the-tcpdump-group/tcpdump#639]
Hi,

I frequently find myself running tcpdump -w to obtain a packet dump _and_ in another window on the same machine tcpdump with the same filter, but without -w, to see whether the phenomenon I am investigating has actually happened.

It would be so nice if there would be a possibility to have both with a single call, writing a pcap file _and_ having regular console output. Maybe the combination of -v and -w would not suppress regular output in the future?

Thanks for considering this!

Greetings
Marc

**Comment by lilchurro** [comment]
I second this! It doesn't seem like a terribly difficult thing to implement. I'll take a look.

**Comment by guyharris** [comment]
> Maybe the combination of -v and -w would not suppress regular output in the future?

What if somebody wants *non-verbose* printed output while writing to a file?  `-v` plus `-w` can't do that.

TShark has a `-P` option that causes output - regardless of how verbose it is - to be printed, even if `-w` is specified.  Unfortunately, macOS's tcpdump uses `-P` to mean "write the capture in pcapng format", so we probably don't want to use `-P` for this purpose.

**Comment by lilchurro** [comment]
Actually, one of the harder aspects of adding features to tcpdump is the shrinking number of flags available. I was wondering if I could repurpose -V (read a list of filenames from file) as -R (which is not taken yet, but the function would be related to -r) and use -R for this purpose. Any advice on this?

**Comment by lilchurro** [comment]
Maybe a long opt like `--print-to-console` when used with `-w`, then.

**Comment by guyharris** [comment]
> `--print-to-console`

What if you're printing to a file at the same time you're saving the capture to a file?  I'd go for just `--print`.

**Comment by lilchurro** [comment]
ACK'd.

**Comment by guyharris** [comment]
Fixed in 9b845d6549f426b892d61b5d05adb2823ecaf991.

**Comment by mcr** [comment]
so, my plan was to cp tcpdump.c pktdump.c, rip out all the options and start
anew.  Long options for everything, and no short options until after the
option shows itself useful.   ENOTIME, but maybe someone else would like to start.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by lilchurro** [comment]
I think that would be worth doing, and would like to help with that effort.

**Comment by fxlb** [comment]
>Long option for evething

It risks not to be practical to use...

**Comment by mcr** [comment]
fxlb <notifications@github.com> wrote:
    > Long option for evething

    > It risks not to be practical to use...

That's the starting point.  Scripts should always use long options to be sure.
Then you add short options based upon popular demand.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
