### ISSUE TITLE
Proper ways to make up for missing getservent() and endservent() on windows

### ISSUE THREAD

**Issue by sgeto** [the-tcpdump-group/tcpdump#640]
[This commit](https://github.com/the-tcpdump-group/libpcap/commit/1e1466905fa8c5adfb08796acd809abde517bdd6) in libpcap removed the file Win32/Src/getservent.c under the assumption that it's unused.
Well. it's not needed libpcap but needed by windump: [init_servarray()](https://github.com/the-tcpdump-group/tcpdump/blob/master/addrtoname.c#L785)

[getservent() and endservent() are not implemented in windows](https://www.gnu.org/software/gnulib/manual/html_node/getservent.html#getservent). That's the bad news.
The good news is that only this is currently what's preventing tcpdump from being build on windows.

So..

A. Bring getservent.c and its support files back?
B. Do it like [bash ](https://git.savannah.gnu.org/cgit/bash.git/tree/bashline.c?h=bash-4.4#n2409) or glib and simply `ifndef` them?
C. Find alternatives?

**Comment by guyharris** [comment]
D. Put it in the tcpdump source rather than the libpcap source.

**Comment by guyharris** [comment]
...and make sure it opens `%systemroot%\System32\Drivers\Etc\Services` (or however it's supposed to be capitalized).

**Comment by sgeto** [comment]
> D. Put it in the tcpdump source rather than the libpcap source.

That's what I meant with A

> ...and make sure it opens %systemroot%\System32\Drivers\Etc\Services (or however it's supposed to be capitalized).

case shouldn't matter. but all lowercase is a good parctice

**Comment by guyharris** [comment]
> ...and make sure it opens `%systemroot%\System32\Drivers\Etc\Services`

See, for example, `Win32/src/ether_ntohost.c`.

**Comment by sgeto** [comment]
`Win32/src/ether_ntohost.c` helps in parsing `%SystemRoot%\drivers\etc\ethers` which should be `%SystemRoot%\system32\drivers\etc\ethers` but  that doesn't matter since this file doesn't exists (anymore).

May I ask why you would want getservent.c (or tcpdump in general) to read `%systemroot%\system32\drivers\etc\services`?
Ask differently: When is this information needed by the application?

**Comment by guyharris** [comment]
> `Win32/src/ether_ntohost.c` helps in parsing `%SystemRoot%\drivers\etc\ethers` which should be `%SystemRoot%\system32\drivers\etc\ethers` but that doesn't matter since this file doesn't exists

It also helps in constructing the *path* to `%SystemRoot%`; that's what I was saying should be used in `getservent.c`?

> When is this information needed by the application?

Well, you found the calls to `getservent()`, so you presumably found where it's needed. :-)

It's used to translate port numbers to service names, e.g. saying "http" instead of "80".  See, for example, `tcpport_string()`.

**Comment by sgeto** [comment]
Hehe good one...

> It's used to translate port numbers to service names, e.g. saying "http" instead of "80". See, for example, tcpport_string().

So if tcpdump can't use this (or can't find the file), it will always show the port numbers?
Is showing port numbers the default behavior? Is there a option to toggle between port numbers to service names? (I guess I should see the man page... 😄)
would this:

06:21:24.577597 IP lb-192-30-253-112-iad.github.com.**443** > CALCULON.25083: Flags [.], seq 93984:95408, ack 1, win 40, options [nop,nop,TS val 2518648575 ecr 1061550440], length 1424

say this:
06:21:24.577597 IP lb-192-30-253-112-iad.github.com.**https** > CALCULON.25083: Flags [.], seq 93984:95408, ack 1, win 40, options [nop,nop,TS val 2518648575 ecr 1061550440], length 1424

under normal conditions? (running `./tcpdump.exe -i\Device\NPF_{F710F358-7869-4158-B9E9-9661763D81F2} port 443`

**Comment by guyharris** [comment]
> So if tcpdump can't use this (or can't find the file), it will always show the port numbers?

Yes.

> Is showing port numbers the default behavior?

Yes.

> Is there a option to toggle between port numbers to service names?

If the `-n` flag is specified, several resolutions of numerical values to names are disabled, including IP addresses to host names, MAC addresses to host names, and port numbers to service names.

> would this: ... say this: ... under normal conditions?

Yes.
