### ISSUE TITLE
OpenBSD fails to compile tcpdump

### ISSUE THREAD

**Issue by jungle-boogie** [the-tcpdump-group/tcpdump#650]
Hello,

TCPDump from master fails to compile on openBSD -current. I cannot get the configure to work:

```
checking for snprintf... yes
checking for library containing dnet_htoa... no
checking for main in -lrpc... no
checking for library containing getrpcbynumber... none required
checking for local pcap library... ../libpcap/libpcap.a
checking for pcap-config... ../libpcap/pcap-config
checking for pcap_loop... no
configure: error: This is a bug, please follow the guidelines in CONTRIBUTING and include the
config.log file in your report.  If you have downloaded libpcap from
tcpdump.org, and built it yourself, please also include the config.log
file from the libpcap source directory, the Makefile from the libpcap
source directory, and the output of the make process for libpcap, as
this could be a problem with the libpcap that was built, and we will
not be able to determine why this is happening, and thus will not be
able to fix it, without that information, as we have not been able to
```

* tcpdump and libpcap version (tcpdump --version)
last successful install:
```
$ /usr/local/sbin/tcpdump --version
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.9.0-PRE-GIT
LibreSSL 2.6.3
```

* operating system name and version and any other details that may be relevant
  (uname -a, compiler name and version, CPU type etc.)

OpenBSD amd 64 bit current. It's an old laptop, but still functioning fine.

* configure flags if any were used

none, straight `./configure`

* statement of the problem

Cannot compile tcpdump, but libpcab will compile without any issues

* steps to reproduce

```
git clone https://github.com/the-tcpdump-group/tcpdump
cd tcpdump
./configure
```

libpcap is installed and available here:
```
$ ls -l /usr/local/lib/libpcap*
-rw-r--r--  1 root  wheel  946062 Nov 15 19:52 /usr/local/lib/libpcap.a
lrwxr-xr-x  1 root  wheel      12 Nov 15 19:52 /usr/local/lib/libpcap.so -> libpcap.so.1
lrwxr-xr-x  1 root  wheel      24 Nov 15 19:52 /usr/local/lib/libpcap.so.1 -> libpcap.so.1.9.0-PRE-GIT
-rwxr-xr-x  1 root  wheel  586835 Nov 15 19:52 /usr/local/lib/libpcap.so.1.9.0-PRE-GIT
```

Attached are some makefiles and config files that may assist you:
[libpcap_tcpdump_files.zip](https://github.com/the-tcpdump-group/tcpdump/files/1479116/libpcap_tcpdump_files.zip)

**Comment by sgeto** [comment]
weird in a few ways...

`checking for local pcap library... ../libpcap/libpcap.a
`
it's favoring the libpcap library in `../libpcap` when you're expecting it to link with the one in `/usr/local/lib/`
I guess the build system should look for  `../libpcap/libpcap.a` `after` failing to find  libpcap via `pcap-config` or in the compiler's default search path.

can you remove `../libpcap` or run `make distclean` or `git clean` in ../libpcap and try again?

**Comment by jungle-boogie** [comment]
Hi @sgeto,

Thanks for the response.

I did a `make distclean` in the `libpcap` directory that I've cloned from github; `git clean` reported:
`fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean`

Performing a `./configure` in the `tcpdump` directory results in the same config issue.

**Comment by sgeto** [comment]
git clean takes the mandatory option -f. try:

`git clean -xdf` and/or `git clean -Xdf`

**Comment by jungle-boogie** [comment]
Hi @sgeto,

Performing, `git clean -xdf` and `git clean -Xdf` within the `libpcap` github clone directory worked. However, I still cannot get `tcpdump` to run the `./configure`.

**Comment by sgeto** [comment]
> However, I still cannot get tcpdump to run the ./configure.

You mean you're getting the same error? If so do another `git clean` in the tcpdump directory, run configure again **and then** upload you're config.log file again.

**Comment by jungle-boogie** [comment]
Hi @sgeto,

yes, I receive the same error when running `./configure`, even after the `git clean`.

**Comment by guyharris** [comment]
> it's favoring the libpcap library in `../libpcap`

Yes, that's what the build process was designed to do, dating back at least as far as the final release from LBL, tcpdump 3.4.  It probably dates back before then.

This allows you to build tcpdump with a libpcap release without having to install that tcpdump release.  That's handy for:

1. testing, if you're a libpcap/tcpdump developer;

1. building your own personal version of tcpdump, with your own personal version of libpcap, if you don't have permission to install a new version of libpcap on a machine (or don't want to).

> I guess the build system should look for  `../libpcap/libpcap.a` **after** failing to find  libpcap via `pcap-config` or in the compiler's default search path.

No, it should do what it's currently doing.

**Comment by sgeto** [comment]
upload you're config.log file

**Comment by jungle-boogie** [comment]
@guyharris,

> No, it should do what it's currently doing.

So, should I tell config to look elsewhere for `libpcap`?

[config.log](https://github.com/the-tcpdump-group/tcpdump/files/1479735/config.log)

**Comment by mcr** [comment]
If you don't want it to find ../libpcap/ then remove that directory, or move your tcpdump source elsewhere. I don't think that --with-libpcap= works, although it should perhaps work.
But, what's wrong with your ../libpcap build?

**Comment by sgeto** [comment]
the error is much shorter now in config.log:

```
configure:5347: checking for pcap-config
configure:5365: found /usr/local/bin/pcap-config
configure:5377: result: /usr/local/bin/pcap-config
configure:5592: checking for pcap_loop
configure:5592: gcc -o conftest -g -O2   conftest.c -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lpcap  -L/usr/local/lib -ldbus-1  >&5
/usr/local/lib/libdbus-1.so.11.1: warning: warning: vsprintf() is often misused, please use vsnprintf()
/usr/local/lib/libpcap.so: undefined reference to `pcap_fmt_errmsg_for_errno'
/usr/local/lib/libpcap.so: undefined reference to `pcap_fopen'
collect2: ld returned 1 exit status
```

**Comment by sgeto** [comment]
@mcr true. something's stange about his ../libpcap build
I also remember a recent change involving `pcap_fopen` in master. Maybe it's that...
I would probably rebuild and install pcap again and see if that helps.

**Comment by jungle-boogie** [comment]
i've performed the following:
`rm -rf libpcap`
`cd ..`
`mkdir pcap`
`cd pcap`
`git clone https://github.com/the-tcpdump-group/libpcap`
`cd libpcap`
`./configure`
`make`
made without any problem
`doas make install`
```
-rwxr-xr-x  1 root  wheel  590271 Nov 16 10:58 /usr/local/lib/libpcap.so.1.9.0-PRE-GIT
lrwxr-xr-x  1 root  wheel      24 Nov 16 10:58 /usr/local/lib/libpcap.so.1 -> libpcap.so.1.9.0-PRE-GIT
lrwxr-xr-x  1 root  wheel      12 Nov 16 10:58 /usr/local/lib/libpcap.so -> libpcap.so.1
-rw-r--r--  1 root  wheel  958772 Nov 16 10:58 /usr/local/lib/libpcap.a
```
```
$ date
Thu Nov 16 10:59:22 PST 2017
```

`cd ~/bin/tcpdump`
`git clean -Xdf`
 `./configure`
configure worked!!!
```
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.9.0-PRE-GIT
```

**Comment by jungle-boogie** [comment]
So something with `libpcap` being one directory up from `tcpdump` caused this issue.
I don't think I had the problem on freebsd.

**Comment by guyharris** [comment]
> Attached are some makefiles and config files that may assist you:

The tcpdump config.log suggests that `../libpcap/libpcap.a` might not have been `ranlib`bed.  It *should* be `ranlib`bed as part of the build process.

**Comment by jungle-boogie** [comment]
Hi @guyharris,

I will work on that for you.

Question about this:
> the from-source libpcap and tcpdump completely uninstalled;

Would that be deleting the files with rm -rf in the appropriate spots? or something like `make uninstall` in the `libpcap` and `tcpdump` directories?

**Comment by guyharris** [comment]
> Would that be deleting the files with rm -rf in the appropriate spots? or something like `make uninstall` in the `libpcap` and `tcpdump` directories?

It'd be `make uninstall` in the `libpcap` and `tcpdump` directories.

**Comment by jungle-boogie** [comment]
No problems encountered with both `libpcap` and `tcpdump` at `~/bin`.
