### ISSUE TITLE
Wrong interpretation regarding DNS traffic encrypted by DNSCrypt v1 on port 443 with UDP

### ISSUE THREAD

**Issue by Ricky-Tigg** [the-tcpdump-group/tcpdump#662]
[ethernet_dnscrypt_udp_443.cap.gz](https://github.com/the-tcpdump-group/tcpdump/files/1759523/ethernet_dnscrypt_udp_443.cap.gz)

Wrong interpretation related to the most specific dissector regarding DNS traffic encrypted by DNScrypt. In both cases output related to info-column with respective filters 'quic' state systematically "Malformed packet". cpdumpfails globally to recognized any No algorithm related to encryption.(capture sample as attachment)

Test-case: Traffic has to be captured on interface Ethernet,.UDP on port 443., which makes sense since in my DNScrypt configuration the DNScrypt built-in cache service is used, and therefore capturing from the loopback interface (IPv4 and IPv6 addresses respectively 127.0.0.1 and :1) shoes as expected a non-encrypted DNS traffic in which traffic does not quit the loopback interface (indeed the client asks from itself regarding cached DNS entries).

In Fedora distribution of Linux, file /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv, contains Tier 2 DNS resolvers that support DNScrypt; Among them a few do not keep logs and are DNSSEC enabled. For the test purpose I choose resolver named dnscrypt.eu-dk, whose server specifications are in .csv format:

"dnscrypt.eu-dk,DNSCrypt.eu Denmark,"Free, non-logged, uncensored. Hosted by Netgroup.",Denmark,,https://dnscrypt.eu,1,yes,yes,no,77.66.84.233,2.dnscrypt-cert.resolver2.dnscrypt.eu,3748:5585:E3B9:D088:FD25:AD36:B037:01F5:520C:D648:9E9A:DD52:1457:4955:9F0A:9955,pubkey.resolver2.dnscrypt.eu" 

where '1,yes,yes' stands respectively for DNSCrypt protocol version, DNSSEC validation, no logs.

Empty both computer's buffer and your favourite web browser caches before running any captures. For desired results of sample captures, visit only site page at https://www.dnsleaktest.com/ then click on 'Standard test' button. Run Tcpdump  before visiting the page and close the page before ending the captures.

As noticeable Tcpdump capture makes no mention regarding above mentioned characteristics .
Tcpdump misinterprets traffic analysed in such a way that it recognized the DNSCrypt as QUICr for the captured data. Indeed QUIC does run over UDP,  therefore QUIC packets are classic UDP packets. Nevertheless traffic is DNS encrypted.

**Comment by guyharris** [comment]
> Tcpdump misinterprets traffic analysed in such a way that it recognized the DNSCrypt as QUICr for the captured data. 

No, it doesn't; tcpdump doesn't recognize QUIC or DNSCrypt, so it just shows the packets as UDP.  Did you try having tcpdump read the file, or did you just *assume* that tcpdump would dissect it as QUIC because Wireshark does?
