### ISSUE TITLE
BPF for 'stp' no longer works

### ISSUE THREAD

**Issue by boisgada** [the-tcpdump-group/tcpdump#665]
I'm not sure when it stopped working, but I have pcap files from Dec 2017 and it was still working then.

`tcpdump --version`
tcpdump version 4.9.0
libpcap version 1.6.2
OpenSSL 1.0.1t  3 May 2016

`tcpdump stp`
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
13 packets dropped by interface

`tcpdump |grep STP`
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:19:11.123701 STP 802.1w, Rapid STP, Flags [Learn, Forward], bridge-id [intentionally removed], length 42
14:19:12.160293 STP 802.1w, Rapid STP, Flags [Learn, Forward], bridge-id [intentionally removed], length 42
14:19:13.134527 STP 802.1w, Rapid STP, Flags [Learn, Forward], bridge-id [intentionally removed], length 42
14:19:14.173158 STP 802.1w, Rapid STP, Flags [Learn, Forward], bridge-id [intentionally removed], length 42
14:19:15.164322 STP 802.1w, Rapid STP, Flags [Learn, Forward], bridge-id [intentionally removed], length 42
^C283 packets captured
297 packets received by filter
0 packets dropped by kernel
3 packets dropped by interface

`uname -a`
Linux ntfk0004 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

**Comment by guyharris** [comment]
That would be a libpcap issue, not a tcpdump issue; the BPF code generation is done by libpcap.  Please re-file this as a libpcap issue.
