### ISSUE TITLE
Interpreting test feedback [00008b00]

### ISSUE THREAD

**Issue by TimJSwan89** [the-tcpdump-group/tcpdump#666]
I am using a custom compiler in a situation where I can build and run the project with almost all tests passing with `gcc` as a default compiler and with the build successfully completing with my custom compiler. So it may be likely that much of my system information is irrelevant to the particular help that I need. It may mainly be in interpreting and using the feedback information.

```
Failed test: juniper_atm1

1,2c1
< Out 
<     Juniper PCAP Flags [none]ATM1-PIC, cookie-len 4, cookie 0x30303030: [|juniper_hdr], length 808464432
---
> EXIT CODE 00008b00
```

Almost every test seems to report this diff, which has `00008b00` and is reported as `: TEST FAILED(exit 256)` I've read places that the 256 is simply a programming language interpretation of an original `1` code, which is not interesting here since there are 2 tests which fail with `gcc` with that code.
`00008b00` hex is `35584` decimal 
I'm not sure where that is coming from

`tests/TESTrun.sh` calls `TESTonce` which tells `system` to call `tcpdump`
```
    $r = system "../tcpdump 2>/dev/null -n -t -r $input $options >NEW/$output";
    if($r != 0) {
        # this means tcpdump failed.
        open(OUTPUT, ">>"."NEW/$output") || die "fail to open $output\n";
        printf OUTPUT "EXIT CODE %08x\n", $r;
```
From there, I suppose `tcpdump.c` `main()`, but I'm not sure what I'm looking for. I guess without help I would begin adding printf statements into the source code and attempt to isolate further.

Update:
My compiler may simply have an issue with `variadic arguments`  since running `../tcpdump -n -r ./isup.pcap` from `tcpdump/tests/` gives `Failed to execute native function pcap_loop successfully. Reason: Variadic arguments in function pointer.`
`libpcap/pcap.c: int pcap_loop(pcap_t *p, int cnt, pcap_handler callback, u_char *user)`

**Comment by mcr** [comment]
On Unix/Linux,  existing with code >=256 usually means that it core dumped.
What does your custom compile produce code for?

>   Almost every test seems to report this diff, which has 00008b00 and is
>   reported as : TEST FAILED(exit 256) I've read places that the 256 is
>   simply a programming language interpretation of an original 1 code,

I don't think that at all correct.
256 is byte-swap of 1, in a 16-bit integer. That's true.

>   which is not interesting here since there are 2 tests which fail with
>   gcc with that code.

That shouldn't be the case.

**Comment by guyharris** [comment]
> 00008b00 hex is 35584 decimal

And is (0200 | SIGSEGV) << 8, i.e. it's probably saying "Segmentation violation - core dumped".

> My compiler may simply have an issue with variadic arguments

What compiler is that?

> Failed to execute native function pcap_loop successfully. 

"native"?  What is the alternative to "native" here?

>     Reason: Variadic arguments in function pointer.
>     libpcap/pcap.c: int pcap_loop(pcap_t *p, int cnt, pcap_handler callback, u_char *user)

I'm not seeing what's variadic there....
