### ISSUE TITLE
Color support: WIP with code+screenshots

### ISSUE THREAD

**Issue by ryandoyle** [the-tcpdump-group/tcpdump#686]
Hi there , I sent this through to the tcpdump-workers mailing list a bit over a week ago but I never received it on the mailing list myself so it may not have gone through. Are Github issues the preferred method of collaboration or are the mailing lists still the way to go?

Anyhow, this is the email I sent. I'm keen to open up a discussion!

---
Hi there

I have started to implement color/colour support in tcpdump and wanted to get some feedback before I continue. It was mentioned in http://seclists.org/tcpdump/2012/q2/25 a few years back but can't find mentions since. Is this still something that is wanted in tcpdump? 

COLOR IMPLEMENTATION
=================
I have used ANSI escape codes for coloring and have used the 4bit pallet, having "bright/bold" as well.

APPLYING COLORS
============
I have created two helper macros like the ND_PRINT(...) macro. These are ND_PRINT_CATEGORY(category, ...) which will print the ANSI escape code, printf and then reset the terminal back to its normal color.

Also, there is a ND_PAINT_CATEGORY_START(category) and ND_PAINT_CATEGORY_END macros that set the ANSI escape code so existing code can be "painted" in a color without modifying all the ND_PRINT usages to ND_PRINT_CATEGORY. I'm still unsure if this is a good idea.

COLORS
======
I've tried to not tie the idea of color to the printing and instead defined different categories. At the moment I have:

- CATEGORY_TIMESTAMP (green bold): This helps to visually break up between packets. For me, the bright green is quite prominent so I can easily see any line breaks that might happen when printing.

- CATEGORY_PROTO_NAME, (green): Protocol names. EG: IP, IP6, ARP, STP

- CATEGORY_ENDPOINT, (cyan): Any info that is printed that denotes the source and destination of the packet. It could be IP/port pairs, or plain IP addresses or MAC addresses in the case of Ethernet.

- CATEGORY_PROTO_ENCAP_PRIMARY, (magenta bold): Used for important data in any protocols that encapsulate other protocols. EG: In the case of ICMP, it would be IP. In the case of HTTP, it would be IP _and_ TCP. 

- CATEGORY_PROTO_ENCAP_SECONDARY, (magenta): Same as above but used for things like label names.

- CATEGORY_PROTO_CHAT_PRIMARY (yellow bold): The highest layer and most important part of the packet. EG: In HTTP, "GET /something" would be highlighted in this color. For ARP, this would be the IP/MAC addresses that were queried for and responded to. 

- CATEGORY_PROTO_CHAT_SECONDARY (yellow): Secondary info, perhaps the human-readable name. EG: It could be a HTTP header name, or the name of a field.

- CATEGORY_PROTO_ERROR (red): Application-specific errors. EG: Incorrect checksums, HTTP 500 response codes.

- CATEGORY_TCPDUMP_ERROR (red bold): Packet decoding errors. I'm not sure where this will be used yet.

I've chosen colors that aim to work on both light and dark terminals. I'm not sure if these colors have issues with people with color-blindness so it would be good to validate that too.

APPLYING TO EXISTING CODE
==========
_New section, not part of the initial email._

The most time consuming part is applying coloring to existing code. I wonder what is preferred here. Is it better to fully support simpler coloring rules across _all_ protocols at once or apply more complex coloring protocol-by-protocol. Maybe just the timestamp and protocol name coloring is good to start off with?

DEMO
====
You can see the code at:
- https://github.com/ryandoyle/tcpdump/tree/color-demo. The branch is "color-demo"

Screen-shots so far are:
- https://github.com/ryandoyle/tcpdump/blob/color-demo/demo1.png
- https://github.com/ryandoyle/tcpdump/blob/color-demo/demo2.png
- https://github.com/ryandoyle/tcpdump/blob/color-demo/demo3.png
- https://github.com/ryandoyle/tcpdump/blob/color-demo/demo4.png

Feedback so far is much appreciated. I think I've optimised coloring to be general purpose but others may use tcpdump in many different ways. I'm keen to hear all the ways that people use it to determine the most general-purpose context where highlighting is useful. Maybe there is too much coloring? Maybe the implementation could be changed? 

Cheers,
Ryan

**Comment by gvanem** [comment]
> ... which will print the ANSI escape code

I've done a similar patch here on Windows. No ANSI-codes, yuk! But I've also modified `ND_PRINT()` like so:
```diff
--- a/netdissect.h 2018-05-23 18:29:39
+++ b/netdissect.h 2018-05-23 18:32:54
 extern int32_t thiszone;	/* seconds offset from gmt to local time */
 /* invalid string to print '(invalid)' for malformed or corrupted packets */
 extern const char istr[];
@@ -223,6 +227,9 @@
   void (*ndo_warning)(netdissect_options *,
 		      const char *fmt, ...)
 		      PRINTFLIKE_FUNCPTR(2, 3);
+
+  const char *printf_func;  /* Effective on _WIN32 only */
+  int ndo_color_flag;       /* Effective on _WIN32 only */
 };

 #define PT_VAT		1	/* Visual Audio Tool */
@@ -323,7 +330,11 @@
 /* Bail out if "*(p)" was not captured */
 #define ND_TCHECK_SIZE(p) ND_TCHECK_LEN(p, sizeof(*(p)))

-#define ND_PRINT(...) (ndo->ndo_printf)(ndo, __VA_ARGS__)
+#define ND_FLUSH()    fflush(stdout)
+
+#define ND_PRINT(...) ( ndo->printf_func = __FUNCTION__, \
+                        (ndo->ndo_printf)(ndo, __VA_ARGS__) )
+
 #define ND_DEFAULTPRINT(ap, length) (*ndo->ndo_default_print)(ndo, ap, length)

--- a/print.c 2018-06-05 11:06:44
+++ b/print.c 2018-06-05 11:15:14
@@ -509,6 +509,11 @@
 	int ret;

 	va_start(args, fmt);
+#ifdef _WIN32
+	if (ndo->ndo_color_flag)
+		ret = vcprintf (ndo, fmt, args);
+	else
+#endif
 	ret = vfprintf(stdout, fmt, args);
 	va_end(args);
```
Where I use the function-name set in `ndo->printf_func`  as an *index* of what colour to use at that point. E.g. in my `vcprintf()` (when `windump --colour` was used), if the `__FUNCTION__` was `"ip_print"`, it will give this output:
![windump-color-1](https://user-images.githubusercontent.com/945271/41653210-a1955b8e-7485-11e8-8cdf-84e789e9d0d1.png)

And if the `__FUNCTION__` was `"syslog_print"`, it will be printed in magenta.

It would be nice with colour; it tells so much more.

**Comment by gvanem** [comment]
I've looked a bit more at your *color-demo* branch. 
You use hard-coded ANSI-codes. how will these colours look with e.g. a blue terminal background? 
(there could perhaps be a `~/tcpdump.cfg` file for these colour settings).

Would it make more sense to use `CATEGORY_x` as enum-values and have a:
```c
static int
ndo_printf_color(netdissect_options *ndo, enum category c, const char *fmt, ...)
{
  va_list args;
  int ret;

  va_start(args, fmt);

#ifdef _WIN32
  if (ndo->ndo_use_color) {
    fflush(stdout);
    set_color(lookup_category_color(c));
  }
  ret = vfprintf(stdout, fmt, args);
  if (ndo->ndo_use_color) {
    fflush(stdout);
    set_color(0);
  }
#else
  const char *ansi_code;

  if (ndo->ndo_use_color)
    fprintf(stdout, lookup_category_color(c));
  ret = vfprintf(stdout, fmt, args);
  if (ndo->ndo_use_color)
    fprintf(stdout, "\x1b[0m");
#endif
  va_end(args);
  return (ret);
}
```

**Comment by mcr** [comment]
Ryan Doyle <notifications@github.com> wrote:
    > Hi there , I sent this through to the tcpdump-workers mailing list a bit over
    > a week ago but I never received it on the mailing list myself so it may not
    > have gone through. Are Github issues the preferred method of collaboration or
    > are the mailing lists still the way to go?

Contributions need to go to github.
Github issues relating small problems, or how to use APIs are welcome.

Bigger questions about how to design something, are best done on the ML.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by ryandoyle** [comment]
Thanks for the feedback.

@gvanem, yeah you're right an enum would be the way to go. It would give better flexibility in terms of changing the colors at runtime and also give support to windows . Also, I like the idea of having a "printer" function pointer. I think that would work well with what @mcr was talking about on the mailing list. Oh and for what its worth, newer versions of Windows 10 support ANSI escape characters now: https://en.wikipedia.org/wiki/ANSI_escape_code#Windows. That might make your patch easier if you're using W10.

@mcr, thanks for your reply on the mailing list too. I'll reply directly on the mailing list for further discussion.

**Comment by gvanem** [comment]
@ryandoyle I know Win-10 now supports ANSI-sequences in the console. But it's so 1980 to use those sequences directly IMHO.

**Comment by guyharris** [comment]
>  But it's so 1980 to use those sequences directly IMHO.

[Termcap apparently dates back to 1978](http://landley.net/history/mirror/unix/art3.htm), so if that's what you're referring to, that's not even 1980.

Unfortunately, [it appears that neither termcap nor terminfo can handle the color escape sequences, at least not for true color](https://stackoverflow.com/questions/36158093/terminal-color-using-terminfo).
