### ISSUE TITLE
tcpdump-4.x randomly stop writing file

### ISSUE THREAD

**Issue by gavinux** [the-tcpdump-group/tcpdump#696]
it randomly stop writing file while the process is alive.
Linux version 2.6.31 - armv5
[tcpdump-4.9.2.make.zip](https://github.com/the-tcpdump-group/tcpdump/files/2274845/tcpdump-4.9.2.make.zip)

it has been found in 4.2.1 and 4.9.3, but I believe all 4.x have this issue
3.9.3 has been tested and works fine.
We have unlimited size for /var/log
BTW, last log from 4.x has been cut.

Linux-192.168.1.100#
iperf -s -u -i 1 -p 5012 -t 345600 &
Linux-192.168.1.101#
/usr/local/sbin/tcpdump -ni wlan0 -s 1600 -w /var/log/wlan0.pcap -C 256 -W 64 &
/usr/local/sbin/tcpdump -ni eth1  -s 1600 -w /var/log/eth1.pcap  -C $256 -W 64 &
iperf -c 192.168.1.100 -u -d -l 800 -b 128k -i 1 -p 5012 -t 345600 &

![untitled](https://user-images.githubusercontent.com/42246223/43909494-784e621a-9bc8-11e8-81bd-18a4da5cc75a.png)
![untitled1](https://user-images.githubusercontent.com/42246223/43909495-78607cca-9bc8-11e8-97bb-a9d0f5ad2d07.png)

![2018_08_09_11_41_21_wireshark](https://user-images.githubusercontent.com/42246223/43909865-552640d6-9bc9-11e8-9d61-d02e56a1469d.png)

![tcpdump-3 9 3](https://user-images.githubusercontent.com/42246223/43909642-d4c6a584-9bc8-11e8-945f-45507431bd2e.png)

**Comment by gvanem** [comment]
You're capturing in round-robin fashion until `MRU*wlan*.pcap02` get overwritten again by another 256.000.000 byte file. But it's only ~74.000.000 bytes. Did you stop the capture somehow (it looks to be the last)? Or it stopped when something happened with the `wlan` driver?

You attached a tcpdump.diff with some odd patches. Could be those if you use them in this tcpdump.

**Comment by gavinux** [comment]
I was running multiple-day test to verify tcpdump can write files reliably.
I made the patch to support write files over 2GB. I don’t think anything wrong with my patch.

The pcap02 stopped by some reason, and the last packet is trimmed. Although it is round-robin fashion, but I passed 64 as parameter, It shouldn’t stop at 02.

Based on my understanding of the code, it seems like the function dump_packet_and_trunc() is not called, otherwise it should write file.
I had tested multiple times, and tcpdump randomly stops writing file.
I also tested with 3.9.3, which has never stopped.

Regards,
YLi

**Comment by gavinux** [comment]
tested 3.9.3 and 4.9.2 to log files to USB again over this weekend. 
3.9.3 has logged 256MB*29 files and still logging but 4.9.2 stopped at about ~300MBytes file size.

**Comment by davemq** [comment]
Is the file system you're using running out of space?

**Comment by gavinux** [comment]
No, they still have lots of space.
The two test units are identical, I have  8GB USB thumb drive on each device.


________________________________

WARNING: This message is intended only for the named recipients. This message may contain information that is confidential. Any dissemination, copying, or use of this message or its contents by anyone other than the named recipient is strictly prohibited. If you are not a named recipient or an employee or agent responsible for delivering this message to a named recipient, please notify the sender immediately, and immediately destroy this message and any copies you may have. WARNING: Email may not be secure unless properly encrypted. It is possible for e-mails to be intercepted or affected by viruses. While we maintain virus checks on all e-mails, we accept no liability for viruses or other material introduced with this message.

**Comment by mcr** [comment]
Can you confirm that files are not being overwritten in the round-robin?  Please re-open.
If you are writing 256M files, then you don't need a 2GB hack, and I thought we already had >2GB support.
