### ISSUE TITLE
illegal link layer address

### ISSUE THREAD

**Issue by LucaKern** [the-tcpdump-group/tcpdump#724]
When I try to run:
> sudo tcpdump "type mgt subtype beacon and ether src $BSSID" -I -c 1 -i en0 -w beacon.cap

I get the following error:` tcpdump: illegal link layer address`

Does anybody know what could be the problem? Thanks

**Comment by guyharris** [comment]
To what value is the shell variable `BSSID` set?  I infer from "en0" that this is macOS, hence a UN\*X, so this is probably a UN\*X shell; as the filter expression is in double-quotes, shell variables in it should be expanded, so the filter being passed to tcpdump has the value of that variable expanded.

**Comment by LucaKern** [comment]
Thanks a lot for your help! It works when the variable is expanded. My bad!
