### ISSUE TITLE
Can't set snaplen > 80 at usbmon interface

### ISSUE THREAD

**Issue by imShara** [the-tcpdump-group/tcpdump#725]
I'm trying to capture data between Android device and printer with tcpdump. And I can't capture whole packages even with `-s 0` option. Buffer parameter (`-B`) and `-p` not helps too. Whole command `tcpdump -i usbmon2 -s 0 -w capture.pcap`.

- I can set snaplen less than 80 (e.g 60) and it works
- I can set snaplen more than 80 on other interface (e.g wlan0 instead usbmon2)

Where to dig this problem?

> Linux localhost 3.10.108
> tcpdump492 version 4.9.2
> libpcap version 1.8.1

**Comment by guyharris** [comment]
What does the command

    udevinfo -q name -p /sys/class/usb_device/usbmon

print?

**Comment by imShara** [comment]
@guyharris, sorry, I have no udevinfo/udevadm on android

**Comment by mcr** [comment]
I think that point was that we don't know what the usbmon2 interface, or whether it even supports full captures.

**Comment by infrastation** [comment]
Not possible to progress without the reporter feedback, closing.

**Comment by guyharris** [comment]
Yes, this might just be Android, for whatever reason, not offering the binary capture interface, just the text capture interface, which limits the amount of packet data it provides.

**Comment by many-sigsegv** [comment]
> Yes, this might just be Android, for whatever reason, not offering the binary capture interface, just the text capture interface, which limits the amount of packet data it provides.

(old issue but answer may be useful anyway)
I managed to enable binary capture interface by using
```
mknod /dev/usbmon0 c 239 0
mknod /dev/usbmon1 c 239 1
mknod /dev/usbmon2 c 239 2
...
```
in adb shell and restarting tcpdump.
Tested on Android 8.1
