### ISSUE TITLE
[Help]which version support to dump vlan tag

### ISSUE THREAD

**Issue by benzhang1986** [the-tcpdump-group/tcpdump#726]
Hi, I can not dump vlan tag with tcpdump of old versions: 
tcpdump version 3.9.8
libpcap version 0.8

but I can dump vlan tag with tcpdump 4.9.2 and libpcap 1.9.0.

can you tell me which version of tcpdump and libpcap that begin to support vlan dump, it's important for me. 

Thank your very much.

**Comment by mcr** [comment]
It depends upon system and kernel versions. I assume linux.
AFAIK, the VLAN tag is in different place in some Linux kernel capture
mechanisms, and that's why you likely need a modern libpcap.
Do you really have 0.8 (the ABI version of libpcap has been is 0.8 for a long
time).   Why is upgrading a problem?
tcpdump 3.x is decades old, and has many security issues.

**Comment by guyharris** [comment]
> Do you really have 0.8 (the ABI version of libpcap has been is 0.8 for a long time). Why is upgrading a problem?

I.e., what does `tcpdump -%` print?  (That's the only way to get the version information on older versions of tcpdump; newer versions support `--version`.)

**Comment by guyharris** [comment]
> It depends upon system and kernel versions. I assume linux. AFAIK, the VLAN tag is in different place in some Linux kernel capture mechanisms, and that's why you likely need a modern libpcap.`

At least in newer versions of the Linux kernel, VLAN packets have the VLAN tags stripped off, with the tag information supplied as metadata to the capture mechanism (PF_PACKET sockets).  Newer versions of libpcap attempt to put the tag back into the packet, so you see the packet as it appeared on the network; older versions of libpcap don't.

**Comment by benzhang1986** [comment]
> > Do you really have 0.8 (the ABI version of libpcap has been is 0.8 for a long time). Why is upgrading a problem?
> 
> I.e., what does `tcpdump -%` print? (That's the only way to get the version information on older versions of tcpdump; newer versions support `--version`.)

![image](https://user-images.githubusercontent.com/15809856/51099728-5a4abe00-180d-11e9-9d74-f0bcc3b91695.png)

**Comment by benzhang1986** [comment]
> > It depends upon system and kernel versions. I assume linux. AFAIK, the VLAN tag is in different place in some Linux kernel capture mechanisms, and that's why you likely need a modern libpcap.`
> 
> At least in newer versions of the Linux kernel, VLAN packets have the VLAN tags stripped off, with the tag information supplied as metadata to the capture mechanism (PF_PACKET sockets). Newer versions of libpcap attempt to put the tag back into the packet, so you see the packet as it appeared on the network; older versions of libpcap don't.

I'm using a old version of linux, 3.10.0:
![image](https://user-images.githubusercontent.com/15809856/51099825-e65ce580-180d-11e9-936a-bbe542699163.png)

**Comment by guyharris** [comment]
What version of what Linux distribution is this?

**Comment by guyharris** [comment]
So where did you get the userland?

In particular, where did you get the tcpdump and libpcap you were using?

**Comment by benzhang1986** [comment]
Someone build them from source code a few years ago.

**Comment by mcr** [comment]
And, since it sounds like it's an embedded system, *PLEASE* make sure you
can upgrade it in the field.

**Comment by benzhang1986** [comment]
Thank you very much, I rebuild tcpdump 4.9.2 and libpcap 1.9.0, I can dump vlan tag now. Thanks.
