### ISSUE TITLE
DNS: wrong error code nemonic printed.

### ISSUE THREAD

**Issue by marka63** [the-tcpdump-group/tcpdump#738]
With EDNS the DNS error code is split over two locations with the lower bits in the DNS header and the upper bits in the OPT record.   Decoding just the bits in the DNS header results in the wrong nemonic being printed.

**Comment by marka63** [comment]
See https://github.com/the-tcpdump-group/tcpdump/pull/733

**Comment by infrastation** [comment]
The associated pull request had been merged 2.5 years ago, closing the issue.
