### ISSUE TITLE
setup make extracheck

### ISSUE THREAD

**Issue by mcr** [the-tcpdump-group/tcpdump#740]
extracheck will compile libpcap and tcpdump with a number of different compilers (in separate build directories), with different options, and then run through a complex of options with a menagerie of pcap input files.  The goal is to set off various run-time warnings that compilers like clang offer.  
This will require a specially setup build environment with particular things installed, and would warrant having a docker and/or AMI image on which to run things against.

**Comment by fxlb** [comment]
I like the idea to use Docker.

**Comment by guyharris** [comment]
> The goal is to set off various run-time warnings that compilers like clang offer.

I.e., the sanitizers?

**Comment by fxlb** [comment]
`-fsanitize=address`, `-fsanitize=undefined` and `-fsanitize=integer` are good candidate.  Perhaps others to look at.

**Comment by mcr** [comment]
Apparently one can import docker images into travis (ruby-openssl does exactly this).  I'm not sure we want to do this on every commit though.  I'm not sure if there are ways to do things on demand.

**Comment by fxlb** [comment]
Based on a specific branch name, like `extracheck`, pushed when needed ?

**Comment by fxlb** [comment]
PcapPlusPlus also uses Docker for testing in ubuntu1404, ubuntu1604, ubuntu1804, centos7, fedora29, etc.

**Comment by infrastation** [comment]
Alright, so who volunteers to work on this setup?

**Comment by infrastation** [comment]
Francois-Xavier has implemented this idea, closing.
