### ISSUE TITLE
Feature request: allow integers in -y

### ISSUE THREAD

**Issue by gpotter2** [the-tcpdump-group/tcpdump#758]
Hello,

It would be great if the `-y` option (data link type) could also accept the integer values of the DLT types.

It would require a small change in https://github.com/the-tcpdump-group/tcpdump/blob/c36abfe8a86fb2e3d8256fa53d6569a4aa65b39c/tcpdump.c#L1823-L1829

We play around with the numeric values of the datalinks in Scapy, (therefore [we don't support `-y` ATM](https://github.com/secdev/scapy/blob/6dde6ae78bc0cc3a577035d7469c2806e97160e8/scapy/utils.py#L1514-L1516)) as we use them to write pcaps, therefore it would make it easier for us to call tcpdump.

**Comment by guyharris** [comment]
You can use `pcap_datalink_val_to_name()` to translate a numerical value to a name, if either 1) you're writing your own Python wrapper for libpcap or 2) whatever wrapper you're using provides it.

**Comment by gpotter2** [comment]
Thanks for the tip.

It however remains pretty inefficient (as tcpdump then reverse the call), and hardly applicable in our case (for reasons I won't bother you with, but basically the wrappers are optional but tcpdump isn't for some functions)

I have a workaround for now. If this feature is a wontfix, feel free to close the issue :smile:

Thanks for your work on tcpdump & libpcap !
