### ISSUE TITLE
Minor issue showing 4294965006 packets dropped by interface

### ISSUE THREAD

**Issue by dmigowski** [the-tcpdump-group/tcpdump#787]
Hello,
just started a tcp dump and immediately killed it afterwards with CTRL-C. It displays an absurd number of packets dropped. Couldn't reproduce, so it just might be a race condition somewhere.

```
JAVAERP-vtestserver:~#   tcpdump -i eth0  -s 256000 -w smb.pcap port 445
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 256000 bytes
^C0 packets captured
0 packets received by filter
0 packets dropped by kernel
4294965006 packets dropped by interface
```
^^ How many packets dropped????

Version is:
```
tcpdump version 4.9.2
libpcap version 1.6.2
OpenSSL 1.0.1t  3 May 2016
```

**Comment by gvanem** [comment]
A recent `tcpdump.c` (in `info()`) has this:
```c
	/*
	 * Older versions of libpcap didn't set ps_ifdrop on some
	 * platforms; initialize it to 0 to handle that.
	 */
	stats.ps_ifdrop = 0;
```

Your tcpdump probably does not have that clearing. 

Does your libpcap use `pcap-pf.c`?

**Comment by dmigowski** [comment]
Sorry, I don't know, I just use the package from current Debian Lenny.

**Comment by guyharris** [comment]
> Does your libpcap use `pcap-pf.c`?

Not unless it's built for --DEC OSF/1-- --Digital UNIX-- Tru64 UNIX, which it isn't - it's running on Linux, so it's built for Linux and using `pcap-linux.c`.

**Comment by ValZapod** [comment]
@dmigowski Very old version. My kali has 
```
root@kali:~# tcpdump -V
tcpdump: option requires an argument -- 'V'
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by infrastation** [comment]
This may be a bug, but it is difficult to tell from the description. If the problem still stands, please see the file `CONTRIBUTING` in the source tree root and follow the bug reporting steps. If this issue does not progress for whatever reason, it will be closed.

**Comment by infrastation** [comment]
So be it.
