### ISSUE TITLE
tcpdump net filter shows error if last octet is not 0

### ISSUE THREAD

**Issue by suchAdemon** [the-tcpdump-group/tcpdump#790]
Hello,
I found out that if I am perform like:
tcpdump net 192.168.10.188/30
or
tcpdump net 192.168.10.188 mask 255.255.255.252

I am always getting this output:
tcpdump: non-network bits set in "192.168.10.188/30"
tcpdump: non-network bits set in "192.168.10.188 mask 255.255.255.252"

But, if I replace the last octet with a 0 its working
tcpdump net 192.168.10.0/30

So if you want to dump just a small range of a network or subnet you have to use a bigger one and than pipe it to grep to remove all the unwanted information.

Would it be possible to not limit the last octet to 0 so that all ranges could be used?

I tested this on Debian 8,9,10,11

Debian 8:
tcpdump version 4.9.2
libpcap version 1.6.2

Debian 9:
tcpdump version 4.9.2
libpcap version 1.8.1

Debain 10:
tcpdump version 4.9.2
libpcap version 1.8.1

Debian 11:
tcpdump --version 
tcpdump version 4.9.2
libpcap version 1.9.0 (with TPACKET_V3)

**Comment by mcr** [comment]
Oliver Schraml <notifications@github.com> wrote:
    > Hello, I found out that if I am perform like: tcpdump net
    > 192.168.10.188/30 or tcpdump net 192.168.10.188 mask 255.255.255.252

    > I am always getting this output: tcpdump: non-network bits set in
    > "192.168.10.188/30" tcpdump: non-network bits set in "192.168.10.188
    > mask 255.255.255.252"

    > But, if I replace the last octet with a 0 its working tcpdump net
    > 192.168.10.0/30

Yes, I agree. There is a bit of a religious issue among some people who think
that you should know better than to not set the right bits to zero.
I don't agree myself, and would welcome a patch to fix this.

It would, I think, be in libpcap.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by infrastation** [comment]
This warning is not expected for the input you quote, please mind that 188 is a multiple of 4:
```
$ tcpdump -n -r tcpdump-master/tests/bgp-aigp-oobr.pcap net 192.168.10.188/30
reading from file tcpdump-master/tests/bgp-aigp-oobr.pcap, link-type EN10MB (Ethernet)
$ tcpdump -n -r tcpdump-master/tests/bgp-aigp-oobr.pcap net 192.168.10.189/30
reading from file tcpdump-master/tests/bgp-aigp-oobr.pcap, link-type EN10MB (Ethernet)
tcpdump: non-network bits set in "192.168.10.189/30"
$ tcpdump --version
tcpdump version 4.9.2
libpcap version 1.8.1
OpenSSL 1.1.1  11 Sep 2018
```
Could you double-check?

**Comment by infrastation** [comment]
The original problem statement does not match the actual behaviour, closing.
