### ISSUE TITLE
Missing packets and 30% of traffic marked with Bad TCP

### ISSUE THREAD

**Issue by jmakov** [the-tcpdump-group/tcpdump#793]
PROBLEM:
Running `tcpdump -p -n -B 10000 -C 50 -i enp111s0 -w /tmp/test.pcap -f "tcp[20:4]=0x383D4649 and tcp[24:1]=0x58"` with the output:
```
tcpdump: listening on enp111s0, link-type EN10MB (Ethernet), capture size 262144 bytes 
^C1451 packets captured 
1451 packets received by filter  
0 packets dropped by kernel  
```
results in:
1. 30% of captured traffic marked with Bad TCP ("TCP ACKed unseen segment", "TCP Previous segment not captured")
2. Missing packets in pcap file (although tcpdump reports `0 packets dropped` there are gaps in FIX messages (which include MsgSeqNum field). Using a FIX library in a separate program we see all the messages.

COMMENT:
Using `-f "host FIX_server_host"` results in the same tcpdump output as above with only one packet marked with Bad TCP (in the first 2s of captured traffic) and no packets missing. Same tcpdump settings, recorded to a M.2 disk.

DETAILS:
We're running a program that communicates via the [FIX protocol](https://en.wikipedia.org/wiki/Financial_Information_eXchange). We'd like to capture all the FIX traffic for later analysis.
Filtering for FIX protocol (with the `-f "tcp[20:4]=0x383D4649 and tcp[24:1]=0x58"` filter) produces a pcap file which when read with Wireshark (version 2.6.8) flags 30% (when recording to RAM) or 97% (recording to a M.2 disk) of recorded traffic with Bad TCP. Also some packets are simply missing. We know that because:
1. FIX protocol sends messages that include sequential numbers (`MsgSeqNum` field in a FIX message). In the pcap file we see in a packet e.g. `MsgSegNum=10`. The next packet (marked with Bad TCP) has e.g. `MsgSeqNum=47` (instead of the expected `MsgSeqNum=11`). There are 30-97% such cases in the pcap file.
2. our program also records all the FIX messages (in and out) and all the messages are present there

OTHER OBSERVATIONS:
When using the `-f "tcp[20:4]=0x383D4649 and tcp[24:1]=0x58"` filter:
* same results with  `-s 1500`
* 97% of traffic marked as Bad TCP when recording to a M.2 disk (on an idle laptop) compared with 30% when recording to RAM
* first 2 seconds of recorded packets include only 1 packet marked as Bad TCP
* from first 2 seconds to 30s 100% packets flagged with Bad TCP, after 30s only occasional packet marked with Bad TCP
* 99% of traffic marked as Bad TCP when recording to RAM with [gulp](https://github.com/jmakov/gulp) using `gulp -i enp111s0 -t -r 100 -C 1 -n test -o /tmp -f "tcp[20:4]=0x383D4649 and tcp[24:1]=0x58"`
* same results (with tcpdump and gulp) with `rx/tx-checksumming: on/off`

VERSION INFO
```
$ uname -a
Linux hostname 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ tcpdump --version
Version: 
tcpdump version 4.9.2
libpcap version 1.8.1
OpenSSL 1.1.1b  26 Feb 2019
```

**Comment by infrastation** [comment]
So, as the CONTRIBUTING puts it, does the problem reproduce on the current master branch of libpcap and tcpdump?
