### ISSUE TITLE
Don't attach to an interface for filter dump

### ISSUE THREAD

**Issue by Oppen** [the-tcpdump-group/tcpdump#804]
If I try to get the output of a compiled filter program with `tcpdump -d $FILTER` without privileges, it fails because it tries to attach to an arbitraty interface and lacks the permissions.
Given this should just be a conversion from input to output, the interface is an unrequited third-party and `tcpdump` shouldn't ask for permission to use it.

**Comment by Oppen** [comment]
Using `pcap_compile_nopcap` may help.

**Comment by fenner** [comment]
> the interface is an unrequited third-party and `tcpdump` shouldn't ask for permission to use it.

This is not completely true. The DLT in use is a required input. It probably makes sense to default to Ethernet, but the resulting program may change depending on what link type is in use.

**Comment by guyharris** [comment]
> Using `pcap_compile_nopcap` may help.

The second argument to `pcap_compile_nopcap()` is a DLT_ value, so you have to supply *something*, as Bill notes.

Currently, tcpdump uses the DLT_ value for the interface being used.

In order for `-d` without an interface to be a generally useful tool, there would need to be a way to specify the DLT_, because, as Bill notes, "the resulting program may change depending on what link type is in use".

Perhaps there should be a new command-line flag that takes a link-layer type name as an argument (with the DLT_ stripped off); if that argument is specified along with `-d`, then 1) no interface will be opened and 2) the specified DLT_ will be used.

**Comment by fenner** [comment]
The `-y` flag already taks a link-layer type name as an argument.  I'm going to push some patches that do this:

```
~/src/tcpdump% ./tcpdump -d -y EN10MB ip proto 42
(000) ldh      [12]
(001) jeq      #0x800           jt 2    jf 5
(002) ldb      [23]
(003) jeq      #0x2a            jt 4    jf 5
(004) ret      #262144
(005) ret      #0
~/src/tcpdump% ./tcpdump -d -y LOOP ip proto 42
(000) ld       [0]
(001) jeq      #0x2             jt 2    jf 5
(002) ldb      [13]
(003) jeq      #0x2a            jt 4    jf 5
(004) ret      #262144
(005) ret      #0
```

but the `-y` argument is still required in this scenario to avoid the error message.  I don't know if that's enough for Oppen.

**Comment by mcr** [comment]
fenner <notifications@github.com> wrote:
    > The `-y` flag already taks a link-layer type name as an argument.  I'm going to push some patches that do this:

    > ```
    > ~/src/tcpdump% ./tcpdump -d -y EN10MB ip proto 42

Bigger question: should /usr/bin/tcpdump even be about translating pcap
notation to BPF?  Maybe this should be added to the libpcap utilities, and
could form the beginning of pcap -> BPF test cases?

    > but the `-y` argument is still required in this scenario to avoid the
    > error message.  I don't know if that's enough for Oppen.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by fenner** [comment]
> fenner wrote:
> > ~/src/tcpdump% ./tcpdump -d -y EN10MB ip proto 42
>
> Bigger question: should /usr/bin/tcpdump even be about translating pcap notation to BPF?

I'd be fine with the idea of having a new tool in libpcap for this.  All the code is in libpcap anyway.

**Comment by guyharris** [comment]
> Bigger question: should /usr/bin/tcpdump even be about translating pcap notation to BPF? Maybe this should be added to the libpcap utilities, and could form the beginning of pcap -> BPF test cases?

There's already `filtertest` in the `testprogs` directory of lib pap:

    $ make testprogs
    $ testprogs/filtertest
    filtertest, with libpcap version 1.10.0-PRE-GIT
    Usage: filtertest [-dO] [ -F file ] [ -m netmask] [ -s snaplen ] dlt [ expression ]
    $ testprogs/filtertest EN10MB ip
    (000) ldh      [12]
    (001) jeq      #0x800           jt 2    jf 3
    (002) ret      #262144
    (003) ret      #0

**Comment by guyharris** [comment]
(`-d`, if you've enabled various bits of libpcap debugging at compile ime, turns debugging on. `-O` turns off the optimizer, just as in tcpdump; `-F` specifies a file containing the filter expression, just as in tcpdump; `-m` and `-s` let you set the netmask and snapshot length arguments to `pcap_open_dead()`.)

**Comment by Oppen** [comment]
> This is not completely true. The DLT in use is a required input. It probably makes sense to default to Ethernet, but the resulting program may change depending on what link type is in use.

This makes sense. Thanks for the info.

> The second argument to `pcap_compile_nopcap()` is a DLT_ value, so you have to supply _something_, as Bill notes.
> 
> Currently, tcpdump uses the DLT_ value for the interface being used.
> 
> In order for `-d` without an interface to be a generally useful tool, there would need to be a way to specify the DLT_, because, as Bill notes, "the resulting program may change depending on what link type is in use".
> 

Maybe defaulting to EN10MB *and* displaying a warning if unspecified would be better?

> Perhaps there should be a new command-line flag that takes a link-layer type name as an argument (with the DLT_ stripped off); if that argument is specified along with `-d`, then 1) no interface will be opened and 2) the specified DLT_ will be used.

Yes, this makes the most sense.

> The `-y` flag already taks a link-layer type name as an argument. I'm going to push some patches that do this:
> 
> ```
> ~/src/tcpdump% ./tcpdump -d -y EN10MB ip proto 42
> (000) ldh      [12]
> (001) jeq      #0x800           jt 2    jf 5
> (002) ldb      [23]
> (003) jeq      #0x2a            jt 4    jf 5
> (004) ret      #262144
> (005) ret      #0
> ~/src/tcpdump% ./tcpdump -d -y LOOP ip proto 42
> (000) ld       [0]
> (001) jeq      #0x2             jt 2    jf 5
> (002) ldb      [13]
> (003) jeq      #0x2a            jt 4    jf 5
> (004) ret      #262144
> (005) ret      #0
> ```
> 
> but the `-y` argument is still required in this scenario to avoid the error message. I don't know if that's enough for Oppen.

That's enough for me, yes.

> > Bigger question: should /usr/bin/tcpdump even be about translating pcap notation to BPF?
> 
> I'd be fine with the idea of having a new tool in libpcap for this. All the code is in libpcap anyway.

I agree.

> > Bigger question: should /usr/bin/tcpdump even be about translating pcap notation to BPF? Maybe this should be added to the libpcap utilities, and could form the beginning of pcap -> BPF test cases?
> 
> There's already `filtertest` in the `testprogs` directory of libpcap:
> 
> ```
> $ make testprogs
> $ testprogs/filtertest
> filtertest, with libpcap version 1.10.0-PRE-GIT
> Usage: filtertest [-dO] [ -F file ] [ -m netmask] [ -s snaplen ] dlt [ expression ]
> $ testprogs/filtertest EN10MB ip
> (000) ldh      [12]
> (001) jeq      #0x800           jt 2    jf 3
> (002) ret      #262144
> (003) ret      #0
> ```

Hmmm. Maybe this could be promoted, then?

**Comment by Oppen** [comment]
Only one thing more: I think this should be documented somewhere. This way, you won't get another Mario asking for this in the future :)

**Comment by guyharris** [comment]
> > the interface is an unrequited third-party and `tcpdump` shouldn't ask for permission to use it.
> 
> This is not completely true. The DLT in use is a required input. It probably makes sense to default to Ethernet, but the resulting program may change depending on what link type is in use.

And, furthermore, at least on Linux, filters using `vlan` will generate *different* code if you're generating it for a live capture than if you're generating it for a savefile or a "dead" `pcap_t`, so the ability to get tcpdump to report the filter code that would be generated for a particular device, for debugging purposes, can be useful.  See, for example, [Wireshark bug 16116](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16116), where that feature - although Wireshark's dumpcap program, rather than tcpdump, was used - came in handy.

**Comment by Oppen** [comment]
> And, furthermore, at least on Linux, filters using `vlan` will generate _different_ code if you're generating it for a live capture than if you're generating it for a savefile or a "dead" `pcap_t`, so the ability to get tcpdump to report the filter code that would be generated for a particular device, for debugging purposes, can be useful. See, for example, [Wireshark bug 16116](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16116), where that feature - although Wireshark's dumpcap program, rather than tcpdump, was used - came in handy.

Right, but having the ability to attach to an interface to dump the code generated specifically for it and making it mandatory are two different things.
Further, if you don't specify one, it's possible that you weren't expecting that, and instead will try to attach to the default one.

**Comment by guyharris** [comment]
> Right, but having the ability to attach to an interface to dump the code generated specifically for it and making it mandatory are two different things.

Yes, I'm just indicating that "-y {DLT} -d" and "-i {interface} -d" both have use cases.

**Comment by Oppen** [comment]
Oh, that makes sense, yeah. Should they be incompatible with one another? I mean, if both are present, either `-y` is redundant or they actually conflict.

**Comment by guyharris** [comment]
"tcpdump -i {interface} -d {filter}" - print the BPF that would generated for {filter} if you're capturing on interface {interface}.

"tcpdump -r {capture file} -d {filter}" - print the BPF that would be generated for {filter} if you're reading file {capture file}.  (Subject to change once we fully support pcapng, where there may be "more than one* set of BPF code; the change may be "sorry, that's pcapng, you *really* don't want me to read the *entire file* looking for Interface Description Blocks and reporting the BPF for each new link-layer type, do you?")

"tcpdump -y {DLT} -d {filter}" - print the BPF that would be generated for reading a pcap file with the appropriate linotype.

"tcpdump -i {interface} -y {DLT} -d {filter}" - either 1) try to make {DLT} the link-layer header type for {interface} and then either report an error or print the BPF for that DLT or 2) say "you can't specify both -i and -y with -d".  I'm inclined to vote for 2).

"tcpdump -d {filter}" - either 1) print the BPF that would generated for {filter} if you're capturing on the default interface or 2) say "you didn't specify an interface or a file or a DLT".

**Comment by fenner** [comment]
Oppen,
> if both (`-i` and `-y`) are present, either -y is redundant or they actually conflict.

Actually this is what `-y` is currently for: e.g., `-i any -y LINUX_SLL2`.

**Comment by guyharris** [comment]
> "tcpdump -i {interface} -y {DLT} -d {filter}" - either 1) try to make {DLT} the link-layer header type for {interface} and then either report an error or print the BPF for that DLT or 2) say "you can't specify both -i and -y with -d". I'm inclined to vote for 2).

And now I'm inclined to vote for 1), instead, given that, as I said earlier, the filter code generated can be different for a live capture.

**Comment by fenner** [comment]
My code in https://github.com/the-tcpdump-group/tcpdump/pull/805 does almost exactly what you mentioned above.  The differences:

"tcpdump -i {interface} -y {DLT} -d {filter}" - try to make {DLT} the link-layer header type for {interface} and then either report an error or print the BPF for that DLT
(This is your 1), which you decided you prefer)

"tcpdump -d {filter}" - print the BPF that would generated for {filter} if you're capturing on an Ethernet interface, with a warning that it's assuming Ethernet

I think there's some useful cleanup to do, like - in the "-r" case it says what DLT it's using; it would be useful info for the other cases too.

**Comment by infrastation** [comment]
Updated the man page to explain the new semantics, closing.
