### ISSUE TITLE
Need to capture packets without the influence of iptables

### ISSUE THREAD

**Issue by Margular** [the-tcpdump-group/tcpdump#809]
I need to capture packets without the influence of iptables. Because I set the DNAT of iptables to cause the inconsistency between the flow IP of in and out when tcpdump grabs packets, so I can't analyze the flow correctly. As shown below, the outlet flow is affected by iptables, but the inlet flow is not affected by iptables. How can I capture packets without the influence of iptables? 

```
10.0.2.15.40322 > 127.0.0.1.8080: Flags [S], seq 2338969149, win 65535, options [mss 1460,sackOK,TS val 1301594 ecr 0,nop,wscale 6], length 0
203.208.40.79.443 > 10.0.2.15.40322: Flags [S.], seq 1312729188, ack 2338969150, win 65535, options [mss 65495,sackOK,TS val 1301594 ecr 1301594,nop,wscale 6], length 0
```

The following is a discussion about the relationship between tcpdump and iptables for reference:
[Does tcpdump bypass iptables?](https://superuser.com/questions/925286/does-tcpdump-bypass-iptables)

**Comment by infrastation** [comment]
Better late than never. It is difficult to tell the topology reliably from the provided example, but as the referenced discussion explains, in Linux tcpdump sees packets just after they arrive from the network card and just before they go into the network card. To have a copy of a packet before iptables modifies it, it **potentially might** help to add a rule with `-j NFLOG` early in iptables and to capture on the receiving end of the tap:
```text
# tcpdump -D
1.eno1 [Up, Running, Connected]
2.any (Pseudo-device that captures on all interfaces) [Up, Running]
3.lo [Up, Running, Loopback]
4.eno2 [Up, Disconnected]
5.nflog (Linux netfilter log (NFLOG) interface) [none]
6.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]

# tcpdump -ni nflog
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on nflog, link-type NFLOG (Linux netfilter log messages), snapshot length 262144 bytes
```

**Comment by infrastation** [comment]
Feel free to reopen if you have other input to make.
