### ISSUE TITLE
ikev2pI2 test failure for ppc64le on openSUSE, tcpdump 4.9.3

### ISSUE THREAD

**Issue by michelmno** [the-tcpdump-group/tcpdump#814]
ikev2pI2 test failure for ppc64le on openSUSE, tcpdump 4.9.3
as per OBS output (1) with extract appended below.

If I do a local trial with current git tree master branch, I have similar failure.

(1) https://build.opensuse.org/package/show/openSUSE:Factory:PowerPC/tcpdump
```
[  103s] Failed test: ikev2pI2
[  103s]
[  103s] 41c41
[  103s] <             (v2auth: len=196 method=rsasig authdata=(000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) ))
[  103s] ---
[  103s] >             (v2auth: len=196 method=rsasig authdata=(0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009d7686de6fabda36c4b374135ccca0c4596fe7636e19ee71ea7d276b4230948ab529651ba1dbec39e85e506ff90b48a57611be386a5867beccde9c9971587907251df58f0c46b473d9f0abc308eb85482f08383d) ))
```
[tcpdump_standard_ppc64le_201912131519.log](https://github.com/the-tcpdump-group/tcpdump/files/3961863/tcpdump_standard_ppc64le_201912131519.log)

**Comment by pmgdeb** [comment]
Also fails in Debian:
   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942171

**Comment by guyharris** [comment]
Try it with the current master branch.

**Comment by michelmno** [comment]
> Try it with the current master branch.

I tried current master branch, the ikev2pl2 test passed, BUT now has 7 other tests failed as per extract of attached log:
```
    brcmtag                                 : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file brcm-tag.pcap, link-type 281, snapshot length 262144
tcpdump: unknown data link type 281
brcmtag-e                               : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file brcm-tag.pcap, link-type 281, snapshot length 262144
tcpdump: unknown data link type 281
    brcmtagprepend                          : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file brcm-tag-prepend.pcap, link-type 282, snapshot length 262144
tcpdump: unknown data link type 282
    dsa                                     : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file dsa.pcap, link-type 284, snapshot length 262144
tcpdump: unknown data link type 284
    dsa-e                                   : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file dsa.pcap, link-type 284, snapshot length 262144
tcpdump: unknown data link type 284
    eapon1                                  : passed
    edsa                                    : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file edsa.pcap, link-type 285, snapshot length 262144
tcpdump: unknown data link type 285
    edsa-e                                  : TEST FAILED(exit core=0/diffstat=1,0/r=256) with error messages:
reading from file edsa.pcap, link-type 285, snapshot length 262144
tcpdump: unknown data link type 285
```
    
[tcpdump_twppc64le2_20200106_failed.log](https://github.com/the-tcpdump-group/tcpdump/files/4025500/tcpdump_twppc64le2_20200106_failed.log)

**Comment by mcr** [comment]
So, there must be endian related decoding bugs?
How can one of us get access to a ppc64le shell?

**Comment by fxlb** [comment]
@michelmno 
libpcap version problem ?
What gives : `./tcpdump --version` ?

**Comment by michelmno** [comment]
The libpcap is version 1.9.1;  the last released one.
```
[michel@twppc64le2:~/work/tcpdump]
$./tcpdump --version
tcpdump version 4.10.0-PRE-GIT
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1c  28 May 2019
SMI-library: 0.4.8
```

**Comment by fxlb** [comment]
Please try the current libpcap master branch.

**Comment by guyharris** [comment]
> So, there must be endian related decoding bugs?

Most endian-related bugs would probably be bugs on *big*-endian platforms, as the vast majority of desktop computers are little-endian, and even a large number of servers are little-endian.

This appears to be an issue in which 1) OpenSSL's libcrypto library imposes requirements on code that uses it, 2) most implementations of those APIs don't produce problems if certain requirements aren't followed, and 3) the little-endian 64-bit PowerPC/Power ISA implementation *does* produce problems if those requirements aren't followed.

The cleanup I checked in was 1) not using an apparently-undocumented libcrypto API (`EVP_Cipher()`) in favor of documented APIs (so that we could see the requirements) and 2) changing the way we handle padding, including not adding extra padding to already-sufficiently-padded payloads (and not trying to handle un-padded payloads, as we shouldn't be seeing them).

**Comment by guyharris** [comment]
> Please try the current libpcap master branch.

...because some capture files in the `tests` directory of the master branch of tcpdump use link-layer types that are only supported in the master branch of libpcap.

**Comment by infrastation** [comment]
Regarding the commits above, recently I had an IPSec debugging session that included tcpdump among other tools, and as a side effect realized that the `-E` argument can accept much more cipher modes than the man page says. So I wanted to test some ciphers quickly to confirm this guess before changing the man page, and it didn't work as I expected, so after going down the call stack I ended up looking at the [misplaced] `colon` and the [undocumented] `EVP_Cipher()` for a while, and concluding it needs another round later to get it right. Ironically, this was exactly the case.

**Comment by michelmno** [comment]
> Please try the current libpcap master branch.

I confirm that all tests passed if using libpcap master branch.
