### ISSUE TITLE
Query about output formatting

### ISSUE THREAD

**Issue by umar14** [the-tcpdump-group/tcpdump#818]
The usual tcpdump output contains IP addresses with port numbers in decimal. Is there any option to print the port numbers in hexadecimal? If not, where can I add/change code in the source files so that the output prints IP addressed with hexadecimal port numbers. Thanks!

e.g 
192.168.1.2.11500
192.168.1.2.2CEC

**Comment by infrastation** [comment]
There is no such option. As to where to make the modification, the answer depends on the protocol. `tcpport_string()` and `udpport_string()` would be good starting points in the source code. Excuse me, but if the problem still stands it would need to be your homework.

**Comment by umar14** [comment]
I managed to solve this. Here's a link to the solution https://unix.stackexchange.com/a/565482/391341)

Thanks
