### ISSUE TITLE
Tiny typo in suggestion for yum install perl-YAML

### ISSUE THREAD

**Issue by fenner** [the-tcpdump-group/tcpdump#819]
https://github.com/the-tcpdump-group/tcpdump/blob/4addcceb8068eacc3c69bdad6ba18ad58353c3a3/tests/TESTrun#L10

says per-YAML instead of perl-YAML

**Comment by guyharris** [comment]
Fixed in 0a963390e5c109d62456cc9c9119d2bf111616a9.
