### ISSUE TITLE
tcpdump not returning HOST

### ISSUE THREAD

**Issue by nabtron** [the-tcpdump-group/tcpdump#826]
I am using tcpdump on ubuntu 18.04 running nginx and php-fpm 7.2

tcpdump version 4.9.3
libpcap version 1.8.1
OpenSSL 1.1.1  11 Sep 2018

When i try to run this command:

`tcpflow -p -c -i ens4 port 80 | grep -oE '(GET|POST|HEAD) .* HTTP/1.[01]|Host: .*'
`
It returns the first part only and the HOST is empty.

![Screenshot 2020-02-16 at 9 05 11 PM](https://user-images.githubusercontent.com/9471128/74608106-202ea880-5100-11ea-8de0-6fffe8fc3494.jpg)

How can i show the hostname too? 

Edit:

It does show the domain name if i specifically give part of it like:

`tcpflow -p -c -i ens4 port 80 | grep -oE '(GET|POST|HEAD) .* HTTP/1.[012]|Host: .*(com|pk|ca|org)'`

Can it be done without this?

**Comment by guyharris** [comment]
Where is tcpdump being used?  Your command lines use [tcpflow](https://github.com/simsong/tcpflow), not tcpdump; they're different programs, with different developers.

**Comment by fxlb** [comment]
No answer, closing.
