### ISSUE TITLE
Binary bot

### ISSUE THREAD

**Issue by superdano** [the-tcpdump-group/tcpdump#834]
Hola, soy nuevo en esto de los bots. Estoy necesitando un bot para binary que consista en lo siguiente. En dígitos, encima/debajo, cuando el ultimo dígito se mantenga 4 veces consecutivas entre 6 a 9, abra una operación o contrato por debajo de 7

**Comment by guyharris** [comment]
Desafortunadamente, tcpdump no tiene tales bots.
