### ISSUE TITLE
Is it broken? (spring legacy project)

### ISSUE THREAD

**Issue by dlehddus1285** [the-tcpdump-group/tcpdump#835]
![왜안될까](https://user-images.githubusercontent.com/50075475/75576885-27f93000-5aa4-11ea-9e88-c5e25ae79cc4.png)

Why are there no templates???
Please.
Can you teach me?

**Comment by guyharris** [comment]
> Why are there no templates???

It's not our project, so we have no idea.

**Comment by dlehddus1285** [comment]
### **I downloaded Tool3.
and**
![왜 안될까2](https://user-images.githubusercontent.com/50075475/75577926-4eb86600-5aa6-11ea-8b89-fc328bb37592.png)

**I clicked this**

![왜안될까3](https://user-images.githubusercontent.com/50075475/75578235-d0a88f00-5aa6-11ea-8528-902293f7998d.png)

**There is a template in the box.**

**Comment by dlehddus1285** [comment]
this one have't DAO folder
and
it have ex00 folder

![왜안될까4](https://user-images.githubusercontent.com/50075475/75578706-a7d4c980-5aa7-11ea-9b28-32e35435fd06.png)

Not have ex00 folder in workingspace sts
but
 have DAO folder in workingspace sts

**Comment by guyharris** [comment]
This is tcpdump, not whatever you're working with.  We don't know what you're talking about, so we cannot help you.

**Comment by dlehddus1285** [comment]
I must misunderstand English.
I thought it was a question board.

Sorry...

**Comment by guyharris** [comment]
> I must misunderstand English.
> I thought it was a question board.

It's a place to report bugs and other issues with [the tcpdump program](https://en.wikipedia.org/wiki/Tcpdump).  It's not a question board, and isn't for software *other* than tcpdump.
