### ISSUE TITLE
Regression in BGP SAFI 132 route target printing

### ISSUE THREAD

**Issue by fenner** [the-tcpdump-group/tcpdump#853]
In tcpdump 4.9.3, SAFI 132 NLRI are printed like:
```
          Multi-Protocol Reach NLRI (14), length: 14, Flags [O]:
            AFI: IPv4 (1), vendor specific SAFI: Route Target Routing Information (132)
            nexthop: 1.0.0.2, nh-length: 4, no SNPA
              origin AS: 22, route target 0:0 (= 0.0.0.0)
```
In master, some refactoring lead to using a print function for data in the packet against a variable allocated on the heap (which leads to incorrect truncation checks depending on memory layout), and requiring that the prefix length be 96 (the full value):
```
          Multi-Protocol Reach NLRI (14), length: 14, Flags [O]:
            AFI: IPv4 (1), vendor specific SAFI: Route Target Routing Information (132)
            nexthop: 1.0.0.2, nh-length: 4, no SNPA
            (illegal prefix length)
```

The comment at the top of the function correctly points out that `valid lengths are { 0, 32, 33, ..., 96 } bits` but later the incorrect comment `An extended community is 8 octets, so the remaining prefix length must be 64` precedes the check that results in the "(illegal prefix length)" here.

I have a patch developed by a colleague at Arista at https://github.com/fenner/tcpdump/commits/rfc4684 but have not created a pull request because I think it requires some minor cleanups.  However, I heard rustlings that a release might be coming soon, and you may not want to release with this regression.

**Comment by mcr** [comment]
I am trying to get a release ready, but it seems like your pull request would be timely.
