### ISSUE TITLE
ICMPv6 RPL: Empty block

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#858]
https://github.com/the-tcpdump-group/tcpdump/blob/8be0a90ea527d872150dd4c202abf57150f7ee2a/print-icmp6.c#L990,L991

Unknown reason.

**Comment by guyharris** [comment]
> Unknown reason.

Nobody got around to writing the code to dissect it?  I.e., there's no `rpl_dis_print()` to call there?

**Comment by fxlb** [comment]
Yes or this case may have just been forgotten?

**Comment by mcr** [comment]
I originally wrote the code.  I didn't have an example packet, TDD. But, knowing it is a DIS is still useful.
