### ISSUE TITLE
Juniper: About testing ndo->ndo_eflag > 1

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/tcpdump#859]
https://github.com/the-tcpdump-group/tcpdump/blob/306c2a0384af923a73bf234f3c8bc186ceff0b58/print-juniper.c#L1546

It's the only case where `ndo->ndo_eflag` is tested > 1.
It's undocumented we could use -ee[...].

Just replace it by `ndo->ndo_eflag` ?

**Comment by mcr** [comment]
So, bigger values mean more detail. > 1, means it is at least two.  I prefer to document it.

**Comment by fxlb** [comment]
To have more details, we already have -v[v]...
Using -e[e]... could add some confusion.
Also this add more complexity on a test matrix ('', '-v', '-e', '-ve', -'vee', -vve, '-vvee', etc.).
It's why I prefer replace this only case by `ndo->ndo_eflag` to only have ndo_eflag = 0 or ndo_eflag= 1.

**Comment by fxlb** [comment]
Updated to `ndo->ndo_eflag` with commit d27628f311b9afcf5ed6e4b0068e8ba6d6324b14.

**Comment by infrastation** [comment]
To me having `-v` as a knob with one or more detail levels and having `-e` as an on-off switch only looks more consistent too. That said, I would probably never pay enough attention to split this hair in the first place, but in any case it is good to have one more issue resolved and closed.
