### ISSUE TITLE
tcpdump doesn't aceept existence of RST/ACK

### ISSUE THREAD

**Issue by b10s** [the-tcpdump-group/tcpdump#860]
```
$ tcpdump -i eth0 -n 'tcp[tcpflags] == tcp-rst and tcp[tcpflags] == tcp-ack'
tcpdump: expression rejects all packets
```
Change `and` to `or` makes it work.

I have a client which sometimes sends RST/ACK during TLS handshake:
![Selection_851](https://user-images.githubusercontent.com/4618288/85419474-1a186f00-b5ad-11ea-9529-e544d80af600.png)

How can I catch RST/ACK?

**Comment by gvanem** [comment]
What about: `tcp[tcpflags] == tcp-rst or tcp[tcpflags] == tcp-ack`?
The `-d` output looks to match `TH_ACK | TH_RST` only:
```
...
 --- (006) ldxb     4*([14]&0xf)
 --- (007) ldb      [x + 27]
[015](008) jeq      #0x4             jt 10      jf 9    << TH_RST == 0x04
[009](009) jeq      #0x10            jt 10      jf 11   << TH_ACK == 0x10
[010](010) ret      #262144   
[008](011) ret      #0
```

**Comment by fxlb** [comment]
You could try:
'tcp[tcpflags] & (tcp-rst|tcp-ack) == (tcp-rst|tcp-ack)'

**Comment by guyharris** [comment]
> ```
> $ tcpdump -i eth0 -n 'tcp[tcpflags] == tcp-rst and tcp[tcpflags] == tcp-ack'
> tcpdump: expression rejects all packets

Yes.  The expression means "the flags field of the TCP header has only RST set (the value of that field is RST) and the flags field of the TCP header has only ACK set (the value of that field is ACK)", which is always going to be false.

If you want to test whether the flags field of the TCP header has *both* RST *and* ACK set, you need to test for both of those bits, as per @fxlb's example - that says "select only the RST and ACK flags in the flags field, and if the result is "RST and ACK both set", match".

(The filters are processed by libpcap, so this applies whenever libpcap filter are used, so, for example, it applies to Wireshark capture filters as well.)

**Comment by b10s** [comment]
Thank you and sorry for disturbing!

**Comment by fxlb** [comment]
Example added in libpcap filter man page with commit
 the-tcpdump-group/libpcap@89b721fb41bf47b21662752221a4dd13a464da99

**Comment by fxlb** [comment]
Example added in the tcpdump man page with commit 8a33158e8896bcc38ceccf2d52c11af84dbfb971.
