### ISSUE TITLE
DHCP Option Numbers instead of human-readable Labels?

### ISSUE THREAD

**Issue by mikcox** [the-tcpdump-group/tcpdump#866]
First: Thanks for the awesome work on this utility!

I have a question about the specific output of some DHCP packets that I'm grabbing.  Is it possible to specify an option that prints the actual DHCP option _**NUMBERS**_ instead of the human-readable options?  For example, take the `Parameter-Request Option 55` from the output below:

```
18:30:00.199229 a0:cc:2b:xx:xx:xx > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 352: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 338)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from a0:cc:2b:xx:xx:xx, length 310, xid 0xb1c3d483, Flags [none] (0x0000)
	  Client-Ethernet-Address a0:cc:2b:xx:xx:xx
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Request
	    Client-ID Option 61, length 7: ether a0:cc:2b:xx:xx:xx
	    Requested-IP Option 50, length 4: 192.168.xx.xx
	    MSZ Option 57, length 2: 1500
	    Vendor-Class Option 60, length 14: "android-dhcp-9"
	    Hostname Option 12, length 16: "SAMSUNG-SM-G950U"
	    Parameter-Request Option 55, length 10: 
	      Subnet-Mask, Default-Gateway, Domain-Name-Server, Domain-Name
	      MTU, BR, Lease-Time, RN
	      RB, Vendor-Option
	    END Option 255, length 0
	    PAD Option 0, length 0
```

I have only ever figured out how to get the human-readable labels for the `Parameter Request` values, i.e. `"Subnet-Mask, Default-Gateway, Domain-Name-Server, ..."`.  Instead, I'm interested in getting the actual raw option numbers, i.e. `"1,3,6,15,26,28,51,58,59,43"`.

My tcpdump version is:

```
xx@xxxxxxxxxxx:~ $ tcpdump --version
tcpdump version 4.9.3
libpcap version 1.8.1
OpenSSL 1.1.1d  10 Sep 2019
```

Thanks in advance for any help you can provide!  (and, as always, feel free to hit me with an RTFM if it's in there somewhere and I'm just missing it!). 😄

**Comment by infrastation** [comment]
Are you saying that in the output above most options are printed as name + id (see `print-bootp.c` line 641), except the ones inside the Parameter-Request block, which are printed as name only (ibid, line 674), and you are expecting consistent level of detail since these code points come from the same registry?

**Comment by mikcox** [comment]
Yes @infrastation that's correct.

Consistency just for consistency's sake would be neat, but at the very least providing an option to show the IDs within the Parameter-Request block (or any sub-blocks) is really what I'm looking for.

**Comment by infrastation** [comment]
Before commit 0bbf6ed in 2006 tcpdump printed all options as names only, the commit among other things had added the numeric ID to options that are directly under the RFC 1048 block, but not to the options that are under the parameter request block. So it looks like the current inconsistency is unintended.

That said, if you need the option numbers urgently, it would be faster to look them up in the source code and/or the IANA registry. For example, in the output above Subnet-Mask is 1, Default-Gateway is 3, Domain-Name-Server is 6, Domain-Name is 15, MTU is 26, BR is 28, Lease-Time is 51, RN is 58, RB is 59 and Vendor-Option is 43.

For a longer term solution it would help to see a better version of the output format, for example this:
```text
	    Hostname Option 12, length 16: "SAMSUNG-SM-G950U"
	    Parameter-Request Option 55, length 10: 
	      Subnet-Mask Option 1, Default-Gateway Option 3, Domain-Name-Server Option 6, Domain-Name Option 15
	      MTU Option 26, BR Option 28, Lease-Time Option 51, RN Option 58
	      RB Option 59, Vendor-Option Option 43
	    END Option 255, length 0
```
or this:
```text
	    Hostname Option 12, length 16: "SAMSUNG-SM-G950U"
	    Parameter-Request Option 55, length 10: 
	      Subnet-Mask Option 1
	      Default-Gateway Option 3
	      Domain-Name-Server Option 6
	      Domain-Name Option 15
	      MTU Option 26
	      BR Option 28
	      Lease-Time Option 51
	      RN Option 58
	      RB Option 59
	      Vendor-Option Option 43
	    END Option 255, length 0
```
Let's see if there's any more feedback before changing the code.

**Comment by mikcox** [comment]
I've already implemented a short-term workaround by looking up the name -> number conversion as you mentioned; thanks for suggesting that.

I'm very happy with either of the output formats that you proposed.  Happy to let anybody else weigh in if they've got input.

Thanks for the rapid response and quick turnaround!

**Comment by mcr** [comment]
Is this primarily about line feeds?
I find "FOOOptionName Option X" very verbose, and I'd rather it was "[X] Foo Option", but that's just me.
In general, we've had proposals to use XML, but JSON sure seems like a better choice some future version.

**Comment by mikcox** [comment]
@mcr I don't care at all about whether each item is on its own line... I just want to see the option _integer number_ for each option somewhere in the output.

**Comment by fxlb** [comment]
```
> 	    Parameter-Request Option 55, length 10: 
> 	      Subnet-Mask Option 1, Default-Gateway Option 3, Domain-Name-Server Option 6, Domain-Name Option 15
> 	      MTU Option 26, BR Option 28, Lease-Time Option 51, RN Option 58
> 	      RB Option 59, Vendor-Option Option 43
> 	    END Option 255, length 0
```
I prefer this one.

**Comment by infrastation** [comment]
OK, with consistency in mind here is a possible terse format:
```text
	    [53] DHCP-Message, length 1: Request
	    [61] Client-ID, length 7: ether a0:cc:2b:xx:xx:xx
	    [50] Requested-IP, length 4: 192.168.xx.xx
	    [57] MSZ, length 2: 1500
	    [60] Vendor-Class, length 14: "android-dhcp-9"
	    [12] Hostname, length 16: "SAMSUNG-SM-G950U"
	    [55] Parameter-Request, length 10: 
	      [1] Subnet-Mask, [3] Default-Gateway, [6] Domain-Name-Server, [15] Domain-Name
	      [26] MTU, [28] BR, [51] Lease-Time, [58] RN
	      [59] RB, [43] Vendor-Option
	    [255] END, length 0
	    [0] PAD, length 0
```
and another, in the traditional style of TCP, ICMPv6, LMP, BGP etc, which looks the easiest to read to me:
```text
	    DHCP-Message (53), length 1: Request
	    Client-ID (61), length 7: ether a0:cc:2b:xx:xx:xx
	    Requested-IP (50), length 4: 192.168.xx.xx
	    MSZ (57), length 2: 1500
	    Vendor-Class (60), length 14: "android-dhcp-9"
	    Hostname (12), length 16: "SAMSUNG-SM-G950U"
	    Parameter-Request (55), length 10: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Domain-Name (15)
	      MTU (26), BR (28), Lease-Time (51), RN (58)
	      RB (59), Vendor-Option (43)
	    END (255), length 0
	    PAD (0), length 0
```

**Comment by infrastation** [comment]
If everyone would be fine with that, I am going to change the printing to the traditional style (the last one) in a day or two. Or feel free to do that yourself. Or tell me to stop.

**Comment by infrastation** [comment]
Alright, the change is in the master branch.

**Comment by infrastation** [comment]
Thank you everyone for providing your input.

**Comment by mikcox** [comment]
Thanks @infrastation!  This will be very useful; I'm excited to start using it once it makes its way into the package.
