### ISSUE TITLE
Issue with print-rx.c

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/tcpdump#868]
When using gcc 7.1 for [djgpp](https://github.com/andrewwutw/build-djgpp), I get an error when compiling `print-rx.c`:
```c
print-rx.c:717:1: error: conflicting types for 'rx_cache_find'
 rx_cache_find(netdissect_options *ndo, const struct rx_header *rxh,
 ^~~~~~~~~~~~~
print-rx.c:498:12: note: previous declaration of 'rx_cache_find' was here
 static int rx_cache_find(netdissect_options *, const struct rx_header *,
            ^~~~~~~~~~~~~
```
Note there is small difference in prototype vs implementation. 
A `u_int` is in this case not the same as a `uint32_t`.

Applying this patch fixes it:
```diff
--- a/print-rx.c 2020-05-29 15:01:00
+++ b/print-rx.c 2020-08-11 14:32:27
@@ -712,10 +712,9 @@
  * Note that because this is a reply, we're looking at the _source_
  * port.
  */
 static int
 rx_cache_find(netdissect_options *ndo, const struct rx_header *rxh,
-             const struct ip *ip, u_int sport, uint32_t *opcode)
+             const struct ip *ip, uint32_t sport, uint32_t *opcode)
 {
        uint32_t i;
        struct rx_cache_entry *rxent;
```

**Comment by infrastation** [comment]
Thank you for pointing this out. In `print-rx.c` the fields/variables `sport` and `dport` store UDP port number, which is 16-bit, so maybe it would be better to nail the type down as `uint16_t` everywhere consistently.

**Comment by infrastation** [comment]
The change is in the master branch, please test and confirm the fix.

**Comment by infrastation** [comment]
Let's assume the change had solved the problem, please reopen if that's not the case.
