### ISSUE TITLE
LSP Ping timestamps are NTP time, but printed using ts_print()

### ISSUE THREAD

**Issue by fenner** [the-tcpdump-group/tcpdump#873]
RFC4379 is a little confusing, since sometimes it refers to "seconds and microseconds" and sometimes to NTP time.  However, https://www.rfc-editor.org/errata/eid1714 makes it clear that it's NTP time.  print-lspping.c should be decoding the time into a `struct l_fixedpt` and using `p_ntp_time()`.

**Comment by infrastation** [comment]
Sounds almost like a patch!

**Comment by infrastation** [comment]
Resolved as fixed, closing.
