### ISSUE TITLE
DHCP options update to reflect IANA registry

### ISSUE THREAD

**Issue by fenner** [the-tcpdump-group/tcpdump#877]
https://tools.ietf.org/html/rfc3679 returns several DHCP option codes to IANA to be reassigned.  (E.g., 91 and 92, which were subsequently assigned in RFC4388 and are the subject of a pull request).  It's probably worth doing a pass through https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml#options and updating the tcpdump option list to match IANA's.

**Comment by mcr** [comment]
Yes, that's a good idea. And RFC8908/RFC8910 just re-allocated things too.

**Comment by infrastation** [comment]
If this is important enough to be done, it should be important enough at least to tell exactly what needs to be done. It would be even better if you proposed a pull request to cover a bit of the problem space and to make sure the updated code points have .pcap file(s).

**Comment by fenner** [comment]
Ok
