### ISSUE TITLE
cpack.c clashes with a static AirPcap

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/tcpdump#881]
When linking `tcpdump` (or `windump.exe`) with a static version of the `AirPcap` library, there 
is this link error:
```
airpcap_static.lib(RadiotapDecode.obj) : error LNK2005: _cpack_init already defined in cpack.obj
airpcap_static.lib(RadiotapDecode.obj) : error LNK2005: _cpack_uint16 already defined in cpack.obj
airpcap_static.lib(RadiotapDecode.obj) : error LNK2005: _cpack_uint32 already defined in cpack.obj
airpcap_static.lib(RadiotapDecode.obj) : error LNK2005: _cpack_uint64 already defined in cpack.obj
airpcap_static.lib(RadiotapDecode.obj) : error LNK2005: _cpack_uint8 already defined in cpack.obj
```
Can these symbols please be renamed/prefixed to something else?
(but in the meantime I can add some prefix in AirPcap and recompile).

**Comment by infrastation** [comment]
It looks like prefixing these function names with `nd_` would be the right thing to do. Let me try that...

**Comment by infrastation** [comment]
Thank you for reporting the problem and confirming the bugfix, the master branch now includes this change. Closing.
