### ISSUE TITLE
Add GNU-like block size suffix support to savefile's file_size

### ISSUE THREAD

**Issue by qhaas** [the-tcpdump-group/tcpdump#884]
Currently, the `-C file_size` flag uses one-million bytes as its base unit, per [the documentation](https://www.tcpdump.org/tcpdump_man.html):
```
The units of file_size are millions of bytes (1,000,000 bytes, not 1,048,576 bytes).
```

This lacks granularity (i.e. fractions are not allowed; e.g. one cannot record less than 1,000,000 bytes) and without reading the `man` page, one might assume 1,048,576 is a 'megabyte'.  Given a number of users operate on data in base 2, it would be useful to support such units explicitly, such as with [GNU-style suffixes](https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html#Block-size).

With such a feature addition, legacy scripts that currently use `-C` will experience no change in behavior, but users seeking smaller files or desiring base-2 can achieve different human-readable sizes by adding a suffix (e.g. 1,048,576 bytes with `-C 1M`, 1,024 bytes with `-C 1K`, etc.).

**Comment by guyharris** [comment]
Fixed by a36b3aeb877e4357918cfd99ddad5ce913a3a0b6.
