### ISSUE TITLE
How to set date to filename when tcpdump is running as service on ubuntu?

### ISSUE THREAD

**Issue by Kesslarr** [the-tcpdump-group/tcpdump#886]
Hi there,
My OS version: ubuntu 18.04, tcpdump version: 4.9.3, libpcap version: 1.8.1
before I ask this question, I have saw [this](https://github.com/systemd/systemd/issues/2146).
But it doesn't work for me by doubling `$` and `%` signs.
Here is my service
```
[Unit]
Description=use tcpdump to  get pcap
After=network.target

[Service]
Restart=always
RestartSec=30
ExecStart=/usr/sbin/tcpdump -i ens3 -w '/home/dev/try/dump_$$(date +%%Y-%%m-%%d_%%H:%%M:%%S)_' -C 1024

[Install]
WantedBy=multi-user.target
```

after start it, I go to check file, and the output is
`'dump_$(date +%Y-%m-%d_%H:%M:%S)_'`

I want to ask how to set date to filename when tcpdump is running as service on ubuntu?
And I don't want my file name output with `'`, I have tried this:
`ExecStart=/usr/sbin/tcpdump -i ens3 -w /home/dev/try/dump_$$(date +%%Y-%%m-%%d_%%H:%%M:%%S)_ -C 1024`
but if I remove `'` sign, my service can't work successfully.

Does any one know how to solve these problems?
Thanks.

**Comment by infrastation** [comment]
The `$(date ...)` construct you are trying to use is called a command substitution, and it is a part of shell syntax (`man sh`), but not a part of systemd unit file syntax (`man systemd.unit`). You can try running a shell script without the filename argument from a systemd unit, then the shell script would do the command substitution and run tcpdump with the filename. Whether this solves the problem or not, the problem does not belong to tcpdump problem space, at least not in its current design, hence closing.
