### ISSUE TITLE
Can tcpdump be used as a serial port debugger?

### ISSUE THREAD

**Issue by hongyi-zhao** [the-tcpdump-group/tcpdump#895]
I try to debug a driverless vehicle chassis with its CAN interface connected to a computer via an RS-232 to USB converter. Can tcpdump be used as a serial port debugger for this scenario?

Regards,
HY

**Comment by gvanem** [comment]
How about a RS-232 to EtherNet converter like these; from [Perle](https://www.perle.com/products/rs232-to-ethernet.shtml) or on [eBay](https://www.ebay.com/itm/RS485-RS232-to-Ethernet-RJ45-Serial-Port-Server-TCP-UDP-Full-Duplex-Modbus-RTU/193270613934?_trkparms=ispr%3D1&hash=item2cffd387ae:g:VFEAAOSwPwpeAabk&amdata=enc%3AAQAFAAACcBaobrjLl8XobRIiIML1V4Imu%252Fn%252BzU5L90Z278x5ickkfKe2vUidqHRg3XM2X2xOVMeOsmwrkr%252FUSoe3HKKy5K0H0%252Fj0p%252BPheuLEQLT%252BHm%252BypBbNRsKSxoXsvhsDadtH7hA01YzZpaoowGcFJEb12%252F%252BHVZybd%252BrE%252FOmKNGaG7JXAq9XYbeYJXGejmXdjArDwQAkN2Fb12QkBMTNPv3CVoScYVpSDJu3sIwYZGqASBf5qEn2dnRdtM%252FSmOCed%252BtGN8PQ1C3%252Figf3P7FjYPGHNAQ14jRKt7F1y6ZSnUQyuBQw5m6WtIlamOegWY3W3k0e9vRhXYHArayaU2Jl%252FTIGvMYnil0AebUX0FO1A1GgKaPpsEjiNLg88q2t1fQDW7hqB%252FPJTTLDwPfVsNGVV4f8HsIgtU%252Bu4hOu7fRnIxSic%252BaOIudlzMUqAyUH8MSEKG8ELRhjsR%252BjxG4%252FkBNis62ANpCVbZs7E%252FrJMWMGiDXFi1VWxBemDcW7kB5kVaFrHGlgS%252B91ZnHhnzfkfJ9kgF%252Fcci4Ir%252Fovo0zeHlAhgK4QxO6gsSpSnzkLy1PRvVV4twQ%252Fp7cq8y9cT5HvNASC5FfekM8sZldHruL2D24l1sSMUV1Ye4ckpG0AJXBtlf7i2LKBN4uXfUedk9wqPskACiWEnGBo49yDCWkyormdvXKQyPvYqv5Nw0KslNjpk0Owed%252BIH7BZCEiE2peJCR%252FFie4NfEOEDt7MFIVsv3X7UkT5%252FhkD7ywgqZbTh4kemvpibE6Bc7MCFShMD3HxazPey4%252BOziVmr2nOIjvWAM%252FRHomhQ1qGOwuHObufeH2dydY2tI5XPPw%253D%253D%7Ccksum%3A1932706139349cf091781dd64f4c886e3b59206d05d2%7Campid%3APL_CLK%7Cclp%3A2334524).

**Comment by hongyi-zhao** [comment]
The connection method I mentioned above is suggested by the chassis vendor. OTOH, I don't have the device you told here.

**Comment by guyharris** [comment]
There are two issues here:

1. Using tcpdump to capture the traffic.
2. Using tcpdump to parse the captured traffic.

Currently, tcpdump can't do the first of those except with an RS-232 to Ethernet converter.  Changing that would need support in libpcap, with a libpcap module that can read from the converter.

Changing the latter would require tcpdump dissector support for whatever formats are produced by the converters in question.  I doubt that what CAN support is in tcpdump can handle the various forms of RS-232 to Ethernet supported by the converters, so that would require tcpdump changes.

What RS-232 to USB converter are you using?

**Comment by hongyi-zhao** [comment]
> Changing the latter would require tcpdump dissector support for whatever formats are produced by the converters in question. I doubt that what CAN support is in tcpdump can handle the various forms of RS-232 to Ethernet supported by the converters, so that would require tcpdump changes.

It seems wireshark can do this job. See the following for more info:

https://wiki.wireshark.org/CaptureSetup/USB
https://www.wireshark.org/docs/dfref/u/usb.html

> What RS-232 to USB converter are you using?

IMO, it's only a converter. Are there different kinds of such converters?

**Comment by guyharris** [comment]
> It seems wireshark can do this job.

What Wireshark can do is capture raw USB traffic and dissect it.  How useful that would be for dissecting USB-to-serial traffic is another matter - there does not appear to be any code path in Wireshark to hand the data on USB to any CAN dissector.

> Are there different kinds of such converters?

To quote [the Wikipedia "USB adapter" page](https://en.wikipedia.org/wiki/USB_adapter):

> For the computer to be able to detect and process the data signals drivers must be installed on the computer. Some chip models have drivers installed by default, including FTDI, while drivers for other chip models must be manually installed (e.g. for Windows and MacOS, WCH CH340, Silicon Labs 210x.

The requirement for a driver seems to indicate that not all adapters use the same protocol over USB to encapsulate serial data.

**Comment by gvanem** [comment]
>  ... not all adapters use the same protocol over USB to encapsulate serial data.

Some converters (like the one from eBay above) uses MQTT which should be simple to decode.
