### ISSUE TITLE
4.99.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [the-tcpdump-group/tcpdump#896]
libpcap 1.10.0
Full test suite log output is in attachment
[tcpdump_test_suite_failing.txt](https://github.com/the-tcpdump-group/tcpdump/files/5761242/tcpdump_test_suite_failing.txt)

**Comment by gvanem** [comment]
Seems the `-n` flags is not used.

**Comment by guyharris** [comment]
Either that, or this is a patched version of tcpdump with [a Red Hat/Fedora change](https://src.fedoraproject.org/rpms/tcpdump/blob/master/f/0007-Introduce-nn-option.patch) applied; that change causes `-n` to turn off *address to host name* lookups but not *port number to port name* lookups, with `-nn` being required to disable both lookups.

See pull request #852, which confusingly thought that we had made that change to `-n` (we hadn't) and that the man page needed to be updated to reflect that (it didn't).  As the bug indicates, we do not plan to make that change to `-n`.

If you are building with a version of tcpdump that has that change, if you want to tests to work, you will have to *undo* that change.

**Comment by kloczek** [comment]
> Either that, or this is a patched version of tcpdump with a Red Hat/Fedora change applied; that change causes -n to turn off address to host name lookups but not port number to port name lookups, with -nn being required to disable both lookups.

Yest it is ..
>See pull request #852, which confusingly thought that we had made that change to -n (we hadn't) and that the man page needed to be updated to reflect that (it didn't). As the bug indicates, we do not plan to make that change to -n.

OK I'll try to disable that patch and retest.
Will back shortly.

**Comment by kloczek** [comment]
OK. After remove that patch eveythinkg is OK now.
Sorry ..

Clocing and thank you.
