### ISSUE TITLE
Issue with RTL8812au driver

### ISSUE THREAD

**Issue by pigsfoot** [the-tcpdump-group/tcpdump#902]
I have recently changed WiFi adapter and now using an Alfa AWUS036ACS USB adapter which uses the RTL8811au chipset. Everything is installed on a RPI 4 running Buster.

Before swapping adapters i used another Alfa card which was 2.4Ghz only and used a different driver... worked great but now want 2.4 & 5 Ghz networks.

The TCPdump command i run is /usr/sbin/tcpdump  -l -I -n -e -tt -i %s  type mgt  subtype probe-req'%capture_iface

The %capture_iface being wlan0

This was working fine and sent data direct to a server. Since swapping adapters and changing drivers i no longer have any data being sent.

One other difference, before swapping the adapter the RPI booted up interface wlan0 straight into monitor mode ( i presume due to the "l" switch above". This no longer happens so i have had to write a short script that execute son boot to load wlan0 into monitor mode. Both ifconfig and iw dev confirms the interface is in monitor mode when set.

iwconfig output

wlan0     IEEE 802.11  Mode:Monitor  Frequency:2.412 GHz  Tx-Power=20 dBm
      Retry short  long limit:2   RTS thr:off   Fragment thr:off
      Power Management:off

iw dev output

phy#0
    Interface wlan0
            ifindex 3
            wdev 0x1
            addr 00:c0:ca:ab:d3:91
            type monitor
            channel 1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
            txpower 20.00 dBm

I can run tcpdump -i wlan0 and get to see all the packets being captured. I can run tcpdump -w [filename] -i wlan0 and everything writes to a file.

TCPdump --version = 4.9.3-1#deb10ul

What isn't working is the data is no longer sent to my server. Nothing else has change, only the wifi adapter and driver.

**Comment by guyharris** [comment]
> This was working fine and sent data direct to a server.

Presumably via a pipe or something such as that, or by writing to a file system mounted from the server, as tcpdump doesn't *itself* have a "send packets to a server" mechanism.

**Comment by pigsfoot** [comment]
Hi @guyharris thanks for the response. I think you may be right re the pipe but i dont think thats the issue. However having looking into this in more depth there does seem to be an issue with tcpdump not getting the same data although i expect this to be possible driver related rather than tcpdump, but perhaps you may still be able to help.

Using the same RPI system, all i have done is swapped adapters and rebooted each time. I have used a known working adapter ( Alfa AWUS036NHA ) and taken a capture and then put back the new adapter ( Alfa AWUS036AWS ) which is the one that doesn't work and done the same, The two captures are different and the 36AWS capture ( not working ) seems to have less information captured. I have attached two files showing the capture hoping it may well help.

For my system to work all i am capturing is the mac address and a date / time stamp.

The first image is from AWUS036NHA - working
The second image is from adapter AWUS036ACS - non working 

![Alfa 36NHA](https://user-images.githubusercontent.com/4267997/104715615-af807980-571e-11eb-9c5c-67d3717b792e.JPG)
![Alfa 36ACS](https://user-images.githubusercontent.com/4267997/104715616-b0b1a680-571e-11eb-8270-a8c707d20c09.JPG)

Thanks

**Comment by guyharris** [comment]
The only difference I see is that, in the first capture, there are some data frames, but there are no data frames in the second capture.

A Google search for

    not seeing data frames monitor mode "rtl8812au"

didn't turn up anything that seemed to directly address that, but it did turn up [the Kismet page on Wi-Fi sources](https://www.kismetwireless.net/docs/readme/datasources_wifi/) that says

> The Linux Wi-Fi source is known to support, among others:
> 
>     ...
> 
> - Realtek USB 802.11AC (rtl8812au, rtl8814), with the proper drivers. There are no in-kernel drivers for these cards. There are multiple forks of the out-of-kernel tree, with varying levels of support for monitor mode and injection; the most likely to work is the variant maintained by the Aircrack-NG team, which can be found at https://github.com/aircrack-ng/rtl8812au.git

so make sure you're running *that* driver.

See also [this note on the aircrack-ng blog](https://aircrack-ng.blogspot.com/2017/08/on-drivers-rtl8812au-wn722n-monitor.html), which discusses issues with various adapters and Linux drivers.

**Comment by pigsfoot** [comment]
Thanks @guyharris  for the feedback and for looking into this for me, much appreciated.

Just to confirm i am using the driver mentioned above.

Its all very odd, as i mentioned it works fine with another card and hence different driver, its just frustrating that when i use the new card i can run tcpdump manually and i do get results but for some reason or another they are not being passed to my server yet nothing else has changed so it must be the driver. as several people mention, this driver has "issues".

Thanks

**Comment by infrastation** [comment]
Closing as resolved.
