### ISSUE TITLE
tcpdump  --no-promiscuous-mode Which scenes are invalid?

### ISSUE THREAD

**Issue by Pony07** [the-tcpdump-group/tcpdump#908]
Problem description: Why can tcpdump turn off promiscuous mode and still receive broadcast packets.
After turning off the promiscuous mode, which scenes can receive broadcast packets, and which scenes can't?

1. man tcpdump description
```
--no-promiscuous-mode
              Don't put the interface into promiscuous mode.  Note that the interface might be in promiscuous mode for some other reason; hence, `-p' cannot be used as an  abbre‐
              viation for `ether host {local-hw-addr} or ether broadcast'.
```
2. tcpdump -i ens39 -p udp -e
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens39, link-type EN10MB (Ethernet), capture size 262144 bytes
22:30:35.722363 00:0c:29:6a:87:11 (oui Unknown) > **Broadcast**, ethertype IPv4 (0x0800), length 60: 10.10.2.2.50726 > 10.10.2.3.6666: UDP, length 2
```

3. Network interface configuration
```
root@ubuntu:/home/ubuntu# ifconfig ens39
ens39     Link encap:Ethernet  HWaddr 00:50:56:2c:3f:68  
          inet addr:10.10.2.1  Bcast:10.10.2.3  Mask:255.255.255.252
          UP BROADCAST RUNNING MULTICAST  MTU:900  Metric:1
          RX packets:63 errors:0 dropped:0 overruns:0 frame:0
          TX packets:63 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3856 (3.8 KB)  TX bytes:3856 (3.8 KB)
```

**Comment by guyharris** [comment]
> Why can tcpdump turn off promiscuous mode and still receive broadcast packets.

Because promiscuous mode is necessary to receive packets that would normally be ignored by an adapter.

I.e., it's necessary to receive *unicast* packets that are not sent to a MAC address the adapter treats as its own.

*Broadcast* packets are *intended* to be received by *all* adapters - that's what "broadcast" refers to.

**Comment by Pony07** [comment]
Thanks for your answer. In other words, turning off promiscuous mode can block unknown unicast traffic.

**Comment by guyharris** [comment]
> In other words, turning off promiscuous mode can block unknown unicast traffic.

Turning off promiscuous mode turns off the reception of unicast traffic not being sent to one of your adapter's unicast MAC addresses and the reception of multicast traffic not being sent to one of the multicast MAC addresses the adapter's configured to receive.

It does *not* turn off reception of packets that *are* sent to one of the adapter's unicast or multicast MAC addresses, whether it's "known" or "unknown".
