### ISSUE TITLE
Miscompilation with clang in tpaddr_print_ip 

### ISSUE THREAD

**Issue by Changochen** [the-tcpdump-group/tcpdump#913]
A minor error.

Environment:
```bash
./tcpdump --version
tcpdump version 5.0.0-PRE-GIT
libpcap version 1.8.1
OpenSSL 1.1.1d  10 Sep 2019
commit: 534916a46d41a38536ecd50830321e374169a7a4

# tested clang
clang version 7.0.1-8 (tags/RELEASE_701/final)
clang version 11.0.1

# OS
Ubuntu 18.04
```

Build process:
```bash
git clone https://github.com/the-tcpdump-group/tcpdump.git
cd tcpdump
mkdir build && cd build && ../configure && make -j
```

When compiled with `clang` and `-O2`, `tpaddr_print_ip` looks like the following:

```asm
   0x410150 <tpaddr_print_ip>:             push   r14
   0x410152 <tpaddr_print_ip+2>:        push   rbx
   0x410153 <tpaddr_print_ip+3>:        push   rax
   0x410154 <tpaddr_print_ip+4>:        mov    rbx,rdi
   0x410157 <tpaddr_print_ip+7>:        cmp    edx,0x800  <- compare with edx, size 32bit
   0x41015d <tpaddr_print_ip+13>:       je     0x41016d <tpaddr_print_ip+29>
   0x41015f <tpaddr_print_ip+15>:       movzx  eax,dx
   0x410162 <tpaddr_print_ip+18>:       cmp    eax,0x1000 <- compare with dx, size 16bit
```
So when `pro = 0x12340800`, it will not be considered as valid, while tcpdump compiled with `-O0` and `-O3` will consider it as valid.

**Comment by mcr** [comment]
sounds like a CLANG bug.  How can we work around it?

**Comment by guyharris** [comment]
> So when `pro = 0x12340800`, it will not be considered as valid, while tcpdump compiled with `-O0` and `-O3` will consider it as valid.

Given that `pro` is a `u_short`, how can it ever be 0x12340800?

**Comment by guyharris** [comment]
And its value is extracted with code that grabs 2 octets from the packet buffer and assembles them into a 2-byte unsigned integral value, so that can't be bigger than 0xFFFF.

**Comment by Changochen** [comment]
> And its value is extracted with code that grabs 2 octets from the packet buffer and assembles them into a 2-byte unsigned integral value, so that can't be bigger than 0xFFFF.

Yes, you are right. I checked with its callers and found it's same to generate such code. I should have double checked. Sorry for that. Closing this issue
