### ISSUE TITLE
No tag for 4.99.1

### ISSUE THREAD

**Issue by dvzrv** [the-tcpdump-group/tcpdump#922]
Hi! I package tcpdump for Arch Linux and noticed, that there is no tag for the version 4.99.1 in this repository (yet), but the version is already available on the official website.

For transparency and bug reporting reasons it would be great if you could push that tag. Thanks! :)

**Comment by mcr** [comment]
I remember pushing the tag, but apparently it didn't really go.
The tag is now there.
