### ISSUE TITLE
I got error "tcpdump: Couldn't change ownership of savefile" on ubuntu 20.04

### ISSUE THREAD

**Issue by qqzhong** [the-tcpdump-group/tcpdump#928]
Hi, 
I got error "tcpdump: Couldn't change ownership of savefile" on ubuntu 20.04.
I tried to reinstall the tcpdump but it does not work yet.

tcpdump --version 
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1f  31 Mar 2020

How can I check and what should I check to fix the error. 
please advise.
Thanks!

**Comment by qqzhong** [comment]
> Hi,
> I got error "tcpdump: Couldn't change ownership of savefile" on ubuntu 20.04.
> I tried to reinstall the tcpdump but it does not work yet.
> 
> tcpdump --version
> tcpdump version 4.9.3
> libpcap version 1.9.1 (with TPACKET_V3)
> OpenSSL 1.1.1f 31 Mar 2020
> 
> How can I check and what should I check to fix the error.
> please advise.
> Thanks!

And more, I disabled the selinux on ubuntu 20.04.
But tcpdump still does not work.

**Comment by infrastation** [comment]
Could you add the exact command and its output?

**Comment by mcr** [comment]
It sounds like you are running tcpdump in a directory that you don't have permission to write to.

**Comment by infrastation** [comment]
Closing due to lack of feedback.

**Comment by HakjunMIN** [comment]
Ridiculously, file extension should be `pcap`. Resolved by changing file name to '`aaa.pcap` for same error

**Comment by mcr** [comment]
I think that this is some ubuntu thing about how it uses group permissions and AppArmor.

**Comment by infrastation** [comment]
I do not remember seeing such an error during those few years when I used Ubuntu 20.04. If this bug exists, but nobody ever specifies the steps to reproduce it, then it is most likely nobody will fix it.

**Comment by mtt0** [comment]
> Ridiculously, file extension should be `pcap`. Resolved by changing file name to `aaa.pcap` for same error

Thanks. I meet the same error.

<img width="774" alt="image" src="https://github.com/the-tcpdump-group/tcpdump/assets/17849741/209e1173-d744-4d8d-9ade-4bb7099c6fdb">

**Comment by infrastation** [comment]
The problem does not reproduce in a freshly installed Ubuntu 20.04.6 VM with all updates:
```
root@ubuntu2004:~# apt-get install tcpdump
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tcpdump is already the newest version (4.9.3-4ubuntu0.2).
tcpdump set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.
root@ubuntu2004:~# tcpdump -i any "udp and port 65087" -w sip.pcap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
^C0 packets captured
0 packets received by filter
0 packets dropped by kernel
root@ubuntu2004:~# rm sip.pcap 
root@ubuntu2004:~# tcpdump -i any "udp and port 65087" -w sip.cap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
^C0 packets captured
0 packets received by filter
0 packets dropped by kernel
root@ubuntu2004:~# tcpdump --version
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1f  31 Mar 2020
```
Is there some other custom configuration that is necessary to reproduce the problem? I note the hostname is `k8s00`, is this a Kubernetes setup?

**Comment by mtt0** [comment]
No, I juse install tcpdump by `apt install tcpdump` and didn't perform any custom configuration.
```shell
root@k8s00:~# tcpdump --version
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by mtt0** [comment]
> AppArmor

On my machine, there is a `/etc/apparmor.d/usr.sbin.tcpdump` file:
```
# vim:syntax=apparmor
#include <tunables/global>

/usr/sbin/tcpdump {
  #include <abstractions/base>
  #include <abstractions/nameservice>
  #include <abstractions/user-tmp>

  capability net_raw,
  capability setuid,
  capability setgid,
  capability dac_override,
  capability chown,
  network raw,
  network packet,

  # for -D
  @{PROC}/bus/usb/ r,
  @{PROC}/bus/usb/** r,

  # for finding an interface
  /dev/ r,
  @{PROC}/[0-9]*/net/dev r,
  /sys/bus/usb/devices/ r,
  /sys/class/net/ r,
  /sys/devices/**/net/** r,

  # for -j
  capability net_admin,

  # for tracing USB bus, which libpcap supports
  /dev/usbmon* r,
  /dev/bus/usb/ r,
  /dev/bus/usb/** r,

  # for init_etherarray(), with -e
  /etc/ethers r,

  # for USB probing (see libpcap-1.1.x/pcap-usb-linux.c:probe_devices())
  /dev/bus/usb/**/[0-9]* w,

  # for -z
  /{usr/,}bin/gzip ixr,
  /{usr/,}bin/bzip2 ixr,

  # for -F and -w
  audit deny @{HOME}/.* mrwkl,
  audit deny @{HOME}/.*/ rw,
  audit deny @{HOME}/.*/** mrwkl,
  audit deny @{HOME}/bin/ rw,
  audit deny @{HOME}/bin/** mrwkl,
  owner @{HOME}/ r,
  owner @{HOME}/** rw,

  # for -r, -F and -w
  /**.[pP][cC][aA][pP] rw,

  # for convenience with -r (ie, read pcap files from other sources)
  /var/log/snort/*log* r,

  /usr/sbin/tcpdump mr,

  # allow printing to stdout/stderr when inside a container
  # (LP: #1667016)
  /dev/pts/* rw,

  # Site-specific additions and overrides. See local/README for details.
  #include <local/usr.sbin.tcpdump>
}
```

**Comment by mtt0** [comment]
Anyway, if it works as designed, we could just ignore this issue.
