### ISSUE TITLE
wolfSSL Support

### ISSUE THREAD

**Issue by haydenroche5** [the-tcpdump-group/tcpdump#931]
Hello tcpdump. I'm an engineer with wolfSSL, which is a TLS and cryptography library geared toward embedded use cases. wolfSSL has an OpenSSL compatibility layer, making it possible to port existing projects that use OpenSSL to wolfSSL with relative ease. A client of ours has had us do just that for tcpdump: https://github.com/wolfSSL/osp/pull/59

I've read your contribution rules/guidelines, but before I go through the motions and submit a pull request, I wanted to ask if your development team would be interested in having these changes upstream, first. I look forward to hearing from you!

**Comment by mcr** [comment]
Hello, yes, wolfSSL patches would be appreciated.

I reviewed osp#59, and aside from the comment that I left about buffer_size, the major issue is that we are trying to get away from autoconf, and only do cmake in the future, so we need cmake patches as well.

The bigger impact is that we'll need to do CI for at least some wolfSSL.

**Comment by haydenroche5** [comment]
Hi @mcr, thanks for taking the time to look at my patch and this issue.

I am reasonably proficient in CMake. I'll see if I can modify the patch to also support the CMake build.

**Comment by mcr** [comment]
> I am reasonably proficient in CMake. I'll see if I can modify the patch to also support the CMake build.

I'm sure not.  I feel that I missed a training manual on non-trivial use.

**Comment by haydenroche5** [comment]
> I'm sure not. I feel that I missed a training manual on non-trivial use.

**Comment by haydenroche5** [comment]
@mcr, I've gotten around to opening a PR for this: https://github.com/the-tcpdump-group/tcpdump/pull/944
