### ISSUE TITLE
MPTCP: Add missing MP_CAPABLE Flags

### ISSUE THREAD

**Issue by RuiCunhaM** [the-tcpdump-group/tcpdump#933]
Hi!

I would like to add support for the MP_CAPABLE C Flag in MPTCP as described in [section 3.1 RFC8684](https://datatracker.ietf.org/doc/html/rfc8684#section-3.1), however this flag states that:

> the sender of this option will not accept
                 additional MPTCP subflows to the source address and
                 port, and therefore the receiver MUST NOT try to open
                 any additional subflows toward this address and port.

This is a bit hard to convey in a few words, following the tcpdump style, so I would like to know what is the best solution for this issue. A few solutions like `C` or `C Flag` were already discussed, but before opening a PR I want to make sure what best fits.

Original Issue: https://github.com/multipath-tcp/mptcp_net-next/issues/190

**Comment by infrastation** [comment]
It looks like this decoder still treats `MP_CAPABLE` flags the way draft-ietf-mptcp-multiaddressed defined it before revision 10:
```c
#define MP_CAPABLE_C                    0x80
#define MP_CAPABLE_S                    0x01
```
(C-bit is incorrect and S-bit is unused)

Commit 4738c1f tried to update respective code to version 1 (RFC 8684), but did not update the flags field to v0/v1. So the current code implements a mix of pre-v0, v0 and v1 interpretations.

That said, as far as a mostly-stateless packet analyzer is concerned, it would be expected to print correctly whether a particular flag is set in a particular packet, but it would not be expected to model or to interpret the protocol instance behaviour at the endpoints (unless trivial and useful).

This way, there is an obvious issues with `mp_capable_print()`, which is hopefully is not too difficult to resolve. Do you see any other issues?

**Comment by RuiCunhaM** [comment]
Hi!

> (C-bit is incorrect and S-bit is unused)

Yes I noticed this also and I was planing to fix it with my patch. As far as other issues go I haven't notice anything else. ( at least in the mp_capable_print(), I can't say for sure for the other options at the moment ).





> That said, as far as a mostly-stateless packet analyzer is concerned, it would be expected to print correctly whether a particular flag is set in a particular packet, but it would not be expected to model or to interpret the protocol instance behaviour at the endpoints (unless trivial and useful).

I'm sorry but I'm still not sure what is the best output to use when the flag in present, since something like _Do not attempt to establish new subflows to this address and port_ seems a bit to verbose for tcpdump, if that makes sense.

Thanks.

**Comment by mcr** [comment]
> Hi!
> This is a bit hard to convey in a few words, following the tcpdump style, so I would like to know what is the best solution for this issue. A few solutions like `C` or `C Flag` were already discussed, but before opening a PR I want to make sure what best fits.
> 
> Original Issue: [multipath-tcp/mptcp_net-next#190](https://github.com/multipath-tcp/mptcp_net-next/issues/190)

I think that you are asking about how to best present this to users.
Well.... I'd ask more MPTCP users what they want...  ultimately of course, there would ideally be part of the man page to explain this.

**Comment by infrastation** [comment]
In [the registry](https://www.iana.org/assignments/tcp-parameters/tcp-parameters.xhtml#mptcp-handshake) these 8 bits don't have terse labels (especially the C-bit), so a classic solution would be just to print the symbols A through H. Please see the array `mp_tcprst_flags` in the same file for an example and the two functions that can print the flags octet nicely (`bittok2str()` and `bittok2str_nosep()`).

**Comment by RuiCunhaM** [comment]
That makes sense. I'll have a look.
Thank you.

**Comment by RuiCunhaM** [comment]
Since we went for printing the flags this way, I ended up adding all the missing flags from the option, even though some of them are not yet used, however they are described.
Printing the A flag may be a bit redundant, since when this one is present checksum is printed too, but I don't think that's a problem.
