### ISSUE TITLE
Response for the security issue I have emailed

### ISSUE THREAD

**Issue by meweez** [the-tcpdump-group/tcpdump#940]
hi,
I have sent two emails for security issues two weeks ago with this mail address: maryam.ebr@student.sharif.edu
 but I did not get any email shows the moderator's decision.
how can I get any updates?
Thanks

P.S: sorry for asking this here! I Did not know where to ask.

**Comment by mcr** [comment]
I have found the only week old email in the spam trap from September 6, and released it.

**Comment by meweez** [comment]
> I have found the only week old email in the spam trap from September 6, and released it.

Thanks.

**Comment by meweez** [comment]
> I have found the only week old email in the spam trap from September 6, and released it.

how much time does it take to answer the email?
thank you
