### ISSUE TITLE
tcpdump -A can not capture traffic on loopback interface

### ISSUE THREAD

**Issue by apuppy** [the-tcpdump-group/tcpdump#956]
I used the command below to capture grpc protocol at tcp port 9505.
`tcpdump -A port 9505`
But there is nothing captured with this command. While when I used another way of this command below. The traffic at tcp port 9505 was successfully captured.
`tcpdump -i lo -A port 9505`
I want know why. Can somebody help me to explain the reason that `tcpdump -A` can not capture the traffic on lo interface. Thank you very much.

**Comment by guyharris** [comment]
> The traffic at tcp port 9505 was successfully captured.
> `tcpdump -i lo -A port 9505`

...

> Can somebody help me to explain the reason that `tcpdump -A` can not capture the traffic on lo interface.

Can somebody explain to me why, if `tcpdump -i lo -A port 9505`, which means "capture traffic to or from port 9505 on the lo interface and print each packet in ASCII", successfully captures packets, you think that `tcpdump -A` can not capture the traffic on the lo interface.

Note that `tcpdump -A port 9505` is *NOT* guaranteed to capture on the lo interface - it captures on the *default* interface, and libpcap (and thus tcpdump) tries to pick, as the preferred interface, an interface that's *NOT* a loopback interface.  For example, on a Debian 11.0.1 (virtual) machine:

```
$ sudo tcpdump -A port 9505
[sudo] password for gharris: 
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on ens33, link-type EN10MB (Ethernet), snapshot length 262144 bytes
```

captures on the ens33 interface, *NOT* the lo interface.

**Comment by infrastation** [comment]
This support request seems to be addressed to a reasonable extent and there is no follow-up, hence closing.

**Comment by apuppy** [comment]
> 

Thank you. Your explanation let me know that tcpdump's default behavior. If I did not explicitly tell tcpdump to capture on which interface. It will choose the first interface which does not include a loopback interface. Thank you.
