### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by zidingz** [the-tcpdump-group/tcpdump#963]
Hey there!

I belong to an open source security research community, and a member (@geeknik) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by infrastation** [comment]
When you created this issue, the new issue form should have presented you with a template that starts with "To report a security issue...", could you confirm this is the case?

**Comment by JamieSlome** [comment]
@infrastation - looks like we missed that!

You can view the report directly [here](https://huntr.dev/bounties/20d7d783-b866-40de-ad50-8ebbf50658a4/).

**Comment by infrastation** [comment]
Thank you, let me have a close look.

**Comment by infrastation** [comment]
This request has been fully addressed, closing.
