### ISSUE TITLE
How to mention TCP tcp.analysis.out_of_order under command line

### ISSUE THREAD

**Issue by piddalagi** [the-tcpdump-group/tcpdump#981]
Dear Team,

can you please tell me how to mention filters like "tcp.analysis.out_of_order" under command line.
I need it badly for some automation.

tcpdump version 4.9.3
libpcap version 1.8.1
OpenSSL 1.1.1  11 Sep 2018

**Comment by guyharris** [comment]
> can you please tell me how to mention filters like "tcp.analysis.out_of_order"

That's a *Wireshark* filter.  The command line equivalent would be with TShark, not with tcpdump; for better or worse, tcpdump doesn't do that level of sequence number analysis.

**Comment by piddalagi** [comment]
appreciate you quick response Harris.

I will check tshark.
