### ISSUE TITLE
Compiling tcpdump from source with DPDK 19.02 enabled libpcap results in bug

### ISSUE THREAD

**Issue by kyrlon** [the-tcpdump-group/tcpdump#983]
When compiling tcpdump from source, I get this bug response :

```
checking for local pcap library... ../libpcap/libpcap.a
checking for pcap-config... ../libpcap/pcap-config
checking for pcap_loop... no
configure: error: This is a bug, please follow the guidelines in CONTRIBUTING and include the
config.log file in your report.  If you have downloaded libpcap from
tcpdump.org, and built it yourself, please also include the config.log
file from the libpcap source directory, the Makefile from the libpcap
source directory, and the output of the make process for libpcap, as
this could be a problem with the libpcap that was built, and we will
not be able to determine why this is happening, and thus will not be
able to fix it, without that information, as we have not been able to
reproduce this problem ourselves.
```
I'm currently attempting to compile tcpdump from source using libpcap with DPDK enabled. I initially followed the instructions from [here](https://github.com/the-tcpdump-group/libpcap/pull/790#issue-391483003) without issue, but when I attempted to copmile tcpdump, I received the bug response.

Current System:
```
[root@localhost tcpdump]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

```
uname -a
Linux localhost.localdomain 3.10.0-1062.12.1.rt56.1042.el7.x86_64 #1 SMP PREEMPT RT Wed Feb 5 10:31:05 CET 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to Reproduce:
* Installing DPDK 19.02 from source
    ```
    sudo wget --no-check-certificate https://fast.dpdk.org/rel/dpdk-19.02.tar.xz
    tar -xf ./dpdk-19.02.tar.xz
    mv ./dpdk-19.02 /opt/
    cd /opt/dpdk-19.02/
    export RTE_SDK=/opt/dpdk-19.02
    export RTE_TARGET=x86_64-native-linuxapp-gcc
    sed -i 's/CONFIG_RTE_BUILD_SHARED_LIB=n/CONFIG_RTE_BUILD_SHARED_LIB=y/' $RTE_SDK/$RTE_TARGET/.config
    sudo make install T=x86_64-native-linuxapp-gcc DESTDIR=~/dpdk-19.02
    ```
* Installing libpcap from source
    ```
    git clone https://github.com/the-tcpdump-group/libpcap.git
    sudo mkdir -p /opt/pcap
    sudo yum install byacc flex -y
    sudo chmod 777 /opt/pcap
    cd libpcap/
    ./configure --prefix=/opt/pcap --with-dpdk=$RTE_SDK
    make
    sudo make install
    ```
* Installing tcpdump from source
    ```
    git clone https://github.com/the-tcpdump-group/tcpdump.git
    sudo mkdir -p /opt/tcpdump/
    cd tcpdump/
    CFLAGS='-I /opt/pcap/include' LDFLAGS='-L /opt/pcap/lib' ./configure --prefix=/opt/tcpdump/
    make
    sudo make install
    ```
    
When compiling tcpdump and libpcap without DPDK enabled, the following output is obtained for versions:
```
/opt/tcpdump/bin/tcpdump --version
tcpdump version 5.0.0-PRE-GIT
libpcap version 1.11.0-PRE-GIT (with TPACKET_V3)
```

Attached I have added the following for libpcap compilation : 
* config.log
* makefile
* output of make

Attached I have added the following for tcpdump compilation :
* config.log

The goal is to use tcpdump to generate pcap files in order to inspect traffic passing through the DPDK interface. 

Please let me know if there are any other information needed to replicate this bug.

---------------------

[output_make_libpcap.txt](https://github.com/the-tcpdump-group/tcpdump/files/8326476/output_make_libpcap.txt)
[config_tcpdump.log](https://github.com/the-tcpdump-group/tcpdump/files/8326483/config_tcpdump.log)
[config_libpcap.log](https://github.com/the-tcpdump-group/tcpdump/files/8326486/config_libpcap.log)
[Makefile_libpcap.txt](https://github.com/the-tcpdump-group/tcpdump/files/8326492/Makefile_libpcap.txt)

**Comment by guyharris** [comment]
```
sudo wget --no-check-certificate https://fast.dpdk.org/rel/dpdk-19.02.tar.xz
tar -xf ./dpdk-19.02.tar.xz
mv ./dpdk-19.02 /opt/
cd /opt/dpdk-19.02/
export RTE_SDK=/opt/dpdk-19.02
export RTE_TARGET=x86_64-native-linuxapp-gcc
sed -i 's/CONFIG_RTE_BUILD_SHARED_LIB=n/CONFIG_RTE_BUILD_SHARED_LIB=y/' $RTE_SDK/$RTE_TARGET/.config
sudo make install T=x86_64-native-linuxapp-gcc DESTDIR=~/dpdk-19.02
```

I think you omitted a

    make config T=$RTE_TARGET

step before the "sed" step.  (And the "make install" step could be `sudo make install T=$RTE_TARGET DESTDIR=~/dpdk-19.02`.)

I also had to hammer on some files when building on Ubuntu 20.04 to keep various warnings from stopping the build.

**Comment by guyharris** [comment]
(And "sudo" shouldn't be necessary for wget, unless you're extracting into a directory to which you have no cite permission for some reason, or for make install - and unnecessary sudos are *not* a good idea.)

**Comment by guyharris** [comment]
>     ./configure --prefix=/opt/pcap --with-dpdk=$RTE_SDK

Presumably you meant

    ./configure --prefix=/opt/pcap --with-dpdk=$HOME/dpdk-19.02

as 1) you didn't install DPDK in `$RTE_SDK`, you installed it in `~/dpdk-19.02` and 2) `~` doesn't work except at the beginning of a shell token, so you have to use `$HOME` to refer to your home directory instead.

**Comment by guyharris** [comment]
The doc/build-sdk-meson.txt file in the DPDK 19.02 source says

```
INSTALLING DPDK USING THE MESON BUILD SYSTEM
---------------------------------------------

Summary
--------
For many platforms, compiling and installing DPDK should work using the
following set of commands::

        meson build
        cd build
        ninja
        ninja install

This will compile DPDK in the ``build`` subdirectory, and then install the
resulting libraries, drivers and header files onto the system - generally
in /usr/local. A package-config file, ``libdpdk.pc``,  for DPDK will also
be installed to allow ease of compiling and linking with applications.

After installation, to use DPDK, the necessary CFLAG and LDFLAG variables
can be got from pkg-config::

        pkg-config --cflags libdpdk
        pkg-config --libs libdpdk
```

DPDK 19.02 appears to have about 117(!) libraries; this means that it is simply not worth it for libpcap's configure script to attempt to handle DPDK if it doesn't provide a `libdpdk.pc` file to indicate which libraries are required.  Without knowing that set of libraries, the *libpcap* configure script can't find a working libpcap.

I will, therefore, be removing *all* support for finding DPDK with *any* mechanism other than `pkg-config` from the libpcap configure script and CMake configuration files.

As the mechanism you used to install DPDK does not appear to install a `.pc` file, this means that it will not work if you want to build libpcap with DPDK support.  Use [the Meson build system](https://mesonbuild.com) to build and install it - this includes [Ninja](https://ninja-build.org), so you will need that as well.

**Comment by kyrlon** [comment]
Thank you for your suggestions. I was able to make changes to the original concerns you've made for my original post. Eventually, I was able to get tcpdump to recognize my dpdk interfaces. For the record, here are the steps I took to get tcpdump to work:

Installing DPDK 19.02 from source
```
yum install meson ninja-build -y
wget --no-check-certificate https://fast.dpdk.org/rel/dpdk-19.02.tar.xz
tar -xf ./dpdk-19.02.tar.xz
mv ./dpdk-19.02 /opt/
cd /opt/dpdk-19.02/
mkdir -p /root/dpdk-19.02
meson build -Dprefix=/root/dpdk-19.02
cd build
ninja
ninja install
``` 
 
Installing libpcap
```
pkg-config --cflags libdpdk
pkg-config --libs libdpdk
mkdir -p /opt/pcap

cd temp/libpcap/
./configure --prefix=/opt/pcap --with-dpdk=/root/dpdk-19.02
make
make install
```

Installing tcpdump
```
cd temp/tcpdump/
CFLAGS='-I /opt/pcap/include' LDFLAGS='-L /opt/pcap/lib' ./configure --prefix=/opt/tcpdump/
make
make install
```

Running tcpdump enabled DPDK
```
export PKG_CONFIG_PATH=/root/dpdk-19.02/lib64/pkgconfig/:$PKG_CONFIG_PATH
/opt/tcpdump/bin/tcpdump -D
1.eno1 [Up, Running, Connected]
2.any (Pseudo-device that captures on all interfaces) [Up, Running]
3.lo [Up, Running, Loopback]
4.eno2 [Up, Disconnected]
5.enp134s0f0 [Up, Disconnected]
6.enp24s0f0 [Up, Disconnected]
7.usbmon2 (Raw USB traffic, bus number 2)
8.usbmon1 (Raw USB traffic, bus number 1)
9.usbmon0 (Raw USB traffic, all USB buses) [none]
10.nflog (Linux netfilter log (NFLOG) interface) [none]
11.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]
12.dpdk:0 (Data Plane Development Kit (DPDK) Interface dpdk:0, MAC:F7-8B-27-A5-2E-BB, PCI:0000:26:00.1)
13.dpdk:1 (Data Plane Development Kit (DPDK) Interface dpdk:1, MAC:0B-33-1C-60-2E-AD, PCI:0000:42:00.1)
```
