### ISSUE TITLE
SIGUSR1 and other non-lethal signals may corrupt binary pcap output

### ISSUE THREAD

**Issue by ferrieux** [the-tcpdump-group/tcpdump#997]
The handy "live control by signal" features (`SIGNAL_REQ_INFO` and `SIGNAL_FLUSH_PCAP`) may occasionally hit a `write()` syscall, for example while writing binary pcap to a pipe (`-w -`). In this case, the `write()` is **not** restarted, resulting in a *short write*, which necessarily corrupts any binary output format.

To exercise this, simply pipe your pcap to another `tcpdump` instance for validation, and repeatedly kick the first one with `SIGUSR1`.
With a reasonably high load, after a few tens of seconds, you'll get a corruption.
(Note you can lower the bar by giving a complex BPF filter to the second `tcpdump`, so that it incurs some backpressure, which increases the time spent blocking in `write()` in the first one).

```shell
$ tcpdump -w - | tcpdump -nn -r - > /dev/null
...
tcpdump: 1950889 packets captured, 1951467 packets received by filter, 0 packets dropped by kernel
tcpdump: 1954318 packets captured, 1954602 packets received by filter, 0 packets dropped by kernel
tcpdump: 1957245 packets captured, 1957801 packets received by filter, 0 packets dropped by kernel
tcpdump: 1959581 packets captured, 1959891 packets received by filter, 0 packets dropped by kernel
tcpdump: 1961849 packets captured, 1961945 packets received by filter, 0 packets dropped by kernel
tcpdump: pcap_loop: invalid packet capture length 2943430581, bigger than snaplen of 262144
```
Note that a method exists to request transparent restarting of syscalls for specified signals: `SA_RESTART`, to be passed as a flag to `sigaction()`.

As it turns out, the function `setsignal()` in [tcpdump.c](../blob/master/tcpdump.c#L2747) does calls `sigaction()` with `SA_RESTART`, but only for `SIGCHLD`.

I'm submitting PR #998 to extend this to both `SIGNAL_REQ_INFO` and `SIGNAL_FLUSH_PCAP`, when defined.

**Comment by infrastation** [comment]
For future problem fixes please consider placing the problem statement closest to the solution (into the commit message or into a comment next to the changed code, whichever seems the most appropriate).

**Comment by ferrieux** [comment]
Thanks, noted. Using `--pretty=oneline` all the time, I tend to forget there's space in there ;)
